var linesImages = ["1","2","3", "4", "12", "13", "14", "15", "16", "19", "20", "21", "22", "23", "25", "26", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "54", "55", "56", "60", "61", "62", "63", "64", "65", "66", "67", "68", "70", "71", "81", "82", "83", "84", "85", "1380", "3000", "3030", "4100", "4101", "4110", "4310", "4500", "5000", "5100", "5110", "5120", "5130", "5200", "6010", "6020", "6030", "6051", "6052", "6060", "6070", "6080", "6200", "6550", "7000", "7020", "7110", "7300", "7320", "7330", "7350", "7360", "7500", "A", "B", "C", "D", "E", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "EXP1", "EXP2", "EXP3", "G2", "G3", "G4", "G5", "G6", "G40", "G50", "G51", "G60", "G61", "G70", "NVA", "NVB", "NVC"];

var dictStops = [["GEN120TOISE", "Le Pont-de-Claix, 120 Toises"],
["GENGAROUTIE", "Grenoble, Gare Routière"],
["GEN16AOUT44", "Saint-Martin-le-Vinoux, Résistance"],
["GEN8MAI1945", "Saint-Martin-d'Hères, 8 mai 1945"],
["GENABBEGREG", "Grenoble, Abbé Grégoire"],
["GENADELAUNE", "Échirolles, Auguste Delaune"],
["GENAIGUIHEX", "Meylan, Aiguinards-Hexagone"],
["GENALB1BELG", "Grenoble, Albert 1er de Belgique"],
["GENALBERGES", "Vaulnaveys-le-Haut, Les Alberges"],
["GENALEGRANG", "Vif, Allée des Granges"],
["GENALEMBERT", "Grenoble, D'Alembert"],
["GENALLIANCE", "Vizille, L'Alliance"],
["GENALLIES", "Grenoble, Alliés"],
["GENALLOVES", "Saint-Martin-d'Hères, Les Alloves"],
["GENALPEXPO", "Eybens, Alpexpo"],
["GENALSACELO", "Grenoble, Alsace-Lorraine"],
["GENANATFRAN", "Grenoble, Anatole France"],
["GENANCIEMAI", "Fontaine, Ancienne Mairie"],
["GENANCIGARE", "Seyssins, Ancienne Gare"],
["GENANCMAIRI", "Meylan, Ancienne Mairie"],
["GENANGONNES", "Brié-et-Angonnes, Les Angonnes"],
["GENANGUISSE", "Saint-Martin-d'Hères, Anguisses"],
["GENANMAL", "Jarrie, Clos Jouvin"],
["GENARAGO", "Grenoble, Arago"],
["GENARBERGES", "Seyssinet-Pariset, Aristide Bergès"],
["GENARGOUD", "Seyssins, L'Argoud"],
["GENARGOUGES", "Grenoble, André Argouges"],
["GENARLEQUIN", "Grenoble, Arlequin"],
["GENARNAUDS", "Domène, Les Arnauds"],
["GENARZELIER", "Le Gua, L'Arzelier"],
["GENAUGUFERR", "Échirolles, Auguste Ferrier"],
["GENAUGURAVI", "Grenoble, Auguste Ravier"],
["GENAVREPUB", "Bresson, Avenue de la République"],
["GENBACHELAR", "Grenoble, Bachelard"],
["GENBAJATIER", "Grenoble, Bajatière"],
["GENBALMETTE", "Claix, La Balmette"],
["GENBALZAZ", "Varces-Allières-et-Risset, Balzac"],
["GENBANCHARD", "Saint-Martin-le-Vinoux, La Banchardière"],
["GENBARBET", "Quaix-en-Chartreuse, Le Barbet"],
["GENBARNA", "Saint-Égrève, Collège Barnave"],
["GENBASCULE", "Saint-Paul-de-Varces, La Bascule"],
["GENBASMONT", "Quaix-en-Chartreuse, Bas de Mont-Quaix"],
["GENBASPET", "Quaix-en-Chartreuse, Bas de Petesset"],
["GENBASQUAIX", "Quaix-en-Chartreuse, Le Bas de Quaix"],
["GENBASTILLE", "La Tronche, Bastille"],
["GENBAUCHES", "Claix, Les Bauches"],
["GENBAYANNE", "Miribel-Lanchâtre, Bayanne"],
["GENBAYARD", "Échirolles, Bayard"],
["GENBEALIERE", "Meylan, Les Béalières"],
["GENBEAU", "Claix, Beau Dunois"],
["GENBEAUDONI", "Montbonnot-Saint-Martin, Baudonniere"],
["GENBEAULIEU", "Brié-et-Angonnes, Beaulieu"],
["GENBEAUREVO", "Sassenage, Beaurevoir"],
["GENBEAUSITE", "Seyssinet-Pariset, Beau Site"],
["GENBEAUVERT", "Grenoble, Beauvert"],
["GENBEAUVOIR", "Seyssins, Beauvoir"],
["GENBELAIR", "Eybens, Bel Air"],
["GENBELLEDON", "Saint-Égrève, Belledonne"],
["GENBELLEVU", "Saint-Égrève, Bellevue"],
["GENBELLEVUE", "Claix, Bellevue"],
["GENBELVEDER", "Seyssinet-Pariset, Belvédère"],
["GENBERGVERC", "Seyssinet-Pariset, Bergès - Vercors"],
["GENBERIVIER", "Meylan, Bérivière"],
["GENBERLIOGN", "Varces-Allières-et-Risset, Berliognière"],
["GENBERRIAT", "Grenoble, Berriat-Le Magasin"],
["GENBERULLE", "Grenoble, Place de Bérulle"],
["GENBERYL", "Veurey-Voroize, Le Béryl"],
["GENBIBLIUNI", "Gières, Bibliothèques Universitaires"],
["GENBIOLLE", "Saint-Égrève, La Biolle - Gare"],
["GENBIOLOGIE", "Gières, Universités - Biologie"],
["GENBIRHAKEI", "Grenoble, Bir Hakeim"],
["GENBLANCFON", "Sassenage, Blanc Fontaine"],
["GENBLANCHON", "Saint-Martin-d'Hères, Parc Jo Blanchon"],
["GENBONNAIS", "Saint-Égrève, Les Bonnais"],
["GENBONPASTE", "Grenoble, Bon Pasteur"],
["GENBOUCHDV", "Seyssinet-Pariset, Bouchayer - Hôtel de Ville"],
["GENBOULODRO", "Claix, Boulodrome-Ecole"],
["GENBOURG", "Murianette, Le Bourg"],
["GENBOURNET", "Seyssins, Le Bournet"],
["GENBRESSON", "Bresson, Bresson Mairie"],
["GENBRIE", "Brié-et-Angonnes, Mont Rolland"],
["GENBRIECOLE", "Brié-et-Angonnes, L'Olympe"],
["GENBRIEGLIS", "Brié-et-Angonnes, Eglise"],
["GENBRIOT", "Murianette, La Briot"],
["GENBRUYERE", "Grenoble, La Bruyère-Parc Jean Verlhac"],
["GENBUCLOS", "Corenc, Buclos"],
["GENBUIS", "Saint-Martin-le-Vinoux, La Buisseratière"],
["GENBUSSEROL", "Meylan, Busserolles"],
["GENCAB", "Grenoble, Colonel Dumont"],
["GENCAMPVIZ", "Vizille, Camping"],
["GENCAP38", "Saint-Égrève, CAP 38"],
["GENCAPDESH", "Saint-Égrève, Cap des H'"],
["GENCAPUCHE", "Grenoble, Capuche"],
["GENCARINA", "Saint-Martin-d'Hères, Le Carina"],
["GENCARONBAS", "La Tronche, La Carronnerie Basse"],
["GENCARONRIE", "La Tronche, Carronnerie - Ile d'Amour"],
["GENCARRIERE", "Claix, Carrière"],
["GENCASANOVA", "Échirolles, Danielle Casanova"],
["GENCASAVILL", "Grenoble, Casamaures - Village"],
["GENCASBONNE", "Grenoble, Caserne de Bonne"],
["GENCASSOULE", "Miribel-Lanchâtre, Cassoulet"],
["GENCEACAMB", "Grenoble, Marie-Louise Paris - CEA"],
["GENCEDRE", "Corenc, Le Cèdre"],
["GENCEMOI", "Grenoble, Cémoi"],
["GENCENSOCIO", "Poisat, Centre Socio-Culturel"],
["GENCENTHEOL", "La Tronche, Centre Théologique"],
["GENCENTRAER", "Quaix-en-Chartreuse, Centre Aéré"],
["GENCENTRESU", "Seyssins, Grand Pré - Centre Sud"],
["GENCENTRSOC", "Seyssinet-Pariset, L'Arche"],
["GENCHABER", "Jarrie, Les Chaberts"],
["GENCHALET", "Vif, Le Chalet"],
["GENCHAMBORD", "Varces-Allières-et-Risset, Chambord"],
["GENCHAMECHA", "Sassenage, Chamechaude"],
["GENCHAMP", "Montchaboud, Champ Clocher"],
["GENCHAMPFIL", "Eybens, Champ Fila"],
["GENCHAMPION", "Grenoble, Championnet"],
["GENCHAMPLAR", "Meylan, Champlars"],
["GENCHAMPROM", "Saint-Martin-d'Hères, Champ Roman"],
["GENCHAMPRON", "Gières, Champrondet"],
["GENCHAMPSD", "Champ-sur-Drac, ZA La Plaine"],
["GENCHAMPSEL", "Grenoble, Champs-Elysées"],
["GENCHAMPY", "Saint-Égrève, Champy"],
["GENCHAMROC", "Meylan, Champ Rochas"],
["GENCHANDON", "Le Pont-de-Claix, Edmée Chandon"],
["GENCHANTEFE", "Vizille, Chantefeuille"],
["GENCHANTERA", "Claix, La Chanteraie"],
["GENCHARBON", "Jarrie, Les Charbonnaux"],
["GENCHARLMIC", "Fontaine, Charles Michels"],
["GENCHARMETT", "Fontaine, Charmettes"],
["GENCHARPEN", "Quaix-en-Chartreuse, Le Charpen"],
["GENCHARRIER", "Claix, Charrières"],
["GENCHAT", "Vizille, Place du Château"],
["GENCHATBEAU", "Sassenage, Château de Beaurevoir"],
["GENCHATEAU", "Échirolles, Le Château"],
["GENCHATEAUQ", "Quaix-en-Chartreuse, Le Château"],
["GENCHATEAUX", "Veurey-Voroize, Chemin du Parc"],
["GENCHATELAR", "Veurey-Voroize, Châtelard"],
["GENCHATELIE", "Eybens, La Châtelière"],
["GENCHATSASS", "Sassenage, Château de Sassenage"],
["GENCHAULNES", "Noyarey, Chaulnes"],
["GENCHAUMES", "Claix, Les Chaumes"],
["GENCHAUMETI", "Meylan, Chaumetière"],
["GENCHAUMIER", "Seyssins, Hameau des Chaumières"],
["GENCHAVANT", "Grenoble, Chavant"],
["GENCHEABBE", "Claix, Chemin de l'Abbé"],
["GENCHEMAUPA", "Noyarey, Rue du Maupas"],
["GENCHEMBATO", "Corenc, Batonnière"],
["GENCHEMI", "Saint-Martin-le-Vinoux, Canet"],
["GENCHEMVER", "Saint-Égrève, Chemin vert"],
["GENCHENES", "Sassenage, Les Chênes"],
["GENCHENEVIE", "Domène, Chenevières"],
["GENCHIAISE", "Proveysieux, La Chiaise"],
["GENCHIEZE", "Claix, La Chièze"],
["GENCHOLLET", "Brié-et-Angonnes, Le Chollet"],
["GENCHOPIN", "Saint-Martin-d'Hères, Chopin"],
["GENCHORCOND", "Grenoble, Chorier - Condorcet"],
["GENCHRISTUR", "Grenoble, Christophe Turc"],
["GENCHURU", "Le Sappey-en-Chartreuse, Churut"],
["GENCIMEBOUR", "Vif, La Cime du Bourg"],
["GENCIMEMONT", "Quaix-en-Chartreuse, La Cime de Mont-Quaix"],
["GENCIMENTIE", "Claix, Les Cimentiers"],
["GENCIMESEYP", "Seyssinet-Pariset, Cimetière"],
["GENCIMETIGA", "Seyssins, Garlettes"],
["GENCIMETIGS", "La Tronche, Cimetière du Grand Sablon"],
["GENCITEINTE", "Grenoble, Cité Internationale"],
["GENCITELABE", "Saint-Martin-d'Hères, Cité Labeye"],
["GENCITEMACE", "Grenoble, Cité Jean Macé"],
["GENCITEPMIS", "Grenoble, Cité Paul Mistral"],
["GENCITESCOL", "Varces-Allières-et-Risset, Collège Jules Verne"],
["GENCLAIXMAI", "Claix, Claix Mairie"],
["GENCLEMENCE", "Grenoble, Clémenceau"],
["GENCLINBELD", "Saint-Martin-d'Hères, Clinique Belledonne"],
["GENCLINDAU", "Seyssins, Clinique - Portail"],
["GENCLINMUT", "Grenoble, Groupe Hospitalier Mutualiste"],
["GENCLOSDOMI", "Le Pont-de-Claix, Clos Dominique"],
["GENCLOSDOR", "Grenoble, Clos d'Or"],
["GENCLOSGRUE", "Saint-Martin-le-Vinoux, Clos Gérard Gruel"],
["GENCLOSSTMA", "Saint-Martin-le-Vinoux, Clos Saint Martin"],
["GENCOLARZEL", "Château-Bernard, Col de l'Arzelier"],
["GENCOLAVIER", "Mont-Saint-Martin, Colavière"],
["GENCOLCHART", "Saint-Martin-le-Vinoux, Collège Chartreuse"],
["GENCOLCLEME", "Saint-Martin-le-Vinoux, Col de Clémencières"],
["GENCOLCOMBO", "Claix, Col de Comboire"],
["GENCOLI", "Saint-Martin-d'Hères, Coli"],
["GENCOLLSAUL", "Eybens, Collège des Saules"],
["GENCOLMANHE", "Échirolles, Colonel Manhès"],
["GENCOLMATTO", "Vizille, Collège Les Mattons"],
["GENCOLPORTE", "Sarcenas, Col de Porte"],
["GENCOLVENCE", "Corenc, Col de Vence"],
["GENCOMBALEY", "Proveysieux, Planfay Combaleyre"],
["GENCOMBOIRE", "Échirolles, Comboire"],
["GENCOMMANAL", "La Tronche, Commandant Nal"],
["GENCOMMANDE", "Échirolles, Commanderie"],
["GENCOMPLEXE", "Sassenage, Complexe Sportif"],
["GENCONDIUNI", "Saint-Martin-d'Hères, Condillac - Universités"],
["GENCONDORCE", "Grenoble, Condorcet"],
["GENCONRADKI", "Saint-Martin-le-Vinoux, Conrad Kilian"],
["GENCORENCMA", "Corenc, Corenc Mairie"],
["GENCORENCVI", "Corenc, Corenc Village"],
["GENCORNEDOR", "Corenc, La Corne d'Or"],
["GENCORNIERS", "Vizille, Les Corniers"],
["GENCOSSEY", "Claix, Cossey"],
["GENCOTEAU", "Claix, Le Coteau"],
["GENCOTESASS", "Sassenage, Les Côtes"],
["GENCOUBERTI", "Domène, Coubertin"],
["GENCROISEM", "Saint-Martin-d'Uriage, Croisement 6"],
["GENCROIX", "Saint-Paul-de-Varces, La Croix"],
["GENCROIXROU", "Saint-Martin-d'Hères, Croix Rouge"],
["GENCRXROLLA", "Claix, La Croix Rolland"],
["GENCULFROID", "Venon, Cul Froid"],
["GENCURIVERC", "Fontaine, Curie - Vercors"],
["GENCUVILLEU", "Saint-Égrève, Cuvilleux"],
["GENCXCIBENS", "Meylan, Croix de Cibeins"],
["GENCXMONTFL", "Corenc, Croix de Montfleury"],
["GENCXPATRE", "Saint-Martin-d'Hères, Croix du Pâtre"],
["GENCXRAMEAU", "Meylan, Croix des Rameaux"],
["GENDEGAULLE", "Eybens, Général de Gaulle"],
["GENDENPAPIN", "Échirolles, Denis Papin"],
["GENDEPORTES", "Grenoble, Rue des Déportés"],
["GENDETOURBE", "Meylan, La Détourbe"],
["GENDOMENEMA", "Domène, Domène Mairie"],
["GENDOYENGOS", "La Tronche, Doyen Gosse"],
["GENDRAC", "Claix, Mémorial"],
["GENDRAC2", "Échirolles, Drac"],
["GENDRCALME", "Grenoble, Vallier - Docteur Calmette"],
["GENDRIANT", "Grenoble, Driant"],
["GENDRMARTIN", "Grenoble, Docteur Martin"],
["GENDRMAZET", "Grenoble, Docteur Mazet"],
["GENDRSCHWEI", "Grenoble, Docteur Schweitzer"],
["GENDUBEDOUT", "Grenoble, Hubert Dubedout - Maison du Tourisme"],
["GENECHALIER", "Veurey-Voroize, Les Echalières"],
["GENECHIGARE", "Échirolles, Echirolles Gare"],
["GENECOLE", "Quaix-en-Chartreuse, Ecoles"],
["GENECOLELP", "Champ-sur-Drac, Le Pavillon"],
["GENECOLEREY", "Vif, Ecole Reymure"],
["GENECOLHOSP", "Échirolles, Ecoles Hospitalières"],
["GENECRINS", "Fontaine, Les Écrins"],
["GENECUREUIL", "Échirolles, Ecureuil"],
["GENEDELWEIS", "Gières, Edelweiss"],
["GENEDISON", "Grenoble, Edison"],
["GENEDMOESMO", "Grenoble, Edmond Esmonin"],
["GENEDROSTAN", "Saint-Martin-d'Hères, Edmond Rostand"],
["GENEDVAILLA", "Saint-Martin-d'Hères, Edouard Vaillant"],
["GENEGLISESE", "Saint-Égrève, Eglise"],
["GENEGRECOLE", "Proveysieux, Proveysieux Village"],
["GENEGREGUA", "Proveysieux, Pont du Gua"],
["GENEGREMOLL", "Proveysieux, Le Mollard"],
["GENEJCURIE", "Vizille, Ecoles Joliot-Curie"],
["GENELSATRIO", "Saint-Martin-d'Hères, Elsa Triolet"],
["GENEMILGUEY", "Grenoble, Emile Gueymard"],
["GENENGENIER", "Sassenage, Les Engenières"],
["GENEPICEA", "Gières, Epicéa"],
["GENESCLANGO", "Grenoble, Esclangon"],
["GENESPLANAD", "Grenoble, Annie Fratellini-Esplanade"],
["GENESSARTS", "Échirolles, Essarts - La Butte"],
["GENETIEGRAP", "Saint-Martin-d'Hères, Etienne Grappe"],
["GENEUGENESU", "Grenoble, Eugène Sue"],
["GENEYGALA", "Corenc, Eygala"],
["GENFACPHARM", "Meylan, Faculté de Pharmacie"],
["GENFAUCONNI", "Seyssinet-Pariset, Fauconnière"],
["GENFELIXVIA", "Grenoble, Félix Viallet"],
["GENFIANCEY", "Saint-Égrève, Chemin Fiancey"],
["GENFLAUCLOS", "Grenoble, Flaubert - Clos d'Or"],
["GENFOCHAIRE", "Mont-Saint-Martin, Fochaire"],
["GENFOCHFERI", "Grenoble, Foch - Ferrié"],
["GENFONDRATE", "Claix, Fond Ratel"],
["GENFONTAGNE", "Varces-Allières-et-Risset, Fontagneux"],
["GENFONTAHDV", "Fontaine, Fontaine Hôtel de Ville - La Source"],
["GENFONTAINA", "Fontaine, Les Fontainades - Le Vog"],
["GENFONTANIL", "Fontanil-Cornillon, Palluel"],
["GENFONTANIM", "Fontanil-Cornillon, Le Fontanil Mairie"],
["GENFONTCIM", "Fontanil-Cornillon, Le Fontanil Cimetière"],
["GENFONVIEIL", "Quaix-en-Chartreuse, Fontvieille"],
["GENFRBLUMET", "Sassenage, François Blumet"],
["GENFRENAIE", "Venon, La Frênaie"],
["GENFRQUESNA", "Échirolles, François Quesnay"],
["GENFURONNIE", "Claix, Furonnières"],
["GENGABFAURE", "Saint-Martin-d'Hères, Gabriel Fauré"],
["GENGAGNIERE", "Saint-Martin-le-Vinoux, Louis Gagnière"],
["GENGALOCHER", "Saint-Martin-d'Hères, Galochère"],
["GENGARCINS", "Vif, Les Garcins"],
["GENGARDE", "Saint-Paul-de-Varces, La Garde"],
["GENGAREJARR", "Jarrie, Jarrie Gare"],
["GENGARENNE", "Corenc, La Garenne"],
["GENGARES", "Grenoble, Gares"],
["GENGARLETTE", "Seyssins, Garlettes"],
["GENGAVANIER", "Saint-Égrève, Gavanière"],
["GENGAY", "Saint-Martin-d'Hères, Gay"],
["GENGAYLUSSA", "Échirolles, Gay Lussac"],
["GENGDCHATEL", "Saint-Martin-d'Hères, Grand Châtelet"],
["GENGDTRONCH", "La Tronche, Grande Tronche"],
["GENGDVERGER", "Champ-sur-Drac, Grand Verger"],
["GENGERARPHI", "Fontaine, Gérard Philipe"],
["GENGIERGARE", "Gières, Gières Gare - Universités"],
["GENGIGNOUX", "Grenoble, Maurice Gignoux"],
["GENGIRAUDIE", "Varces-Allières-et-Risset, La Giraudière"],
["GENGLAIEULS", "Saint-Martin-d'Hères, Glaïeuls"],
["GENGLAIRAUX", "Saint-Égrève, Les Glairaux"],
["GENGLIERES", "Échirolles, Les Glières"],
["GENGONNADIE", "Champ-sur-Drac, Marcel Paul"],
["GENGRANDPRE", "Seyssinet-Pariset, Grand Pré"],
["GENGRANG", "Saint-Égrève, Grange Haute"],
["GENGRANGE", "Vif, La Grange"],
["GENGRANGECH", "Eybens, La Grange du Château"],
["GENGRANGES", "Échirolles, Les Granges"],
["GENGRANIER", "Meylan, Granier"],
["GENGRAPH", "Échirolles, Centre du graphisme"],
["GENGRDPLACE", "Grenoble, Grand'place"],
["GENGRDSABLO", "La Tronche, Grand Sablon"],
["GENGREHOTEL", "Grenoble, Grenoble Hôtel de Ville"],
["GENGRESIVAU", "Corenc, Grésivaudan"],
["GENGRIMPI", "Vizille, Le Grimpillon"],
["GENGROSCHEN", "Varces-Allières-et-Risset, Le Gros Chêne"],
["GENGRUGLIAS", "Échirolles, Grugliasco"],
["GENGUEBOUTE", "Meylan, Gué du Boutet"],
["GENGUERIMAN", "Saint-Martin-le-Vinoux, 16 Août 1944"],
["GENGUICHARD", "Vaulnaveys-le-Haut, Les Guichards"],
["GENGUILE", "Sarcenas, Guilletière"],
["GENGUSTRIVE", "Grenoble, Gustave Rivet"],
["GENGUYMOCQU", "Échirolles, Guy Mocquet"],
["GENHBERLUNI", "Saint-Martin-d'Hères, Hector Berlioz - Universités"],
["GENHDUNANT", "Grenoble, Henri Dunant"],
["GENHEBOURG", "Herbeys, Herbeys Le Bourg"],
["GENHENRIREY", "Seyssins, Henri Rey"],
["GENHENRIWAL", "Saint-Martin-d'Hères, Henri Wallon"],
["GENHOPITSUD", "Échirolles, Hôpital Sud"],
["GENHOPMICHA", "La Tronche, Hôpital Michallon"],
["GENHOPOLICE", "Grenoble, Hôtel de Police"],
["GENHORLOGE", "Saint-Martin-le-Vinoux, Horloge"],
["GENHOTELBEL", "Saint-Martin-le-Vinoux, Hôtel Bellevue"],
["GENHOUILLEB", "Saint-Martin-d'Hères, Houille Blanche"],
["GENHTMEYLAN", "Meylan, Haut-Meylan"],
["GENHVENCE", "Corenc, Hameau de Vence"],
["GENILESCORD", "Veurey-Voroize, Iles Cordées"],
["GENILESMARS", "Le Pont-de-Claix, Iles de Mars"],
["GENILEVERTE", "Grenoble, Ile Verte"],
["GENILIADE", "Eybens, L'Iliade"],
["GENINRIA", "Montbonnot-Saint-Martin, INRIA"],
["GENIRENEJOL", "Le Pont-de-Claix, Irène Joliot-Curie"],
["GENIUTUFRAP", "Gières, Universités - IUT - UFRAPS"],
["GENJACOBINS", "Vif, Jacobins"],
["GENJAILLIER", "Meylan, Les Jaillières"],
["GENJAVAUX", "Eybens, Les Javaux"],
["GENJBRUANT", "Vaulnaveys-le-Haut, Ecole Jules Bruant"],
["GENJEANNARC", "Grenoble, Jeanne d'Arc"],
["GENJEANPREV", "Fontaine, Jean Prévost"],
["GENJFLANDRI", "Meylan, Jules Flandrin"],
["GENJRACINE", "Grenoble, Jean Racine"],
["GENJULESGUE", "Fontaine, Jules Guesde"],
["GENJULESREY", "La Tronche, Jules Rey"],
["GENKARBEN", "Saint-Égrève, Karben"],
["GENKARLMARX", "Fontaine, Karl Marx"],
["GENLABAUME", "Seyssins, La Baume"],
["GENLACHAL", "Saint-Martin-le-Vinoux, Lachal"],
["GENLACHARRI", "Le Gua, La Charrière"],
["GENLACHENAI", "Venon, La Chênaie"],
["GENLACOMBE", "Gières, La Combe"],
["GENLACUCHE", "Veurey-Voroize, La Cuche"],
["GENLAFAURIE", "Venon, La Faurie"],
["GENLAFOY", "Meylan, La Foy"],
["GENLAGAY", "Bresson,  Bresson Lagay"],
["GENLAGNEAU", "Seyssins, L'Agneau"],
["GENLAGOMMA", "Saint-Martin-le-Vinoux, Le Gomma"],
["GENLALUIRE", "Le Pont-de-Claix, Gendarmerie"],
["GENLALUNE", "Seyssins, Rue de la Lune"],
["GENLAMELLE", "Champ-sur-Drac, La Melle"],
["GENLAMONTA", "Saint-Égrève, La Monta"],
["GENLAMURAIL", "Seyssinet-Pariset, Murailles"],
["GENLANGEVIN", "Échirolles, Paul Langevin"],
["GENLAPIERRE", "Le Gua, La Pierre"],
["GENLAPLAINE", "Seyssinet-Pariset, La Plaine"],
["GENLAPOYA", "Fontaine, La Poya"],
["GENLARIVO", "Mont-Saint-Martin, La Rivoire"],
["GENLARIVOIR", "Saint-Martin-le-Vinoux, La Rivoire"],
["GENLASERRAL", "Venon, La Serralière"],
["GENLASURE", "Fontaine, La Sure"],
["GENLATUILE", "Vaulnaveys-le-Haut, La Tuilerie"],
["GENLAVALONE", "Vif, La Valonne"],
["GENLAVILLE", "Venon, La Ville"],
["GENLEBOURG", "Eybens, Le Bourg"],
["GENLEBRET", "Meylan, Le Brêt"],
["GENLECELLIE", "Seyssins, Clinique du Dauphiné"],
["GENLECHAMAN", "Gières, Le Chamandier"],
["GENLECHAPON", "Venon, Le Chapon"],
["GENLECHENIL", "Venon, Le Chenil"],
["GENLECHERES", "Meylan, Les Léchères"],
["GENLECOMB", "Seyssinet-Pariset, Les Combes"],
["GENLECRET", "Eybens, Le Crêt"],
["GENLECRETS", "Sarcenas, Le Crêt"],
["GENLEGATINE", "Saint-Martin-le-Vinoux, Gatinet"],
["GENLEGORGET", "La Tronche, Le Gorget"],
["GENLEGOUILL", "Le Sappey-en-Chartreuse, Le Gouillat"],
["GENLEGUA", "Sassenage, Le Gua"],
["GENLEGUAMAI", "Le Gua, Le Gua Mairie"],
["GENLEJAPIN", "Gières, Le Japin"],
["GENLEMARAIS", "Saint-Martin-d'Hères, Le Marais"],
["GENLEMASGAC", "Saint-Martin-le-Vinoux, Mas Caché"],
["GENLENCLOS", "Brié-et-Angonnes, L'Enclos"],
["GENLEONJOUH", "Grenoble, Léon Jouhaux"],
["GENLEPARL", "Seyssins, Le Parlement"],
["GENLEPERROU", "Venon, Le Perroud"],
["GENLEPLATR", "Jarrie, Le Plâtre"],
["GENLEPLATRE", "Vaulnaveys-le-Bas, Chemin des Cottes"],
["GENLEPRIOU", "Seyssins, Le Priou"],
["GENLEREFUGE", "Vif, Le Refuge"],
["GENLEREYNET", "Venon, Le Reynet"],
["GENLERIF", "Vif, Le Rif"],
["GENLERONZA", "La Tronche, Le Rozan"],
["GENLESALLAS", "Vizille, Les Allas"],
["GENLESBAINS", "Grenoble, Suzanne Noël - Les Bains"],
["GENLESCOMBE", "Saint-Martin-le-Vinoux, Les Combes"],
["GENLESCOTES", "Seyssins, Les Côtes"],
["GENLESESSAR", "Grenoble, Les Essarts"],
["GENLESFAURE", "Le Gua, Les Faures"],
["GENLESFAUVE", "Saint-Martin-le-Vinoux, Les Fauvettes"],
["GENLESFORGE", "Vizille, Les Forges"],
["GENLESILES", "Seyssinet-Pariset, Les Iles"],
["GENLESPIES", "Sassenage, Les Pies"],
["GENLETOILE", "Le Pont-de-Claix, L'Etoile"],
["GENLEVERNAY", "Miribel-Lanchâtre, Le Vernay"],
["GENLEVETIER", "Saint-Martin-le-Vinoux, Levetière"],
["GENLHERMITA", "Saint-Martin-le-Vinoux, L'Hermitage"],
["GENLMICHEL", "Grenoble, Louise Michel"],
["GENLOUISJOU", "Grenoble, Louis Jouvet"],
["GENLTE", "Vizille, Vizille Lycée"],
["GENLYCBACHA", "Meylan, Lycée du Grésivaudan - Bachais"],
["GENLYCGRESI", "Meylan, Lycée du Grésivaudan"],
["GENLYSROUGE", "Grenoble, Lys Rouge"],
["GENMADELEIN", "Grenoble, Madeleine"],
["GENMAICULTU", "Grenoble, MC2: Maison de la Culture"],
["GENMAINNATI", "Grenoble, Marché d'Intérêt National"],
["GENMAIRIECO", "Corenc, Mairie-Condamine"],
["GENMAIRIESM", "Saint-Martin-le-Vinoux, Hôtel de Ville"],
["GENMAISANCI", "Grenoble, Maison des Anciens"],
["GENMAISNEUV", "Eybens, Maisons Neuves"],
["GENMAISON", "Vaulnaveys-le-Bas, Maison Blanche"],
["GENMAISONCO", "Saint-Martin-d'Hères, Maison Communale"],
["GENMAISONNA", "Fontaine, Louis Maisonnat"],
["GENMALACHER", "Meylan, Malacher"],
["GENMALADIER", "Sassenage, Maladière"],
["GENMALHERBE", "Grenoble, Malherbe"],
["GENMALHIVER", "Claix, Malhivert"],
["GENMALISSOL", "Varces-Allières-et-Risset, Malissolles"],
["GENMALLIFAU", "Grenoble, Mallifaud"],
["GENMARAT", "Fontaine, Marat"],
["GENMARCEAU", "Grenoble, Marceau - Jardin des Vallons"],
["GENMARCHAND", "Vaulnaveys-le-Haut, Marchandises"],
["GENMARCSANG", "Seyssins, Marc Sangnier"],
["GENMARESIST", "Grenoble, Martyrs - Résistance"],
["GENMARIANNE", "Le Pont-de-Claix, Marianne"],
["GENMARIECUR", "Échirolles, Marie Curie"],
["GENMARITELL", "Bresson, La Maritelle"],
["GENMARRONNI", "Veurey-Voroize, Les Marronniers"],
["GENMASDESIL", "Seyssins, Mas des Iles"],
["GENMASGARNI", "Vif, Mas Garni"],
["GENMASSEGU", "Vif, Le Masségu"],
["GENMASSENET", "Grenoble, Massenet"],
["GENMAUPA", "Saint-Martin-d'Uriage, Maupas"],
["GENMAUPERTJ", "Jarrie, Maupertuis"],
["GENMAUPERTU", "Meylan, Maupertuis"],
["GENMAYENCIN", "Gières, Mayencin - Champ Roman"],
["GENMEINGET", "Saint-Paul-de-Varces, Le Meinget"],
["GENMETRA", "Brié-et-Angonnes, Les Métraux"],
["GENMEYLMAIR", "Meylan, Meylan Mairie"],
["GENMICHALLO", "La Tronche, Michallon"],
["GENMIRIBEL", "Miribel-Lanchâtre, Miribel"],
["GENMOLLARD", "Corenc, Rochasson"],
["GENMOLLARDP", "Sassenage, Mollard - Pichon"],
["GENMOLLARSA", "Le Sappey-en-Chartreuse, Les Jonquilles"],
["GENMONMOUSS", "Échirolles, Monmousseau"],
["GENMONTCHAV", "Montchaboud, Montchaboud Le Village"],
["GENMONTFLEU", "Corenc, Montfleury"],
["GENMONTLIVE", "Meylan, Montlivet"],
["GENMONTQUAI", "Quaix-en-Chartreuse, Mont-Quaix"],
["GENMONUMENT", "Corenc, Monument"],
["GENMORTES", "Domène, Les Mortes"],
["GENMOUCHERO", "Claix, Moucherotte"],
["GENMOUNIER", "Grenoble, Mounier"],
["GENMOUTONNE", "Saint-Égrève, Moutonnées"],
["GENMURET", "Saint-Égrève, Muret"],
["GENMURIERS", "Meylan, Les Mûriers"],
["GENMUSEEDAU", "Grenoble, Musée Dauphinois"],
["GENMUSGEOCH", "Échirolles, Musée Géo Charles"],
["GENMUSHEBER", "La Tronche, Musée Hébert"],
["GENMUTUALIT", "Grenoble, Mutualité"],
["GENNAMIERE", "Mont-Saint-Martin, Chemin de Namière"],
["GENNARBONNE", "Saint-Martin-le-Vinoux, Narbonne"],
["GENNAVIS", "Échirolles, Navis"],
["GENNERON", "Saint-Martin-le-Vinoux, Néron"],
["GENNEYRBELL", "Saint-Martin-d'Hères, Neyrpic - Belledonne"],
["GENNODAMLAC", "Varces-Allières-et-Risset, Notre-Dame de Lachal"],
["GENNORBSEGA", "Meylan, Norbert Ségard"],
["GENNOTREDAM", "Grenoble, Notre-Dame - Musée"],
["GENNOYARBAS", "Noyarey, Bascule"],
["GENNOYARSTJ", "Noyarey, Saint-Jean"],
["GENNOYVILLA", "Noyarey, Noyarey Village"],
["GENODYSSEE", "Eybens, Odyssée"],
["GENOISEAUX", "Corenc, Les Oiseaux"],
["GENORATOIRE", "Domène, L'Oratoire"],
["GENORIEL", "Varces-Allières-et-Risset, L'Oriel"],
["GENOVALIE", "Sassenage, L'Ovalie"],
["GENPABLONER", "Saint-Martin-d'Hères, Pablo Neruda"],
["GENPABLOPIC", "Échirolles, Collège Pablo Picasso"],
["GENPAJON", "Corenc, Charles Pajon"],
["GENPALAQUIT", "Sarcenas, Col de Palaquit"],
["GENPALJUSTI", "Grenoble, Palais de Justice - Gare"],
["GENPAMPRES", "Claix, Les Pampres"],
["GENPARCBICH", "Noyarey, Parc des Biches"],
["GENPARCS", "Sassenage, Les Parcs"],
["GENPARISE", "Seyssinet-Pariset, Pariset"],
["GENPASCAL", "La Tronche, Pascal"],
["GENPAULCOCA", "Grenoble, Paul Cocat"],
["GENPAULELUA", "Saint-Martin-d'Hères, Paul Eluard"],
["GENPAVILLON", "Varces-Allières-et-Risset, Pavillon"],
["GENPCLAUDEL", "Grenoble, Paul Claudel"],
["GENPEAGEDEV", "Vizille, Le Péage"],
["GENPEIFFEND", "Saint-Martin-d'Uriage, Les Peiffendes"],
["GENPELISIER", "Varces-Allières-et-Risset, Pélissière"],
["GENPELLOUTI", "Échirolles, Fernand Pelloutier"],
["GENPERCEVAL", "Seyssinet-Pariset, Percevalière"],
["GENPERIBROS", "Saint-Martin-d'Hères, Péri - Brossolette"],
["GENPERIERES", "Veurey-Voroize, Perrières"],
["GENPEROUSES", "Claix, Les Pérouses"],
["GENPERRIERE", "Gières, La Perrière"],
["GENPETIBRIO", "Vif, Le Petit Brion"],
["GENPFMITTER", "Seyssins, Parc François Mitterrand"],
["GENPHEROULT", "Échirolles, Paul Héroult"],
["GENPIEDGIER", "Gières, Pied de Gières"],
["GENPIERCOUR", "Saint-Martin-d'Hères, Pierre Courtade"],
["GENPIERRELO", "Saint-Martin-d'Hères, Pierre Loti"],
["GENPIERSEMA", "Saint-Martin-d'Hères, Pierre Sémard"],
["GENPINEA", "Saint-Égrève, La Pinéa - St Robert"],
["GENPISBUCLO", "Meylan, Piscine des Buclos"],
["GENPLACA", "Champagnier, Place du Laca"],
["GENPLACECYM", "Grenoble, Place Cymaise"],
["GENPLACEQUA", "Quaix-en-Chartreuse, Quaix en Chartreuse Place"],
["GENPLACESAP", "Le Sappey-en-Chartreuse, Le Sappey en Ch. Place"],
["GENPLACEVIL", "Seyssins, Seyssins Village"],
["GENPLACMARC", "Fontaine, Place du Marché Cachin"],
["GENPLAINE", "Vif, La Plaine"],
["GENPLAINEDS", "Gières, Plaine des Sports"],
["GENPLAINEFL", "Meylan, Plaine Fleurie"],
["GENPLALOUIS", "Meylan, Place de la Louisiane"],
["GENPLANF", "Proveysieux, Planfay Bas"],
["GENPLANFAY", "Proveysieux, Planfay Haut"],
["GENPLATANES", "Varces-Allières-et-Risset, Les Platanes"],
["GENPLGEANTS", "Grenoble, Les Géants"],
["GENPLIBERAT", "Sassenage, Place de la Libération"],
["GENPLREPUBL", "Gières, Place de la République"],
["GENPOLESUD", "Grenoble, Polesud - Alpexpo"],
["GENPOLOTTI", "Échirolles, Antoine Polotti"],
["GENPOMAR", "Proveysieux, Pomarey Bas"],
["GENPOMAREY", "Proveysieux, Pomarey"],
["GENPOMMERAI", "Varces-Allières-et-Risset, La Pommeraie"],
["GENPOMPIDOU", "Claix, Pompidou"],
["GENPONSARD", "Grenoble, Ponsard"],
["GENPONTCN", "Champ-sur-Drac, Pont de Champ"],
["GENPONTDEV", "Gières, Pont de Venon"],
["GENPONTGENE", "Vif, Le Pont de Genevrey"],
["GENPONTMAS", "Vizille, Le Pont du Mas"],
["GENPORTAILR", "Saint-Martin-d'Hères, Portail Rouge"],
["GENPORTGRES", "Saint-Martin-d'Hères, Porte du Grésivaudan"],
["GENPOSTE", "Claix, Poste"],
["GENPOTIE", "Saint-Martin-d'Hères, Potié"],
["GENPOULAT", "Saint-Paul-de-Varces, Le Poulat"],
["GENPRAPARIS", "Sassenage, Praparis Usine"],
["GENPRAPAROS", "Noyarey, Praparis - Les Roses"],
["GENPREAUCR", "Eybens, Pré au crêt"],
["GENPRECATLA", "Meylan, Pré Catlan"],
["GENPREDEAU", "Montbonnot-Saint-Martin, Pré de l'Eau"],
["GENPREDIEU", "Saint-Égrève, Fiancey - Prédieu"],
["GENPREFLEUR", "Sassenage, Pré Fleury"],
["GENPRELENFR", "Le Gua, Prélenfrey Eglise"],
["GENPREMILL", "Montbonnot-Saint-Martin, Pré Millet"],
["GENPREMOL", "Poisat, Prémol"],
["GENPRENOUVE", "Seyssins, Pré Nouvel"],
["GENPREORME", "Varces-Allières-et-Risset, Pré de l'Orme"],
["GENPRESQUIL", "Grenoble, Oxford"],
["GENPRIEURE", "Domène, Le Prieuré"],
["GENPRISME", "Seyssins, Le Prisme"],
["GENPROMOSOC", "Saint-Martin-d'Hères, Promotion Sociale"],
["GENPROVIDEN", "Corenc, Providence"],
["GENPTCHATEL", "Veurey-Voroize, Petit Châtelard"],
["GENPTCLXMAI", "Le Pont-de-Claix, Pont-de-Claix Mairie"],
["GENPTROUGE", "Claix, Pont Rouge"],
["GENPTTRONCH", "La Tronche, Petite Tronche"],
["GENPTVENCE", "Saint-Égrève, Pont de Vence"],
["GENPUIS", "Venon, Les Puis"],
["GENQUINZAIN", "Échirolles, Quinzaine"],
["GENRABOT", "Grenoble, Le Rabot"],
["GENRAFOUR", "Fontanil-Cornillon, Rafour"],
["GENRAMPE", "Échirolles, La Rampe - Centre-Ville"],
["GENRAYCHANA", "Grenoble, Raymond Chanas"],
["GENRENECASS", "Domène, René Cassin"],
["GENREPLAT", "Brié-et-Angonnes, Le Replat"],
["GENREPOSOIR", "Saint-Martin-le-Vinoux, Le Reposoir"],
["GENREVIREE", "Meylan, La Revirée"],
["GENREVIREES", "Meylan, Revirée - Sayettes"],
["GENRHINDANU", "Grenoble, Rosa Parks"],
["GENRIGAU", "Proveysieux, Garcinière"],
["GENRIPAILLE", "Saint-Martin-le-Vinoux, Ripaillère"],
["GENRISSET", "Varces-Allières-et-Risset, Risset"],
["GENRIVETS", "Murianette, Les Rivets"],
["GENRIVOIRE", "Sassenage, Rivoire de la Dame"],
["GENROBESPIE", "Poisat, Robespierre"],
["GENROCHEFOR", "Varces-Allières-et-Risset, Le Rochefort"],
["GENROCHEPLA", "Saint-Martin-d'Hères, Rocheplane"],
["GENROCHEPLE", "Saint-Égrève, Rochepleine"],
["GENROCHERES", "Saint-Égrève, Rocher d'Escalade"],
["GENROLLANDI", "Sassenage, La Rollandière"],
["GENROMANCHE", "Champ-sur-Drac, Espace Navarre"],
["GENRONDEAU", "Grenoble, Marielle Franco - Le Rondeau"],
["GENRONDEURO", "Varces-Allières-et-Risset, Rond-Point de l'Europe"],
["GENRONZY", "Claix, La Ronzy"],
["GENROSERAIE", "Gières, Roseraie"],
["GENROSES", "Claix, Les Roses"],
["GENROSSETS", "Le Gua, Les Rossets"],
["GENROUDIER", "Quaix-en-Chartreuse, Roudier"],
["GENROUSTEGR", "Quaix-en-Chartreuse, Route de Saint-Egrève"],
["GENROZATIER", "Varces-Allières-et-Risset, Rozatière"],
["GENRUEALPES", "Fontaine, Rue des Alpes"],
["GENRUEPASTE", "Fontaine, Rue Pasteur"],
["GENRUIRES", "Eybens, Les Ruires-Boétie"],
["GENRUISSET", "Noyarey, Le Ruisset"],
["GENSABLONS", "La Tronche, Sablons"],
["GENSACRISTI", "Vif, Rue de la Sacristie"],
["GENSAILLANT", "Le Gua, Les Saillants"],
["GENSAINTEYN", "Le Sappey-en-Chartreuse, Saint-Eynard"],
["GENSAINTMIC", "Claix, Saint-Michel"],
["GENSALENGRO", "Grenoble, Salengro"],
["GENSALLEZOL", "Champ-sur-Drac, Zola - Mairie"],
["GENSAMMARIN", "Saint-Égrève, San Marino - Barrage"],
["GENSARCENA", "Sarcenas, Sarcenas Le Village"],
["GENSARCROZ", "Sarcenas, Pont du Croz"],
["GENSAULES", "Eybens, Les Saules"],
["GENSAVOY", "Proveysieux, Savoyardière"],
["GENSEYHDV", "Seyssinet-Pariset, Seyssinet-Pariset Hôtel de Ville"],
["GENSEYSROND", "Seyssins, Seyssins Rondeau"],
["GENSEYSVILL", "Seyssinet-Pariset, Seyssins Village"],
["GENSEYVILLA", "Seyssins, Seyssins Village"],
["GENSIMIA", "Jarrie, Les Simianes"],
["GENSMHVILLA", "Saint-Martin-d'Hères, Saint-Martin-d'Hères Village"],
["GENSMVINOUX", "Saint-Martin-le-Vinoux, Place du Village"],
["GENSNETVILA", "Seyssinet-Pariset, Seyssinet Village"],
["GENSONNANT", "Gières, Le Sonnant"],
["GENSOUSFRET", "Quaix-en-Chartreuse, Sous La Frette"],
["GENSOUSPERO", "Venon, Sous-Perroud"],
["GENSOUVE", "Brié-et-Angonnes, Souveyron"],
["GENSOUVEVI", "Brié-et-Angonnes, Le Coin"],
["GENSPAULMAI", "Saint-Paul-de-Varces, Place"],
["GENSTADE", "Échirolles, Stade"],
["GENSTADEPER", "Champ-sur-Drac, Léo Lagrange"],
["GENSTADLESD", "Grenoble, Stade Lesdiguières"],
["GENSTALALLI", "Grenoble, Stalingrad-Alliés"],
["GENSTAUGUST", "Grenoble, Saint-Augustin"],
["GENSTBARTHE", "Le Gua, Saint-Barthélémy"],
["GENSTBRUNNC", "Grenoble, Saint-Bruno"],
["GENSTBRUNO", "Grenoble, Saint-Bruno"],
["GENSTEANGE", "Varces-Allières-et-Risset, Saint-Ange"],
["GENSTECLAIR", "Grenoble, Sainte-Claire - Les Halles"],
["GENSTEGVGAR", "Saint-Égrève, Saint Egrève Gare"],
["GENSTEND", "Varces-Allières-et-Risset, Stendhal"],
["GENSTEYNARD", "Fontaine, Saint-Eynard"],
["GENSTGCOMMI", "Saint-Georges-de-Commiers, St-G.-de-Commiers Gare"],
["GENSTGERMAI", "La Tronche, Saint-Germain"],
["GENSTJBOSCO", "Meylan, Saint-Jean Bosco"],
["GENSTLAUREN", "Grenoble, Saint-Laurent"],
["GENSTMARTIN", "Saint-Martin-d'Uriage, Route de Saint Martin"],
["GENSTMURY", "Meylan, Saint-Mury"],
["GENSTROCH", "Grenoble, Saint-Roch"],
["GENSTVICTOR", "Meylan, Saint-Victor"],
["GENSUDGALAX", "Échirolles, Sud Galaxie"],
["GENSURIEUX", "Échirolles, Surieux"],
["GENTAILLEES", "Saint-Martin-d'Hères, Les Taillées - Universités"],
["GENTAILLIS", "Claix, Les Taillis"],
["GENTAVER", "Brié-et-Angonnes, Tavernolles"],
["GENTEISSEIR", "Grenoble, Teisseire"],
["GENTELEBAS", "Grenoble, Téléphérique"],
["GENTERRATS", "Gières, Les Terrats"],
["GENTERRAY", "Meylan, Lionel Terray"],
["GENTHEVE", "Jarrie, Les Thévenets"],
["GENTRAVERS", "Vaulnaveys-le-Bas, Les Travers"],
["GENTREFFORI", "Sassenage, Trefforine"],
["GENTREILLE", "Meylan, La Treille"],
["GENTRONCHOP", "Grenoble, La Tronche Hôpital"],
["GENTUILERIE", "Seyssins, Tuilerie"],
["GENURIAGE", "Saint-Martin-d'Uriage, Uriage Gare"],
["GENURIOL", "Vif, Uriol"],
["GENUSINENOR", "Vif, L'Usine Nord"],
["GENVALALLIE", "Claix, Val d'Allières"],
["GENVALEYBEN", "Eybens, Val d'Eybens"],
["GENVALLCATA", "Grenoble, Vallier - Catane"],
["GENVALLIBE", "Grenoble, Vallier - Libération"],
["GENVALMY", "Grenoble, Flandrin - Valmy"],
["GENVARCESRE", "Varces-Allières-et-Risset, République"],
["GENVASSIEUX", "Échirolles, Vassieux"],
["GENVAULBAS", "Vaulnaveys-le-Bas, Vaulnaveys-Le-Bas Le Village"],
["GENVAULHAUT", "Vaulnaveys-le-Haut, Vaulnaveys-Le-Haut Le Village"],
["GENVENARIA", "Vizille, Vénaria"],
["GENVENCEECO", "Saint-Égrève, Vence EcoParc"],
["GENVENONMAI", "Venon, Venon Mairie"],
["GENVERCORS", "La Tronche, Vercors"],
["GENVERDERET", "Eybens, Le Verderet"],
["GENVERDUN", "Grenoble, Verdun - Préfecture"],
["GENVERLAINE", "Grenoble, Verlaine"],
["GENVERNES", "Domène, Les Vernes"],
["GENVERNET", "Jarrie, Le Vernet Croix"],
["GENVERT", "Claix, Vert Sapin"],
["GENVEUREYEG", "Veurey-Voroize, Eglise"],
["GENVEUREYMA", "Veurey-Voroize, Mairie"],
["GENVEUREYRI", "Veurey-Voroize, La Rive"],
["GENVEYRET", "Grenoble, Veyret"],
["GENVICTHUGO", "Grenoble, Victor Hugo"],
["GENVIEUXDON", "Sassenage, Vieux donjon"],
["GENVIFGARE", "Vif, Vif Gare"],
["GENVIFGEND", "Vif, Rivalta"],
["GENVIFMAIRI", "Vif, Vif Mairie"],
["GENVIGNATE", "Gières, Vignate"],
["GENVIGNES", "Bresson, Les Vignes"],
["GENVIGNY", "Grenoble, Vigny"],
["GENVILLAGE", "Échirolles, Le Village"],
["GENVILLOLYM", "Grenoble, Village Olympique"],
["GENVISANCOU", "Saint-Égrève, Visancourt"],
["GENVOHRIGEN", "Vizille, Parc Vöhringen"],
["GENXAVJOUVI", "Grenoble, Xavier Jouvin"],
["GENZASPEYRE", "Vif, Z.A. des Speyres"],
["GENZELLAMEL", "Saint-Martin-d'Hères, Zella Mehlis"],
["GENZILES", "Le Pont-de-Claix, ZI des Iles"],




["GEN12420", "Chamrousse, LE RECOIN VFD"],
["GEN13045", "Revel, REVEL ECOLES"],
["GEN13050", "Revel, LA FONTAINE"],
["GEN13052", "Revel, LA SARRAZINE"],
["GEN13054", "Domène, DOMENE MAIRIE"],
["GEN13056", "Domène, DOMENE LES ARNAUDS"],
["GEN13064", "Revel, REVEL LA BOURGEAT"],
["GEN13074", "Le Versoud, LA CHARRIERE"],
["GEN13076", "Le Versoud, ETAPES-MALVAISIN"],
["GEN13078", "Domène, LES VERNES"],
["GEN13082", "Domène, LE PRIEURE"],
["GEN13088", "Montbonnot-Saint-Martin, BAUDONNIERE"],
["GEN13093", "Saint-Jean-le-Vieux, ST JEAN LE VIEUX LA MONTA"],
["GEN13100", "Domène, RENE CASSIN"],
["GEN13108", "La Combe-de-Lancey, LE MAS JULIEN"],
["GEN13113", "Revel, LE GEYMOND"],
["GEN13116", "Saint-Jean-le-Vieux, LE RIF"],
["GEN13119", "Saint-Jean-le-Vieux, ST JEAN LE VIEUX LE MOLLARD"],
["GEN13121", "Revel, LES JACQUETS"],
["GEN13122", "Revel, CHARRIERES NEUVES"],
["GEN13125", "Revel, LES FAURES"],
["GEN13126", "Revel, REVEL LE MONT"],
["GEN13129", "Revel, LES ROUSSETS"],
["GEN13131", "Saint-Jean-le-Vieux, ST JEAN LE VIEUX EGLISE"],
["GEN13133", "Saint-Jean-le-Vieux, LE NAYSORD"],
["GEN13137", "Saint-Jean-le-Vieux, LE COUVAT"],
["GEN13140", "Saint-Jean-le-Vieux, L ISLE"],
["GEN13570", "Montbonnot-Saint-Martin, PRE MILLET"],
["GEN13586", "Montbonnot-Saint-Martin, INRIA"],
["GEN13594", "Saint-Ismier, ST ISMIER LA BATIE"],
["GEN13598", "Saint-Ismier, LES MILLETS"],
["GEN13604", "Saint-Ismier, LES VARCIAUX"],
["GEN13606", "Saint-Ismier, BOUFFIERE"],
["GEN13608", "Saint-Ismier, LE MANIVAL"],
["GEN13614", "Saint-Ismier, LE MEMORIAL"],
["GEN13616", "Saint-Ismier, GEYDAN GENISSIEUX"],
["GEN13618", "Saint-Ismier, CHEMIN DES BOUTS"],
["GEN13626", "Saint-Ismier, LOT. LABIS"],
["GEN13628", "Saint-Ismier, LE MOULIN"],
["GEN13633", "Saint-Ismier, COLLEGE DU GRESIVAUDAN - PARKING"],
["GEN13634", "Saint-Nazaire-les-Eymes, LES EYMES RD 1090"],
["GEN13636", "Saint-Nazaire-les-Eymes, LES RATZ"],
["GEN13638", "Saint-Nazaire-les-Eymes, LE PIAT"],
["GEN13642", "Le Versoud, COTE BELLE"],
["GEN13644", "Saint-Ismier, LE FANGEAT"],
["GEN13650", "Saint-Ismier, LES MARECHAUX"],
["GEN13652", "Saint-Nazaire-les-Eymes, ST NAZAIRE LES EYMES GARE"],
["GEN13658", "Saint-Nazaire-les-Eymes, LE LAVORS"],
["GEN13660", "Saint-Ismier, CHEMIN QUARTALLEES"],
["GEN13662", "Le Versoud, LA PLACE"],
["GEN13664", "Le Versoud, BELLE PLAINE"],
["GEN13668", "Saint-Ismier, ST ISMIER LES PLANTEES"],
["GEN13674", "Saint-Ismier, LYCEE HORTICOLE"],
["GEN13678", "Montbonnot-Saint-Martin, PRE DE L EAU"],
["GEN13682", "La Combe-de-Lancey, LA COMBE DE LANCEY LE VILLARD"],
["GEN13686", "La Combe-de-Lancey, LE PETIT CHATEAU"],
["GEN13688", "La Combe-de-Lancey, LE MAS LA RUE"],
["GEN13690", "La Combe-de-Lancey, LE MAS MONTACOL"],
["GEN13692", "Laval, LE BONNAT"],
["GEN13694", "Laval, LAVAL MAIRIE"],
["GEN13698", "La Combe-de-Lancey, LA COMBE DE LANCEY LE MONT"],
["GEN13700", "La Combe-de-Lancey, LES ECHARRAS"],
["GEN13702", "La Combe-de-Lancey, VILLARD D EN BAS"],
["GEN13704", "La Combe-de-Lancey, LA COMBE LA CHAPELLE"],
["GEN13706", "La Combe-de-Lancey, LE MAS VANNIER"],
["GEN13708", "Sainte-Agnès, ECOLE DE STE AGNES"],
["GEN13710", "Sainte-Agnès, LA VILLE"],
["GEN13712", "Saint-Mury-Monteymond, LE CHOLET"],
["GEN13714", "La Combe-de-Lancey, LE MAS LARY"],
["GEN13718", "Saint-Mury-Monteymond, CARREFOUR PRELONG"],
["GEN13720", "Saint-Mury-Monteymond, ST MURY CIMETIERE"],
["GEN13722", "Villard-Bonnot, LA MADONE"],
["GEN13724", "Villard-Bonnot, VORS"],
["GEN13726", "Villard-Bonnot, VILLARD BONNOT LA MAIRIE"],
["GEN13728", "Villard-Bonnot, LA POLOGNE"],
["GEN13730", "Villard-Bonnot, EGLISE - GENDARMERIE"],
["GEN13732", "Saint-Mury-Monteymond, L EGLISE"],
["GEN13734", "Sainte-Agnès, LA FAURE"],
["GEN13736", "Froges, BRIGNOUD PLACE"],
["GEN13738", "Villard-Bonnot, LE SABOT"],
["GEN13740", "Sainte-Agnès, LE MAS N° 2"],
["GEN13742", "Sainte-Agnès, STE AGNES LE MOLLARD"],
["GEN13744", "Sainte-Agnès, MAISON D ARGOUD AU RIF"],
["GEN13746", "Villard-Bonnot, LANCEY"],
["GEN13748", "Saint-Mury-Monteymond, LA PALLUD MATERNELLE"],
["GEN13753", "Villard-Bonnot, LYCEE M. REYNOARD - PARKING"],
["GEN13754", "Villard-Bonnot, CITE DES ROSES"],
["GEN13756", "Sainte-Agnès, STE AGNES LA BOURGEAT"],
["GEN13758", "Sainte-Agnès, LE FAY"],
["GEN13762", "Sainte-Agnès, STE AGNES LA GORGE"],
["GEN13764", "Le Versoud, CITE NOUVELLE"],
["GEN13766", "Le Versoud, PONT DE PRUNEY"],
["GEN13768", "Sainte-Agnès, LES GRANDS CHAMPS"],
["GEN13770", "Villard-Bonnot, LANCEY GARE"],
["GEN13772", "Saint-Mury-Monteymond, LE BANC"],
["GEN13774", "Villard-Bonnot, LYCEE RD.523"],
["GEN13776", "Saint-Mury-Monteymond, LE MAS VIEUX"],
["GEN13778", "Saint-Mury-Monteymond, LES COCHARDS"],
["GEN13780", "Villard-Bonnot, COLLEGE BELLEDONNE"],
["GEN13782", "Villard-Bonnot, PAPETERIES"],
["GEN13786", "Laval, LA BOUTIERE"],
["GEN13788", "Laval, PRABERT"],
["GEN13790", "Laval, LAVAL LE MOLLARD"],
["GEN13792", "Laval, LE FUZIER"],
["GEN13794", "Les Adrets, PRAPOUTEL PATTE D OIE"],
["GEN13796", "Laval, LE PLANEYSSARD ECOLE"],
["GEN13798", "Les Adrets, PRAPOUTEL GENDARMERIE"],
["GEN13800", "Laval, LE CARNIVAL"],
["GEN13802", "Sainte-Agnès, LE FAY N°2"],
["GEN13804", "Les Adrets, LES GENIEVRES"],
["GEN13806", "Laval, VAUGELAS BAS"],
["GEN13808", "Sainte-Agnès, LA PERRIERE"],
["GEN13810", "Sainte-Agnès, EPINGLE LA PERRIERE"],
["GEN14188", "Crolles, LA CROIX DES AYES"],
["GEN14192", "Saint-Pancrasse, ST PANCRASSE LA MAIRIE"],
["GEN14194", "Bernin, CROIX DES VARVOUX"],
["GEN14196", "Bernin, BERNIN P.T.T."],
["GEN14198", "Bernin, VARVOUX LE BAS"],
["GEN14204", "Bernin, LES VARVOUX"],
["GEN14211", "Saint-Hilaire, LES MARGAINS"],
["GEN14212", "Bernin, LES REVOLEYS"],
["GEN14218", "Crolles, ST MICROELECTRONICS"],
["GEN14222", "Froges, ECOLE ELEMENTAIRE GUYNEMER"],
["GEN14224", "Froges, LE BOCCARD"],
["GEN14226", "Froges, PRE DU CHENE"],
["GEN14228", "Le Champ-près-Froges, LOT. LA TOUR"],
["GEN14234", "Froges, COQUILLARD"],
["GEN14236", "Le Champ-près-Froges, CHAMP PRES FROGES - LE MOLLARD"],
["GEN14250", "Crolles, RAFOUR CROIZAT"],
["GEN14253", "Froges, LANGENET"],
["GEN14254", "Le Champ-près-Froges, LE BAS"],
["GEN14256", "Le Champ-près-Froges, CHAMPALUD"],
["GEN14262", "Crolles, POMPIERS"],
["GEN14264", "Froges, CITE JARDINS"],
["GEN14269", "Froges, LES JAURES"],
["GEN14271", "Froges, LOT BALC. BELLEDONNE"],
["GEN14273", "Froges, ALLEE DES THUYAS"],
["GEN14274", "Froges, LE PLANET"],
["GEN14276", "Froges, LES BOIS"],
["GEN14279", "Froges, LE MAZARETIER"],
["GEN14280", "Froges, LES VIGNES DE PICHAT"],
["GEN14282", "Saint-Hilaire, PRE BENOIT"],
["GEN14284", "Saint-Hilaire, LES GANDINS"],
["GEN14295", "Froges, MAS PELIOUD"],
["GEN14297", "Froges, LES AYETTES"],
["GEN14300", "Les Adrets, L ENVERS"],
["GEN14302", "Les Adrets, ECOLE LES ADRETS"],
["GEN14304", "Les Adrets, ROUTE VIEUX MANEGE"],
["GEN14306", "Les Adrets, LES ALPETS"],
["GEN14312", "Les Adrets, VILLARD CHATEAU"],
["GEN14314", "Les Adrets, POUTAZ BAS"],
["GEN14316", "Les Adrets, LES AVONS"],
["GEN14318", "Les Adrets, PRES COMMUNAUX N°1"],
["GEN14320", "Les Adrets, PRES COMMUNAUX N°2"],
["GEN14322", "Les Adrets, LES FOURNELLES"],
["GEN14325", "Les Adrets, LA PITROUSE"],
["GEN14328", "Hurtières, HURTIERES LE HAUT"],
["GEN14330", "Hurtières, HURTIERES MAIRIE"],
["GEN14332", "Les Adrets, VILLARD BERNARD"],
["GEN14334", "Le Champ-près-Froges, CHAMP LE HAUT MAIRIE"],
["GEN14338", "Les Adrets, LES COMPTES"],
["GEN14340", "Froges, ROUARE"],
["GEN14344", "Hurtières, HURTIERES PLACE"],
["GEN14346", "Les Adrets, LE LANAT"],
["GEN14348", "Theys, THEYS ECOLES"],
["GEN14351", "Theys, LES AYES"],
["GEN14354", "Tencin, PRE SEC"],
["GEN14357", "Theys, ROUTE DES GAUTHIERS"],
["GEN14359", "Theys, LES GLAPIGNEUX"],
["GEN14360", "Theys, LES COMBES D EN BAS"],
["GEN14363", "Theys, LE BOURGUIGNON"],
["GEN14366", "Theys, LES BERTS"],
["GEN14369", "Theys, LES VALLINS"],
["GEN14371", "Theys, PIERRE HERSE"],
["GEN14373", "Theys, LES COMBES D EN HAUT"],
["GEN14374", "La Pierre, LA PIERRE - CARR. RD 523"],
["GEN14377", "Theys, LOUTRE"],
["GEN14379", "Theys, LA TOUR"],
["GEN14380", "Theys, LA MAISON BLANCHE"],
["GEN14382", "Les Adrets, LES FOURNACHES"],
["GEN14385", "Theys, THEYS LA ROCHE"],
["GEN14386", "Theys, GORGE D OR"],
["GEN14388", "Theys, LES ESSARTS"],
["GEN14390", "Les Adrets, LES BLETTIERES"],
["GEN14395", "Theys, GLAPIGNEUX DESSOUS"],
["GEN14397", "Les Adrets, LE PRE"],
["GEN14400", "La Ferrière, LA MARTINETTE"],
["GEN14402", "La Ferrière, FOND DE FRANCE"],
["GEN14405", "La Ferrière, LE PLEYNET"],
["GEN14406", "La Ferrière, CAMOREL"],
["GEN14408", "La Ferrière, LA FERRIERE LA CHAPELLE"],
["GEN14410", "La Ferrière, LES MILLETS C.V.O."],
["GEN14978", "La Terrasse, INSTITUT"],
["GEN14980", "Saint-Bernard, LES VIROILLES"],
["GEN14984", "Saint-Bernard, HAMEAU ST MICHEL"],
["GEN14986", "Saint-Bernard, LE PRAYER"],
["GEN14988", "Saint-Bernard, LE TERRAIL"],
["GEN14990", "Saint-Bernard, LE COMBET"],
["GEN14994", "Saint-Bernard, ST BERNARD DU TOUVET LA BATIE"],
["GEN14996", "Saint-Bernard, LES PELLOUX"],
["GEN14998", "Saint-Hilaire, LES CHATAINS"],
["GEN15000", "Saint-Hilaire, LA CROIX DES EYRAUDS"],
["GEN15008", "Saint-Bernard, LA DIAT"],
["GEN15010", "Saint-Hilaire, MAT. LES GANDINS"],
["GEN15012", "Saint-Hilaire, LES VIALS"],
["GEN15014", "Saint-Bernard, LES GUILLOTS"],
["GEN15016", "Saint-Hilaire, ECOLE DES GAUDES"],
["GEN15018", "Saint-Hilaire, LES MASSARDS"],
["GEN15022", "Le Touvet, LA FRETTE"],
["GEN15026", "La Terrasse, LACHAT"],
["GEN15029", "La Terrasse, LE BURLET"],
["GEN15031", "Le Touvet, MONTABON"],
["GEN15032", "Goncelin, GONCELIN GARE"],
["GEN15035", "Tencin, MONTGALMAND"],
["GEN15036", "Le Touvet, LA CONCHE"],
["GEN15038", "Goncelin, VILLARD BOZON"],
["GEN15042", "Theys, LE CARRET"],
["GEN15044", "Tencin, GRANDES TERRES"],
["GEN15046", "Theys, LE GRE"],
["GEN15050", "Tencin, LE CLOS DU CEDRE"],
["GEN15053", "Goncelin, COLLEGE ICARE"],
["GEN15054", "Goncelin, COLLEGE RD.523"],
["GEN15056", "Theys, LA COCHE"],
["GEN15058", "Crêts en Belledonne, LA CASSEY"],
["GEN15060", "Theys, LES VINCENTS"],
["GEN15064", "Crêts en Belledonne, LE LEVET"],
["GEN15066", "Crêts en Belledonne, LE VOLEY"],
["GEN15068", "Crêts en Belledonne, LES AMICONS"],
["GEN15070", "La Ferrière, LE CURTILLARD"],
["GEN15072", "La Ferrière, VILLAGE-ECOLES"],
["GEN15074", "La Ferrière, LE PETIT THIERVOZ"],
["GEN15076", "La Ferrière, LE GRAND THIERVOZ"],
["GEN15080", "Pinsot, LA PIAT"],
["GEN1516", "Allevard, LE DAVID"],
["GEN1517", "Allevard, LE COLLET D ALLEVARD"],
["GEN1534", "Le Cheylas, LE MERCIER RD523"],
["GEN15702", "Sainte-Marie-du-Mont, LA CHAPELLE"],
["GEN15704", "Saint-Bernard, COL DE MARCIEU"],
["GEN15706", "Sainte-Marie-du-Mont, LE VILLARD"],
["GEN15710", "Sainte-Marie-du-Mont, LA VIEILLE EGLISE"],
["GEN15712", "Saint-Bernard, LOTISSEMENT MARCIEU"],
["GEN15716", "Le Cheylas, LES MEYANNES"],
["GEN15718", "Le Cheylas, LE CHEYLAS - LA MAIRIE"],
["GEN15722", "Le Cheylas, LE CHEYLAS GARE  D.523"],
["GEN15724", "Le Cheylas, LE CHEYLAS LE MERCIER"],
["GEN15726", "Le Cheylas, LE ROMPAY"],
["GEN15728", "La FlachÃ¨re, LA FLACHERE MAIRIE"],
["GEN15732", "Crêts en Belledonne, BEAUREGARD"],
["GEN15734", "Sainte-Marie-d'Alloix, STE MARIE D ALLOIX LE VILLAGE"],
["GEN15736", "La FlachÃ¨re, LA FLACHERE ECOLE"],
["GEN15741", "Saint-Vincent-de-Mercuze, CAVE COOPERATIVE"],
["GEN15742", "Le Touvet, LA CIME"],
["GEN15744", "Le Touvet, LE SAINT JEAN"],
["GEN15748", "Le Touvet, COLLEGE LA PIERRE  AIGUILLE"],
["GEN15750", "Le Touvet, LE TOUVET GARE"],
["GEN15752", "Saint-Vincent-de-Mercuze, ST VINCENT MERCUZE LA PISCINE"],
["GEN15755", "Crêts en Belledonne, LE TRAIT"],
["GEN15756", "Crêts en Belledonne, LE CHAPELAT"],
["GEN15758", "Crêts en Belledonne, MAILLES"],
["GEN15762", "Saint-Vincent-de-Mercuze, ST VINCENT DE MERCUZE MAIRIE"],
["GEN15764", "Saint-Vincent-de-Mercuze, LE MONTALIEU"],
["GEN15766", "Le Cheylas, LES BLEUETS"],
["GEN15769", "Saint-Vincent-de-Mercuze, LA FUMAS"],
["GEN15770", "Saint-Vincent-de-Mercuze, ST VINCENT LA BRANCHY"],
["GEN15774", "Saint-Vincent-de-Mercuze, GS DOUDART DE LAGREE"],
["GEN15776", "Saint-Vincent-de-Mercuze, LOT. DE LA BARDE"],
["GEN15778", "Le Cheylas, LE CHEYLAS LE VILLARD"],
["GEN15780", "Le Touvet, TOUVET MATERNELLE"],
["GEN15782", "Saint-Vincent-de-Mercuze, RUE HAUSSEPIED"],
["GEN15784", "Le Cheylas, LE TROUILLET"],
["GEN15791", "Allevard, LES MORETS"],
["GEN15794", "Allevard, LE  DAVID"],
["GEN15804", "Allevard, HAMEAU MONTOUVRARD"],
["GEN15806", "Crêts en Belledonne, ST PIERRE ECOLES"],
["GEN15808", "Crêts en Belledonne, LE CATUS"],
["GEN15812", "Crêts en Belledonne, SAILLES LE BAS"],
["GEN15814", "Crêts en Belledonne, LE GUILLON"],
["GEN15816", "Crêts en Belledonne, LE RIGARD"],
["GEN15820", "Crêts en Belledonne, SAILLES LE HAUT"],
["GEN15822", "Crêts en Belledonne, MONTGOUTOUX"],
["GEN15824", "Crêts en Belledonne, LE CHABOUD"],
["GEN15826", "Crêts en Belledonne, GORGE NOIRE"],
["GEN15828", "Crêts en Belledonne, CRETS EN BELLEDONNE LE VILLAGE"],
["GEN15830", "Crêts en Belledonne, LE BEROUD"],
["GEN15832", "Crêts en Belledonne, LE CARIGNON"],
["GEN15834", "Crêts en Belledonne, LE FEYJOUX"],
["GEN15836", "Crêts en Belledonne, LES GRANGES"],
["GEN15842", "Crêts en Belledonne, LES COTTERIAUX"],
["GEN15844", "Le Cheylas, L ABBAYE"],
["GEN15846", "Pinsot, PINSOT LE VILLAGE"],
["GEN15850", "Pinsot, CHINFERT"],
["GEN15852", "Pinsot, HOT PIC BELLE ETOILE"],
["GEN16340", "Sainte-Marie-du-Mont, LES PRES  MAIRIE"],
["GEN16345", "Barraux, CIMETIERE"],
["GEN16347", "Barraux, HAMEAU LA CUILLER"],
["GEN16348", "Barraux, LA CORVA"],
["GEN16350", "Barraux, LE RESERVOIR"],
["GEN16352", "La Buissière, LA BERARDE"],
["GEN16354", "Barraux, LE BOISSIEU PONT"],
["GEN16357", "La Buissière, LA BUISSIERE LES GRANGES"],
["GEN16358", "La Buissière, LA BUISSIERE ECOLE"],
["GEN16360", "Barraux, BARRAUX MATERNELLE"],
["GEN16361", "Pontcharra, LYCEE P. DU TERRAIL - BREDA"],
["GEN16362", "La FlachÃ¨re, LE BOISSIEU LOT"],
["GEN16364", "Sainte-Marie-du-Mont, HAMEAU DE ST GEORGES"],
["GEN16367", "Barraux, BARRAUX EC.PRIMAIRE"],
["GEN16368", "Barraux, LE PUITS"],
["GEN16372", "Barraux, LE FAYET"],
["GEN16374", "Barraux, BARRAUX LOT. BEAUREG"],
["GEN16377", "Pontcharra, JAVEYDAN"],
["GEN16378", "Pontcharra, MALBOURGET"],
["GEN16380", "Chapareillan, ST MARCEL D EN HAUT"],
["GEN16382", "Pontcharra, COLLEGE MARCEL CHENE"],
["GEN16384", "Pontcharra, VILLARD DIDIER"],
["GEN16386", "Pontcharra, LYCEE P. DU TERRAIL"],
["GEN16388", "Barraux, BARRAUX LE VILLAGE"],
["GEN16390", "Pontcharra, PONTCHARRA GARE"],
["GEN16396", "Pontcharra, VILLARD NOIR"],
["GEN16398", "La FlachÃ¨re, LA FLACHERE GARE"],
["GEN16404", "La Buissière, LA MALADIERE"],
["GEN16410", "Allevard, PANORAMIC"],
["GEN16412", "Allevard, LE CLOSY"],
["GEN16414", "Pontcharra, PONTCHARRA LA MAIRIE"],
["GEN16419", "Pontcharra, CHALLEYS"],
["GEN16421", "Pontcharra, PAPILLARD"],
["GEN16423", "Pontcharra, LE MARAIS"],
["GEN16425", "Pontcharra, MONTAUCHER"],
["GEN16426", "Pontcharra, VILLARD NOIR LES PLANTEES"],
["GEN16428", "Pontcharra, AVENUE DU GRANIER"],
["GEN16431", "Pontcharra, LE PAPET"],
["GEN16436", "Saint-Maximin, ST MAXIMIN LA MAIRIE"],
["GEN16444", "La Chapelle-du-Bard, BEAUVOIR"],
["GEN16446", "Allevard, LA RATZ"],
["GEN16448", "Allevard, LE COLOMBIER"],
["GEN16450", "La Chapelle-du-Bard, LA CHAPELLE LA GORGE"],
["GEN16454", "La Chapelle-du-Bard, LA CHAPELLE ECOLE"],
["GEN16456", "La Chapelle-du-Bard, MONTGAREN"],
["GEN16458", "Le Moutaret, LE MOUTARET LE VILLAGE"],
["GEN16460", "Le Moutaret, FREYDON"],
["GEN16462", "Le Moutaret, LES MASURES"],
["GEN16464", "La Chapelle-du-Bard, LE BUISSON"],
["GEN16994", "Chapareillan, EC PRIVEE BELLECOUR"],
["GEN16998", "Chapareillan, CHAPAREILLAN GARE"],
["GEN17000", "Chapareillan, LES ATRUS"],
["GEN17003", "Chapareillan, COTAGNIERS"],
["GEN17004", "Chapareillan, LES GIROUDS"],
["GEN17006", "Chapareillan, LA PALUD"],
["GEN17008", "Chapareillan, L ETRAZ"],
["GEN17010", "Chapareillan, CHAPAREILLAN MAIRIE"],
["GEN17012", "Chapareillan, ST MARCEL D EN BAS"],
["GEN17014", "Chapareillan, BELLECOMBETTE"],
["GEN17017", "Chapareillan, LA MEUNIERE"],
["GEN17019", "Chapareillan, CHAPAREILLAN ECOLE"],
["GEN17020", "Chapareillan, BELLECOMBE"],
["GEN17023", "Chapareillan, LES GAILLONS"],
["GEN20030", "Saint-Bernard, ST BERNARD EGLISE"],
["GEN20055", "Saint-Ismier, LE RIVET"],
["GEN20088", "Meylan, NORBERT SEGARD"],
["GEN20090", "Meylan, BUSSEROLLES"],
["GEN20194", "La Chapelle-du-Bard, PLAN POUCET"],
["GEN20211", "Pontcharra, RESIDENCES BAYARD"],
["GEN20215", "Pontcharra, LYCEE AV DE LA GARE"],
["GEN20217", "La Buissière, CHATEAU"],
["GEN20223", "Allevard, COLLEGE FLAVIUS VAUSSENAT"],
["GEN20230", "Saint-Nazaire-les-Eymes, ST NAZAIRE LES EYMES MAIRIE"],
["GEN20231", "Saint-Nazaire-les-Eymes, TRANSFORMATEUR"],
["GEN20257", "Le Cheylas, LES CHABERTS"],
["GEN20261", "Laval, LA TAILLAT"],
["GEN20264", "Laval, LE CARNIVAL LANCELOT"],
["GEN20287", "La Chapelle-du-Bard, REVIT"],
["GEN20289", "La Chapelle-du-Bard, PONT DU BENS"],
["GEN20290", "Le Touvet, LE TOUVET GENDARMERIE"],
["GEN20294", "Les Adrets, LES AVONS 2"],
["GEN20295", "Crêts en Belledonne, PLANCHAMPS"],
["GEN20298", "Allevard, LE GLAPIGNEUX"],
["GEN20300", "Allevard, ALLEVARD LE MOLLARD"],
["GEN20302", "Allevard, LA TOUR DU TREUIL"],
["GEN20316", "La Buissière, PATTE D OIE"],
["GEN20319", "Pontcharra, ECOLE CESAR TERRIER"],
["GEN20322", "Le Cheylas, LES VIGNASSES"],
["GEN20338", "Pontcharra, LA TREILLE"],
["GEN20358", "Saint-Ismier, LE CLOS DU MARS"],
["GEN30007", "Chamrousse, LE RECOIN OT"],
["GEN30027", "Pontcharra, MEDIATHEQUE"],
["GEN30028", "Pontcharra, VILLAGE D ENTREPRISES"],
["GEN30029", "Pontcharra, PONTCHARRA PISCINE"],
["GEN30033", "Crolles, TEISSEIRE"],
["GEN30041", "Le Cheylas, LE CHEYLAS USINES"],
["GEN30044", "Le Cheylas, LE CHEYLAS ECOLES"],
["GEN30045", "Saint-Martin-d'Uriage, CHENEVARIE"],
["GEN30046", "Saint-Martin-d'Uriage, LA PEREREE"],
["GEN30047", "Saint-Martin-d'Uriage, CORPS D URIAGE"],
["GEN30049", "Saint-Martin-d'Uriage, IZARDS PATTE D'OIE"],
["GEN30051", "Saint-Martin-d'Uriage, LE PINET D URIAGE"],
["GEN30052", "Saint-Martin-d'Uriage, CARREFOUR DU REPLAT"],
["GEN30055", "Saint-Martin-d'Uriage, HAUTES VUES"],
["GEN30056", "Saint-Martin-d'Uriage, ST NIZIER D URIAGE"],
["GEN30057", "Gières, GIERES GARE"],
["GEN30067", "Montbonnot-Saint-Martin, MONTBONNOT LA PISCINE"],
["GEN30069", "Allevard, BESSEY"],
["GEN30071", "Allevard, GUILLET"],
["GEN30073", "Villard-Bonnot, GRANDE ILE"],
["GEN30076", "Montbonnot-Saint-Martin, CH DE LA CROIX VERTE"],
["GEN30077", "Montbonnot-Saint-Martin, ECOLE DES CHAVANNES"],
["GEN30086", "Allevard, MUSEE JADIS"],
["GEN30089", "Allevard, LES PANISSIERES"],
["GEN30102", "Saint-Maximin, ST MAXIMIN LA COMBE"],
["GEN30105", "Saint-Maximin, AVALLON"],
["GEN30108", "Saint-Maximin, LES BRUNS"],
["GEN30111", "Saint-Maximin, RIPPELETS"],
["GEN30114", "Saint-Maximin, BRETONNIERES"],
["GEN30117", "Allevard, LES AMOUREUX"],
["GEN30120", "Allevard, AVENUE DE SAVOIE"],
["GEN30421", "La Combe-de-Lancey, LA SCIERIE"],
["GEN4001", "Chapareillan, RUE DES NOYERS"],
["GEN40053", "Lumbin, ESAT"],
["GEN5000", "Chapareillan, ALLIBERT TREKKING"],
["GEN5013", "La Chapelle-du-Bard, LE ROZAT"],



["S0543", "Apprieu, APPRIEU LE RIVIER ECOLE"],
["S0022", "Bilieu, BILIEU BARDONNET"],
["S0023", "Bilieu, BILIEU CHANTARET"],
["S0019", "Bilieu, BILIEU LES MAURES"],
["S0021", "Bilieu, BILIEU PETIT BILIEU"],
["S0020", "Bilieu, BILIEU ROUTE DE CHARAVINES"],
["S0018", "Bilieu, BILIEU VILLAGE"],
["S0031", "Charancieu, CHARANCIEU CENTRE"],
["S0573", "Charancieu, CHARANCIEU ZA CHARANCIEU"],
["S0577", "Charavines, CHARAVINES BERNARDIERE"],
["S0038", "Charavines, CHARAVINES FORGES"],
["S0042", "Charavines, CHARAVINES GARE"],
["S0037", "Charavines, CHARAVINES GUILLERMET"],
["S0034", "Charavines, CHARAVINES JACQUIN"],
["S0035", "Charavines, CHARAVINES MONTFOLLET"],
["S0044", "Charavines, CHARAVINES OFFICE DE TOURISME"],
["S0043", "Charavines, CHARAVINES PAPETERIE"],
["S0039", "Charavines, CHARAVINES PLACE DU MARCHE"],
["S0040", "Charavines, CHARAVINES VIRAGE JANIN"],
["S0047", "Charnècles, CHARNECLES 6 CHEMINS"],
["S0053", "Charnècles, CHARNECLES LES RIVOIRES"],
["S0055", "Charnècles, CHARNECLES LEZARDIERES PT"],
["S0050", "Charnècles, CHARNECLES MAIRIE"],
["S0049", "Charnècles, CHARNECLES PLACE"],
["S0048", "Charnècles, CHARNECLES PONT DE BOIS VERT"],
["S0060", "Chirens, CHIRENS CLERMONT"],
["S0579", "Chirens, CHIRENS COLLEGE"],
["S0062", "Chirens, CHIRENS GARANGERE"],
["S0063", "Chirens, CHIRENS GUILLETIERE"],
["S0059", "Chirens, CHIRENS L ARSENAL"],
["S0057", "Chirens, CHIRENS LE FAGOT"],
["S0058", "Chirens, CHIRENS LE GAYET"],
["S0061", "Chirens, CHIRENS TOUR CLERMONT"],
["S0056", "Chirens, CHIRENS VILLAGE"],
["S0082", "Coublevie, COUBLEVIE BARRIOZ"],
["S0068", "Coublevie, COUBLEVIE BARTHELON"],
["S0097", "Coublevie, COUBLEVIE BEAUREGARD"],
["S0585", "Coublevie, COUBLEVIE BOUVIER DIVAT"],
["S0086", "Coublevie, COUBLEVIE CH DE LA GRANDE SURE"],
["S0071", "Coublevie, COUBLEVIE COLLEGE PLAN MENU"],
["S0065", "Coublevie, COUBLEVIE CROIX BAYARD"],
["S0077", "Coublevie, COUBLEVIE ECOLE DU BERARD"],
["S0080", "Coublevie, COUBLEVIE HOPITAL"],
["S0100", "Coublevie, COUBLEVIE LAFAILLE"],
["S0094", "Coublevie, COUBLEVIE LAVOIR DU NEYROUD"],
["S0067", "Coublevie, COUBLEVIE LE BRET"],
["S0578", "Coublevie, COUBLEVIE LES NOYERS"],
["S0079", "Coublevie, COUBLEVIE MAIRIE"],
["S0093", "Coublevie, COUBLEVIE MAISON DE RETRAITE"],
["S0081", "Coublevie, COUBLEVIE MFR DALMASSIERE"],
["S0069", "Coublevie, COUBLEVIE MOLLARD"],
["S0095", "Coublevie, COUBLEVIE NEYROUD"],
["S0092", "Coublevie, COUBLEVIE ORGEOISE"],
["S0101", "Coublevie, COUBLEVIE PARKING PLAN MENU"],
["S0070", "Coublevie, COUBLEVIE PILET"],
["S0066", "Coublevie, COUBLEVIE PL DU 19 MARS 1962"],
["S0064", "Coublevie, COUBLEVIE PLACE E BROCHIER"],
["S0085", "Coublevie, COUBLEVIE ROUTE DE LA BUISSE"],
["S0078", "Coublevie, COUBLEVIE ROUTE DE ST JEAN"],
["S0076", "Coublevie, COUBLEVIE ROUTE DES GORGES"],
["S0073", "Coublevie, COUBLEVIE RUE DU 11 NOV 1918"],
["S0074", "Coublevie, COUBLEVIE TIVOLIERE"],
["S0072", "Coublevie, COUBLEVIE ZA DU ROULET"],
["S0544", "Fontanil-Cornillon, FONTANIL CORNIL CROIX DE ROCHETTE"],
["S0545", "Fontanil-Cornillon, FONTANIL CORNIL LEP F. DOLTO"],
["S0589", "Fontanil-Cornillon, FONTANIL CORNIL PALLUEL"],
["S0001", "La Bâtie-Divisin, BATIE DIVISIN MAIRIE"],
["S0571", "La Buisse, LA BUISSE AFIPH"],
["S0025", "La Buisse, LA BUISSE CHEMIN DU GAY"],
["S0026", "La Buisse, LA BUISSE ECOLES"],
["S0027", "La Buisse, LA BUISSE GRAND CHAMP"],
["S0029", "La Buisse, LA BUISSE LE GAY GIRATOIRE"],
["S0028", "La Buisse, LA BUISSE LE PANSU"],
["S0024", "La Buisse, LA BUISSE PLACE"],
["S0580", "La Buisse, LA BUISSE RESSOURCERIE"],
["S0565", "La Buisse, ST J.DE MOIRANS ROSSIGNOL"],
["S0187", "La Murette, LA MURETTE LA COURATIERE"],
["S0186", "La Murette, LA MURETTE LE PAYSAN"],
["S0185", "La Murette, LA MURETTE VILLAGE"],
["S0197", "Le Pin, LE PIN BREZIN BOURG"],
["S0200", "Le Pin, LE PIN CARREFOUR BREZIN"],
["S0199", "Le Pin, LE PIN CENTRE EQUESTRE"],
["S0198", "Le Pin, LE PIN LA CUAZ"],
["S0201", "Le Pin, LE PIN LES ALLEX"],
["S0195", "Le Pin, LE PIN PL SAINT CHRISTOPHE"],
["S0196", "Le Pin, LE PIN VERS ARS"],
["S0104", "Massieu, MASSIEU COTE D AINAN"],
["S0103", "Massieu, MASSIEU LA SARRA"],
["S0102", "Massieu, MASSIEU VILLAGE"],
["S0109", "Merlas, MERLAS BOUTIERE"],
["S0108", "Merlas, MERLAS CHAPELLE DE MERLAS"],
["S0114", "Merlas, MERLAS FAGOTIERE"],
["S0075", "Merlas, MERLAS LAYAT BAS"],
["S0113", "Merlas, MERLAS LE BURLET"],
["S0588", "Merlas, MERLAS LES ECHELLES"],
["S0117", "Merlas, MERLAS LES GORGES"],
["S0116", "Merlas, MERLAS MERLIETTE"],
["S0106", "Merlas, MERLAS NOUVELIERE"],
["S0107", "Merlas, MERLAS PICOUDIERE"],
["S0112", "Merlas, MERLAS PIVOTIERE"],
["S0110", "Merlas, MERLAS REYSSABOT"],
["S0111", "Merlas, MERLAS ST SIXTE"],
["S0105", "Merlas, MERLAS VILLAGE"],
["S0550", "Miribel-les-Échelles, MIR.lesECHELLES EGLISE"],
["S0547", "Miribel-les-Échelles, MIR.lesECHELLES LES EMPTAZ"],
["S0546", "Miribel-les-Échelles, MIR.lesECHELLES ST ROCH"],
["S0548", "Miribel-les-Échelles, ST AUPRE LE VERNEY"],
["S0139", "Moirans, MOIRANS BOIS DU FOUR"],
["S0157", "Moirans, MOIRANS BOULODROME"],
["S0122", "Moirans, MOIRANS CAMPALOUD"],
["S0120", "Moirans, MOIRANS CHALET"],
["S0137", "Moirans, MOIRANS CHAMPFEUILLET"],
["S0158", "Moirans, MOIRANS COLLEGE VERGERON"],
["S0133", "Moirans, MOIRANS COSTE GAZ"],
["S0136", "Moirans, MOIRANS COTE DES FILLES"],
["S0134", "Moirans, MOIRANS DELLORENZI"],
["S0534", "Moirans, MOIRANS ECHEVINS"],
["S0131", "Moirans, MOIRANS ESPACE JAIL"],
["S0167", "Moirans, MOIRANS GARE SNCF"],
["S0135", "Moirans, MOIRANS LE PAVILLET"],
["S0162", "Moirans, MOIRANS LES BALMES"],
["S0127", "Moirans, MOIRANS LES VIOLETTES"],
["S0140", "Moirans, MOIRANS LESARDIERE"],
["S0126", "Moirans, MOIRANS LOUIS MOYROUD"],
["S0161", "Moirans, MOIRANS LYCEE BEGHIN"],
["S0141", "Moirans, MOIRANS LYCEE P BEGHIN"],
["S0125", "Moirans, MOIRANS MAISONNEUVE"],
["S0123", "Moirans, MOIRANS MANGUELY"],
["S0535", "Moirans, MOIRANS MEDIATHEQUE"],
["S0584", "Moirans, MOIRANS MONTMARTEL"],
["S0165", "Moirans, MOIRANS NOVESPACE POMMARIN"],
["S0128", "Moirans, MOIRANS OUVRIERS PAPETIERS"],
["S0159", "Moirans, MOIRANS PARC DE LA GRILLE"],
["S0124", "Moirans, MOIRANS PETIT CHAMP FREY"],
["S0138", "Moirans, MOIRANS PETIT CRIEL"],
["S0121", "Moirans, MOIRANS POMPIERS"],
["S0160", "Moirans, MOIRANS RI D OLON"],
["S0132", "Moirans, MOIRANS RUE DE LA COSTE"],
["S0153", "Moirans, MOIRANS RUE DU 8 MAI 1945"],
["S0118", "Moirans, MOIRANS SAINT JACQUES"],
["S0163", "Moirans, MOIRANS SCHNEIDER"],
["S0533", "Moirans, VOUREY MONNAIR"],
["S0181", "Montferrat, MONTFERRAT 4 CHEMINS"],
["S0177", "Montferrat, MONTFERRAT JALAMION"],
["S0176", "Montferrat, MONTFERRAT LA GARENNE"],
["S0178", "Montferrat, MONTFERRAT LAC BLEU"],
["S0173", "Montferrat, MONTFERRAT LE VERNEY"],
["S0175", "Montferrat, MONTFERRAT LES ETEPPES"],
["S0179", "Montferrat, MONTFERRAT MUSEE"],
["S0172", "Montferrat, MONTFERRAT VERRONIERE"],
["S0171", "Montferrat, MONTFERRAT VILLAGE EGLISE"],
["S0194", "Paladru, PALADRU CALATRIN"],
["S0192", "Paladru, PALADRU GARAGE RENAULT"],
["S0193", "Paladru, PALADRU LA TRUITIERE"],
["S0190", "Paladru, PALADRU LES TROIS CHENES"],
["S0189", "Paladru, PALADRU ST P DE PALADRU"],
["S0191", "Paladru, PALADRU STADE"],
["S0188", "Paladru, PALADRU VILLAGE"],
["S0205", "Pommiers-la-Placette, POM. laPLACETTE COL DE LA PLACETTE"],
["S0207", "Pommiers-la-Placette, POM. laPLACETTE LES BARNIERS"],
["S0575", "Pommiers-la-Placette, POM. laPLACETTE PALLACHERE"],
["S0206", "Pommiers-la-Placette, POM. laPLACETTE QUATRE BRAS"],
["S0574", "Pommiers-la-Placette, POM. laPLACETTE TENNIS"],
["S0204", "Pommiers-la-Placette, POM. laPLACETTE VILLAGE"],
["S0209", "Réaumont, REAUMONT BOURG ECOLE"],
["S0216", "Réaumont, REAUMONT CHEMIN DU MOULIN"],
["S0210", "Réaumont, REAUMONT LE BAYARD"],
["S0217", "Réaumont, REAUMONT LE BESSEY"],
["S0213", "Réaumont, REAUMONT LE CARRET"],
["S0215", "Réaumont, REAUMONT LE CARRET TRANSFO"],
["S0214", "Réaumont, REAUMONT LE MOURET"],
["S0208", "Réaumont, REAUMONT VILLAGE"],
["S0572", "Réaumont, ST BLAISE DU BU CHATELARD"],
["S0557", "Renage, RENAGE EGLISE"],
["S0554", "Renage, RENAGE LA CROZE"],
["S0555", "Renage, RENAGE LES PRAIRIES"],
["S0556", "Renage, RENAGE PLACE CARDINALE"],
["S0558", "Renage, RENAGE ZA LE PLAN"],
["S0553", "Renage, RIVES CLOS JUVIN"],
["S0054", "Rives, CHARNECLES FERME BOURDIS"],
["S0222", "Rives, RIVES ABATTOIRS"],
["S0221", "Rives, RIVES ALLIMAND"],
["S0239", "Rives, RIVES BAS RIVES"],
["S0225", "Rives, RIVES BERLIOZ"],
["S0234", "Rives, RIVES CHARTREUSE"],
["S0223", "Rives, RIVES COLLEGE R DESNOS"],
["S0242", "Rives, RIVES COURBATIERE"],
["S0243", "Rives, RIVES GARE SNCF"],
["S0224", "Rives, RIVES JEAN JAURES"],
["S0232", "Rives, RIVES LEVATEL"],
["S0220", "Rives, RIVES LIBERATION"],
["S0231", "Rives, RIVES MAISON DE RETRAITE"],
["S0238", "Rives, RIVES MALADIERE"],
["S0233", "Rives, RIVES PASTIERES"],
["S0240", "Rives, RIVES PLACE X BROCHIER"],
["S0226", "Rives, RIVES SADI CARNOT"],
["S0252", "Saint-Aupre, ST AUPRE BARREAU"],
["S0246", "Saint-Aupre, ST AUPRE BEC FIN"],
["S0254", "Saint-Aupre, ST AUPRE CHAMPTORAZ"],
["S0256", "Saint-Aupre, ST AUPRE CHEVALLIER"],
["S0249", "Saint-Aupre, ST AUPRE CHEVILLARD"],
["S0253", "Saint-Aupre, ST AUPRE COLOMBIER"],
["S0251", "Saint-Aupre, ST AUPRE DELPHIN"],
["S0248", "Saint-Aupre, ST AUPRE GRAND VIVIER"],
["S0255", "Saint-Aupre, ST AUPRE LE GRAND CHEMIN"],
["S0250", "Saint-Aupre, ST AUPRE MARGARON"],
["S0247", "Saint-Aupre, ST AUPRE ROSSETIERE"],
["S0245", "Saint-Aupre, ST AUPRE TURE"],
["S0244", "Saint-Aupre, ST AUPRE VILLAGE"],
["S0542", "Saint-Blaise-du-Buis, APPRIEU BONPERTUIS"],
["S0211", "Saint-Blaise-du-Buis, REAUMONT LE GUICHARD"],
["S0260", "Saint-Blaise-du-Buis, ST BLAISE DU BU CIMETIERE"],
["S0265", "Saint-Blaise-du-Buis, ST BLAISE DU BU DEVEZ"],
["S0262", "Saint-Blaise-du-Buis, ST BLAISE DU BU GRAND VOYE"],
["S0257", "Saint-Blaise-du-Buis, ST BLAISE DU BU MAIRIE"],
["S0261", "Saint-Blaise-du-Buis, ST BLAISE DU BU PETIT VOYE"],
["S0258", "Saint-Blaise-du-Buis, ST BLAISE DU BU RAVIGNHOUSE"],
["S0269", "Saint-Blaise-du-Buis, ST BLAISE DU BU ROUTE DU RIVIER"],
["S0263", "Saint-Blaise-du-Buis, ST BLAISE DU BU RTE DE LA MURETTE"],
["S0259", "Saint-Blaise-du-Buis, ST BLAISE DU BU ZA LE TALAMUD"],
["S0272", "Saint-Bueil, ST BUEIL LA ROCHE"],
["S0275", "Saint-Bueil, ST BUEIL LE SATRE"],
["S0270", "Saint-Bueil, ST BUEIL RD82"],
["S0218", "Saint-Cassien, REAUMONT HALTE FERROVIAIRE"],
["S0278", "Saint-Cassien, ST CASSIEN EGLISE"],
["S0280", "Saint-Cassien, ST CASSIEN LE ROYER"],
["S0279", "Saint-Cassien, ST CASSIEN LE SAPIN"],
["S0277", "Saint-Cassien, ST CASSIEN MALOZA"],
["S0284", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY CARREF GD VIVIER"],
["S0298", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY CHARRAT"],
["S0294", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY COUCHONNIERE"],
["S0282", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY ETANG DAUPHIN"],
["S0287", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY GATELIERE"],
["S0290", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY LE PARIS"],
["S0288", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY LE PERRIN"],
["S0285", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY LE PICARD"],
["S0297", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY LE VIVIER"],
["S0295", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY LES GROS"],
["S0289", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY LES REYNAUDS"],
["S0293", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY LES ROUX"],
["S0283", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY LES VACHONNES"],
["S0286", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY POMPIERS"],
["S0292", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY TOLVON"],
["S0281", "Saint-Étienne-de-Crossey, ST E.DE CROSSEY VILLAGE"],
["S0322", "Saint-Geoire-en-Valdaine, StG.enVALDAINE BOULONGEAT"],
["S0330", "Saint-Geoire-en-Valdaine, StG.enVALDAINE CHAFFARDIERE"],
["S0304", "Saint-Geoire-en-Valdaine, StG.enVALDAINE CHAMPET"],
["S0326", "Saint-Geoire-en-Valdaine, StG.enVALDAINE CHOCHE LE PARIS"],
["S0324", "Saint-Geoire-en-Valdaine, StG.enVALDAINE CONSUOZ"],
["S0331", "Saint-Geoire-en-Valdaine, StG.enVALDAINE CONSUOZ ABRIBUS"],
["S0582", "Saint-Geoire-en-Valdaine, StG.enVALDAINE COTAGON"],
["S0329", "Saint-Geoire-en-Valdaine, StG.enVALDAINE GENDARMERIE"],
["S0310", "Saint-Geoire-en-Valdaine, StG.enVALDAINE HOPITAL"],
["S0309", "Saint-Geoire-en-Valdaine, StG.enVALDAINE L ORCIERE"],
["S0536", "Saint-Geoire-en-Valdaine, StG.enVALDAINE LA COMBE"],
["S0311", "Saint-Geoire-en-Valdaine, StG.enVALDAINE LA GLACIERE"],
["S0305", "Saint-Geoire-en-Valdaine, StG.enVALDAINE LA PALE"],
["S0328", "Saint-Geoire-en-Valdaine, StG.enVALDAINE LAMBERTIERE"],
["S0320", "Saint-Geoire-en-Valdaine, StG.enVALDAINE LAREMBERT"],
["S0319", "Saint-Geoire-en-Valdaine, StG.enVALDAINE LE FALQUE"],
["S0318", "Saint-Geoire-en-Valdaine, StG.enVALDAINE LE GROSSET"],
["S0325", "Saint-Geoire-en-Valdaine, StG.enVALDAINE LE MOLLARD"],
["S0312", "Saint-Geoire-en-Valdaine, StG.enVALDAINE LE PLATON"],
["S0323", "Saint-Geoire-en-Valdaine, StG.enVALDAINE LES BROSSES"],
["S0327", "Saint-Geoire-en-Valdaine, StG.enVALDAINE LES HOPITAUX"],
["S0317", "Saint-Geoire-en-Valdaine, StG.enVALDAINE LES PERRINS"],
["S0313", "Saint-Geoire-en-Valdaine, StG.enVALDAINE PLAMPALAIS"],
["S0410", "Saint-Geoire-en-Valdaine, VOIRON LOUIS NEEL"],
["S0030", "Saint-Jean-de-Moirans, LA BUISSE LE GAY"],
["S0142", "Saint-Jean-de-Moirans, MOIRANS CHARTREUX"],
["S0342", "Saint-Jean-de-Moirans, ST J.DE MOIRANS COLOMB AUTOROUTE"],
["S0341", "Saint-Jean-de-Moirans, ST J.DE MOIRANS COLOMBINIERE"],
["S0345", "Saint-Jean-de-Moirans, ST J.DE MOIRANS GYMNASE"],
["S0336", "Saint-Jean-de-Moirans, ST J.DE MOIRANS L ARCHAT"],
["S0335", "Saint-Jean-de-Moirans, ST J.DE MOIRANS LA MANCHE"],
["S0333", "Saint-Jean-de-Moirans, ST J.DE MOIRANS LE SAIX"],
["S0344", "Saint-Jean-de-Moirans, ST J.DE MOIRANS LES TISSEUSES"],
["S0538", "Saint-Jean-de-Moirans, ST J.DE MOIRANS MAISON POUR TOUS"],
["S0334", "Saint-Jean-de-Moirans, ST J.DE MOIRANS MARCHE AUX CERISES"],
["S0340", "Saint-Jean-de-Moirans, ST J.DE MOIRANS PARABOOT"],
["S0332", "Saint-Jean-de-Moirans, ST J.DE MOIRANS PATINIERE"],
["S0339", "Saint-Jean-de-Moirans, ST J.DE MOIRANS PLACE"],
["S0337", "Saint-Jean-de-Moirans, ST J.DE MOIRANS PLAN MENU RD1075"],
["S0537", "Saint-Jean-de-Moirans, ST J.DE MOIRANS TRINCON"],
["S0424", "Saint-Jean-de-Moirans, VOIRON PAVIOT"],
["S0354", "Saint-Julien-de-Raz, ST J.DE RATZ CENTRE PNEUMOLOGIE"],
["S0349", "Saint-Julien-de-Raz, ST J.DE RATZ LAC"],
["S0350", "Saint-Julien-de-Raz, ST J.DE RATZ LE GARREL"],
["S0355", "Saint-Julien-de-Raz, ST J.DE RATZ LE PLAN"],
["S0352", "Saint-Julien-de-Raz, ST J.DE RATZ LE PUITS"],
["S0348", "Saint-Julien-de-Raz, ST J.DE RATZ VILLAGE"],
["S0356", "Saint-Nicolas-de-Macherin, StN.DE MACHERIN CHATELONNIERE"],
["S0360", "Saint-Nicolas-de-Macherin, StN.DE MACHERIN HAUTEFORT"],
["S0362", "Saint-Nicolas-de-Macherin, StN.DE MACHERIN L USINE"],
["S0358", "Saint-Nicolas-de-Macherin, StN.DE MACHERIN LE PILON"],
["S0361", "Saint-Nicolas-de-Macherin, StN.DE MACHERIN LES PRAIRIES"],
["S0357", "Saint-Nicolas-de-Macherin, StN.DE MACHERIN MACHERIN"],
["S0363", "Saint-Nicolas-de-Macherin, StN.DE MACHERIN MELISSARD"],
["S0359", "Saint-Nicolas-de-Macherin, StN.DE MACHERIN PLACE"],
["S0365", "Saint-Sulpice-des-Rivoires, ST SULP.RIVOIRE BOURG"],
["S0364", "Saint-Sulpice-des-Rivoires, ST SULP.RIVOIRE CHATEAU D EAU"],
["S0367", "Saint-Sulpice-des-Rivoires, ST SULP.RIVOIRE FERME MOLLARD"],
["S0366", "Saint-Sulpice-des-Rivoires, ST SULP.RIVOIRE LA PLATIERE"],
["S0368", "Saint-Sulpice-des-Rivoires, ST SULP.RIVOIRE RIVOIRES"],
["S0375", "Tullins, TULLINS COLLEGE CONDORCET"],
["S0583", "Tullins, TULLINS CRUZILLE"],
["S0389", "Tullins, TULLINS ECOLE DESMOULINS"],
["S0369", "Tullins, TULLINS FURES"],
["S0397", "Tullins, TULLINS GARE SNCF"],
["S0379", "Tullins, TULLINS GOUY"],
["S0377", "Tullins, TULLINS JARDIN DES ARTS"],
["S0381", "Tullins, TULLINS L ESLINARD"],
["S0383", "Tullins, TULLINS LE MANGUELY"],
["S0395", "Tullins, TULLINS LE PARADIS"],
["S0374", "Tullins, TULLINS LE PAVE"],
["S0370", "Tullins, TULLINS LE PORT"],
["S0384", "Tullins, TULLINS LE VERT"],
["S0382", "Tullins, TULLINS LES MASSONS"],
["S0372", "Tullins, TULLINS MICHEL PERRET"],
["S0380", "Tullins, TULLINS ORCEL"],
["S0390", "Tullins, TULLINS PETIT TIZIN"],
["S0373", "Tullins, TULLINS ROUTE DE GRENOBLE"],
["S0391", "Tullins, TULLINS ST JEAN DE CHEPY"],
["S0623", "Tullins, TULLINS STADE JEAN VALOIS"],
["S0622", "Tullins, TULLINS VERDEMONT"],
["S0624", "Tullins, TULLINS ZONE COMMERCIALE"],
["S0398", "Velanne, VELANNE CENTRE"],
["S0399", "Velanne, VELANNE LA SAUGE"],
["S0402", "Voiron, VOIRON AVENUE DE PAVIOT"],
["S0423", "Voiron, VOIRON BALTISS"],
["S0456", "Voiron, VOIRON BD DU GUILLON"],
["S0415", "Voiron, VOIRON BELVEDERE I"],
["S0414", "Voiron, VOIRON BELVEDERE II"],
["S0442", "Voiron, VOIRON BERIDOT"],
["S0409", "Voiron, VOIRON BLANCHISSERIES"],
["S0446", "Voiron, VOIRON BRAMERET"],
["S0411", "Voiron, VOIRON BRUNERIE"],
["S0448", "Voiron, VOIRON BRUNETIERE"],
["S0418", "Voiron, VOIRON CENTRE SOCIAL"],
["S0457", "Voiron, VOIRON CES LA GARENNE"],
["S0444", "Voiron, VOIRON CHAMPFEUILLET"],
["S0443", "Voiron, VOIRON CHAMPFEUILLET ZA"],
["S0434", "Voiron, VOIRON CLINIQUE"],
["S0447", "Voiron, VOIRON CLOS BERARD"],
["S0417", "Voiron, VOIRON COLLEGE ST JOSEPH"],
["S0445", "Voiron, VOIRON CROIX MORIN"],
["S0493", "Voiron, VOIRON CROIX ROUSSE"],
["S0472", "Voiron, VOIRON DENFERT ROCHEREAU"],
["S0465", "Voiron, VOIRON DOCTEUR VALOIS"],
["S0452", "Voiron, VOIRON ECOLE STE MARIE"],
["S0485", "Voiron, VOIRON EDGAR KOFLER"],
["S0416", "Voiron, VOIRON EGLISE ST PIERRE"],
["S0425", "Voiron, VOIRON FATON"],
["S0412", "Voiron, VOIRON FBG SERMORENS"],
["S0494", "Voiron, VOIRON FERRONNIERE"],
["S0464", "Voiron, VOIRON FRERES TARDY"],
["S0600", "Voiron, VOIRON GARE NORD 01"],
["S0601", "Voiron, VOIRON GARE NORD 02"],
["S0603", "Voiron, VOIRON GARE NORD 04"],
["S0604", "Voiron, VOIRON GARE NORD 05"],
["S0562", "Voiron, VOIRON GARE NORD QUAI 03"],
["S0605", "Voiron, VOIRON GARE SUD 06"],
["S0606", "Voiron, VOIRON GARE SUD 07"],
["S0607", "Voiron, VOIRON GARE SUD 08"],
["S0611", "Voiron, VOIRON GARE SUD 12"],
["S0612", "Voiron, VOIRON GARE SUD 13"],
["S0613", "Voiron, VOIRON GARE SUD 14"],
["S0615", "Voiron, VOIRON GARE SUD 16"],
["S0616", "Voiron, VOIRON GARE SUD 17"],
["S0487", "Voiron, VOIRON GENDARMERIE"],
["S0419", "Voiron, VOIRON GENERAL LECLERC"],
["S0450", "Voiron, VOIRON GEORGE SAND"],
["S0420", "Voiron, VOIRON GEORGES FRIER"],
["S0433", "Voiron, VOIRON GRAND ANGLE"],
["S0413", "Voiron, VOIRON GYMNASE LA GARENNE"],
["S0476", "Voiron, VOIRON HOPITAL"],
["S0449", "Voiron, VOIRON HORTENSIAS"],
["S0451", "Voiron, VOIRON IMPOTS"],
["S0475", "Voiron, VOIRON J. CHIRAC"],
["S0405", "Voiron, VOIRON L AGNELAS"],
["S0436", "Voiron, VOIRON LAVOIR DE CRIEL"],
["S0489", "Voiron, VOIRON LE PARVIS"],
["S0488", "Voiron, VOIRON LE ROUSSET"],
["S0625", "Voiron, VOIRON LE ROUSSET 2"],
["S0407", "Voiron, VOIRON LE VERDIN"],
["S0408", "Voiron, VOIRON LEPRINCE RINGUET"],
["S0492", "Voiron, VOIRON LES ECUREUILS"],
["S0486", "Voiron, VOIRON LES TUILIERES"],
["S0459", "Voiron, VOIRON LYCEE MARTELLIERE"],
["S0421", "Voiron, VOIRON MAIRIE"],
["S0404", "Voiron, VOIRON MAISON BLANCHE"],
["S0458", "Voiron, VOIRON MEDIATHEQUE"],
["S0403", "Voiron, VOIRON PAVIOT ECOLE"],
["S0406", "Voiron, VOIRON POLE DE VOUISE"],
["S0437", "Voiron, VOIRON RUE DE CRIEL"],
["S0439", "Voiron, VOIRON RUE DES CASTORS"],
["S0438", "Voiron, VOIRON RUE DES MARMOTTES"],
["S0455", "Voiron, VOIRON RUE GUIMET"],
["S0454", "Voiron, VOIRON SNCF"],
["S0422", "Voiron, VOIRON VERDUN"],
["S0498", "Voissant, VOISSANT EGLISE"],
["S0499", "Voissant, VOISSANT SOUS LE MONT"],
["S0500", "Voissant, VOISSANT VERCHERE"],
["S0164", "Voreppe, MOIRANS THALES"],
["S0525", "Voreppe, VOREPPE ALUMINIUM"],
["S0514", "Voreppe, VOREPPE AV DU 11 NOVEMBRE"],
["S0509", "Voreppe, VOREPPE BANNETTES"],
["S0513", "Voreppe, VOREPPE BASCULE"],
["S0517", "Voreppe, VOREPPE CAFE ADRAIT"],
["S0521", "Voreppe, VOREPPE CHARMINELLES"],
["S0519", "Voreppe, VOREPPE CHASSOLIERE"],
["S0505", "Voreppe, VOREPPE CHEVALON"],
["S0503", "Voreppe, VOREPPE DOCTEUR THEVENET"],
["S0524", "Voreppe, VOREPPE ELS GROUP"],
["S0530", "Voreppe, VOREPPE GARE SNCF"],
["S0522", "Voreppe, VOREPPE L ARCADE"],
["S0512", "Voreppe, VOREPPE LOGIS NEUF"],
["S0527", "Voreppe, VOREPPE LOUIS ARMAND"],
["S0515", "Voreppe, VOREPPE MAIRIE"],
["S0506", "Voreppe, VOREPPE MALOSSANE"],
["S0510", "Voreppe, VOREPPE MONUMENT AUX MORTS"],
["S0526", "Voreppe, VOREPPE POMA"],
["S0529", "Voreppe, VOREPPE RADIALL"],
["S0528", "Voreppe, VOREPPE SAMLLOC"],
["S0504", "Voreppe, VOREPPE SEMINAIRE"],
["S0520", "Voreppe, VOREPPE VOLOUISE"],
["S0620", "Vourey, VOUREY LAVOIR"],
["S0532", "Vourey, VOUREY PRESSOIR"],

];
