var linesImages = ["NAVA", "NAVB", "NAVC", "NAVD", "NAVE", "A", "B", "C", "D", "E", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11", "C12", "C13", "C14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "34", "35", "36", "40", "41", "42", "44", "45", "46", "47", "48", "49", "50", "51", "54", "55", "56", "59", "60", "61", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "78", "79", "80", "82", "84", "85", "86", "88", "89", "90", "91", "92", "N62", "N93"];

var dictStops = [
["SEM:GEN120TOISE", "Le Pont-de-Claix, 120 Toises"],
["SEM:GENGAROUTIE", "Grenoble, Gare Routière"],
["SEM:GEN16AOUT44", "Saint-Martin-le-Vinoux, Résistance"],
["SEM:GEN8MAI1945", "Saint-Martin-d'Hères, 8 mai 1945"],
["SEM:GENABBEGREG", "Grenoble, Abbé Grégoire"],
["SEM:GENADELAUNE", "Échirolles, Auguste Delaune"],
["SEM:GENAIGUIHEX", "Meylan, Aiguinards-Hexagone"],
["SEM:GENALB1BELG", "Grenoble, Albert 1er de Belgique"],
["SEM:GENALBERGES", "Vaulnaveys-le-Haut, Les Alberges"],
["SEM:GENALEGRANG", "Vif, Allée des Granges"],
["SEM:GENALEMBERT", "Grenoble, D'Alembert"],
["SEM:GENALLIANCE", "Vizille, L'Alliance"],
["SEM:GENALLIES", "Grenoble, Alliés"],
["SEM:GENALLOVES", "Saint-Martin-d'Hères, Les Alloves"],
["SEM:GENALPEXPO", "Eybens, Alpexpo"],
["SEM:GENALSACELO", "Grenoble, Alsace-Lorraine"],
["SEM:GENANATFRAN", "Grenoble, Anatole France"],
["SEM:GENANCIEMAI", "Fontaine, Ancienne Mairie"],
["SEM:GENANCIGARE", "Seyssins, Ancienne Gare"],
["SEM:GENANCMAIRI", "Meylan, Ancienne Mairie"],
["SEM:GENANGONNES", "Brié-et-Angonnes, Les Angonnes"],
["SEM:GENANGUISSE", "Saint-Martin-d'Hères, Anguisses"],
["SEM:GENANMAL", "Jarrie, Clos Jouvin"],
["SEM:GENARAGO", "Grenoble, Arago"],
["SEM:GENARBERGES", "Seyssinet-Pariset, Aristide Bergès"],
["SEM:GENARGOUD", "Seyssins, L'Argoud"],
["SEM:GENARGOUGES", "Grenoble, André Argouges"],
["SEM:GENARLEQUIN", "Grenoble, Arlequin"],
["SEM:GENARNAUDS", "Domène, Les Arnauds"],
["SEM:GENARZELIER", "Le Gua, L'Arzelier"],
["SEM:GENAUGUFERR", "Échirolles, Auguste Ferrier"],
["SEM:GENAUGURAVI", "Grenoble, Auguste Ravier"],
["SEM:GENAVREPUB", "Bresson, Avenue de la République"],
["SEM:GENBACHELAR", "Grenoble, Bachelard"],
["SEM:GENBAJATIER", "Grenoble, Bajatière"],
["SEM:GENBALMETTE", "Claix, La Balmette"],
["SEM:GENBALZAZ", "Varces-Allières-et-Risset, Balzac"],
["SEM:GENBANCHARD", "Saint-Martin-le-Vinoux, La Banchardière"],
["SEM:GENBARBET", "Quaix-en-Chartreuse, Le Barbet"],
["SEM:GENBARNA", "Saint-Égrève, Collège Barnave"],
["SEM:GENBASCULE", "Saint-Paul-de-Varces, La Bascule"],
["SEM:GENBASMONT", "Quaix-en-Chartreuse, Bas de Mont-Quaix"],
["SEM:GENBASPET", "Quaix-en-Chartreuse, Bas de Petesset"],
["SEM:GENBASQUAIX", "Quaix-en-Chartreuse, Le Bas de Quaix"],
["SEM:GENBASTILLE", "La Tronche, Bastille"],
["SEM:GENBAUCHES", "Claix, Les Bauches"],
["SEM:GENBAYANNE", "Miribel-Lanchâtre, Bayanne"],
["SEM:GENBAYARD", "Échirolles, Bayard"],
["SEM:GENBEALIERE", "Meylan, Les Béalières"],
["SEM:GENBEAU", "Claix, Beau Dunois"],
["SEM:GENBEAUDONI", "Montbonnot-Saint-Martin, Baudonniere"],
["SEM:GENBEAULIEU", "Brié-et-Angonnes, Beaulieu"],
["SEM:GENBEAUREVO", "Sassenage, Beaurevoir"],
["SEM:GENBEAUSITE", "Seyssinet-Pariset, Beau Site"],
["SEM:GENBEAUVERT", "Grenoble, Beauvert"],
["SEM:GENBEAUVOIR", "Seyssins, Beauvoir"],
["SEM:GENBELAIR", "Eybens, Bel Air"],
["SEM:GENBELLEDON", "Saint-Égrève, Belledonne"],
["SEM:GENBELLEVU", "Saint-Égrève, Bellevue"],
["SEM:GENBELLEVUE", "Claix, Bellevue"],
["SEM:GENBELVEDER", "Seyssinet-Pariset, Belvédère"],
["SEM:GENBERGVERC", "Seyssinet-Pariset, Bergès - Vercors"],
["SEM:GENBERIVIER", "Meylan, Bérivière"],
["SEM:GENBERLIOGN", "Varces-Allières-et-Risset, Berliognière"],
["SEM:GENBERRIAT", "Grenoble, Berriat-Le Magasin"],
["SEM:GENBERULLE", "Grenoble, Place de Bérulle"],
["SEM:GENBERYL", "Veurey-Voroize, Le Béryl"],
["SEM:GENBIBLIUNI", "Gières, Université – Bibliothèques"],
["SEM:GENBIOLLE", "Saint-Égrève, La Biolle - Gare"],
["SEM:GENBIOLOGIE", "Gières, Universités - Biologie"],
["SEM:GENBIRHAKEI", "Grenoble, Bir Hakeim"],
["SEM:GENBLANCFON", "Sassenage, Blanc Fontaine"],
["SEM:GENBLANCHON", "Saint-Martin-d'Hères, Parc Jo Blanchon"],
["SEM:GENBONNAIS", "Saint-Égrève, Les Bonnais"],
["SEM:GENBONPASTE", "Grenoble, Bon Pasteur"],
["SEM:GENBOUCHDV", "Seyssinet-Pariset, Bouchayer - Hôtel de Ville"],
["SEM:GENBOULODRO", "Claix, Boulodrome-Ecole"],
["SEM:GENBOURG", "Murianette, Le Bourg"],
["SEM:GENBOURNET", "Seyssins, Le Bournet"],
["SEM:GENBRESSON", "Bresson, Bresson Mairie"],
["SEM:GENBRIE", "Brié-et-Angonnes, Mont Rolland"],
["SEM:GENBRIECOLE", "Brié-et-Angonnes, L'Olympe"],
["SEM:GENBRIEGLIS", "Brié-et-Angonnes, Eglise"],
["SEM:GENBRIOT", "Murianette, La Briot"],
["SEM:GENBRUYERE", "Grenoble, La Bruyère-Parc Jean Verlhac"],
["SEM:GENBUCLOS", "Corenc, Buclos"],
["SEM:GENBUIS", "Saint-Martin-le-Vinoux, La Buisseratière"],
["SEM:GENBUSSEROL", "Meylan, Busserolles"],
["SEM:GENCAB", "Grenoble, Colonel Dumont"],
["SEM:GENCAMPVIZ", "Vizille, Camping"],
["SEM:GENCAP38", "Saint-Égrève, CAP 38"],
["SEM:GENCAPDESH", "Saint-Égrève, Cap des H'"],
["SEM:GENCAPUCHE", "Grenoble, Capuche"],
["SEM:GENCARINA", "Saint-Martin-d'Hères, Le Carina"],
["SEM:GENCARONBAS", "La Tronche, La Carronnerie Basse"],
["SEM:GENCARONRIE", "La Tronche, Carronnerie - Ile d'Amour"],
["SEM:GENCARRIERE", "Claix, Carrière"],
["SEM:GENCASANOVA", "Échirolles, Danielle Casanova"],
["SEM:GENCASAVILL", "Grenoble, Casamaures - Village"],
["SEM:GENCASBONNE", "Grenoble, Caserne de Bonne"],
["SEM:GENCASSOULE", "Miribel-Lanchâtre, Cassoulet"],
["SEM:GENCEACAMB", "Grenoble, Marie-Louise Paris - CEA"],
["SEM:GENCEDRE", "Corenc, Le Cèdre"],
["SEM:GENCEMOI", "Grenoble, Cémoi"],
["SEM:GENCENSOCIO", "Poisat, Centre Socio-Culturel"],
["SEM:GENCENTHEOL", "La Tronche, Centre Théologique"],
["SEM:GENCENTRAER", "Quaix-en-Chartreuse, Centre Aéré"],
["SEM:GENCENTRESU", "Seyssins, Grand Pré - Centre Sud"],
["SEM:GENCENTRSOC", "Seyssinet-Pariset, L'Arche"],
["SEM:GENCHABER", "Jarrie, Les Chaberts"],
["SEM:GENCHALET", "Vif, Le Chalet"],
["SEM:GENCHAMBORD", "Varces-Allières-et-Risset, Chambord"],
["SEM:GENCHAMECHA", "Sassenage, Chamechaude"],
["SEM:GENCHAMP", "Montchaboud, Champ Clocher"],
["SEM:GENCHAMPFIL", "Eybens, Champ Fila"],
["SEM:GENCHAMPION", "Grenoble, Championnet"],
["SEM:GENCHAMPLAR", "Meylan, Champlars"],
["SEM:GENCHAMPROM", "Saint-Martin-d'Hères, Champ Roman"],
["SEM:GENCHAMPRON", "Gières, Champrondet"],
["SEM:GENCHAMPSD", "Champ-sur-Drac, ZA La Plaine"],
["SEM:GENCHAMPSEL", "Grenoble, Champs-Elysées"],
["SEM:GENCHAMPY", "Saint-Égrève, Champy"],
["SEM:GENCHAMROC", "Meylan, Champ Rochas"],
["SEM:GENCHANDON", "Le Pont-de-Claix, Edmée Chandon"],
["SEM:GENCHANTEFE", "Vizille, Chantefeuille"],
["SEM:GENCHANTERA", "Claix, La Chanteraie"],
["SEM:GENCHARBON", "Jarrie, Les Charbonnaux"],
["SEM:GENCHARLMIC", "Fontaine, Charles Michels"],
["SEM:GENCHARMETT", "Fontaine, Charmettes"],
["SEM:GENCHARPEN", "Quaix-en-Chartreuse, Le Charpen"],
["SEM:GENCHARRIER", "Claix, Charrières"],
["SEM:GENCHAT", "Vizille, Place du Château"],
["SEM:GENCHATBEAU", "Sassenage, Château de Beaurevoir"],
["SEM:GENCHATEAU", "Échirolles, Le Château"],
["SEM:GENCHATEAUQ", "Quaix-en-Chartreuse, Le Château"],
["SEM:GENCHATEAUX", "Veurey-Voroize, Chemin du Parc"],
["SEM:GENCHATELAR", "Veurey-Voroize, Châtelard"],
["SEM:GENCHATELIE", "Eybens, La Châtelière"],
["SEM:GENCHATSASS", "Sassenage, Château de Sassenage"],
["SEM:GENCHAULNES", "Noyarey, Chaulnes"],
["SEM:GENCHAUMES", "Claix, Les Chaumes"],
["SEM:GENCHAUMETI", "Meylan, Chaumetière"],
["SEM:GENCHAUMIER", "Seyssins, Hameau des Chaumières"],
["SEM:GENCHAVANT", "Grenoble, Chavant"],
["SEM:GENCHEABBE", "Claix, Chemin de l'Abbé"],
["SEM:GENCHEMAUPA", "Noyarey, Rue du Maupas"],
["SEM:GENCHEMBATO", "Corenc, Batonnière"],
["SEM:GENCHEMI", "Saint-Martin-le-Vinoux, Canet"],
["SEM:GENCHEMVER", "Saint-Égrève, Chemin vert"],
["SEM:GENCHENES", "Sassenage, Les Chênes"],
["SEM:GENCHENEVIE", "Domène, Chenevières"],
["SEM:GENCHIAISE", "Proveysieux, La Chiaise"],
["SEM:GENCHIEZE", "Claix, La Chièze"],
["SEM:GENCHOLLET", "Brié-et-Angonnes, Le Chollet"],
["SEM:GENCHOPIN", "Saint-Martin-d'Hères, Chopin"],
["SEM:GENCHORCOND", "Grenoble, Chorier - Condorcet"],
["SEM:GENCHRISTUR", "Grenoble, Christophe Turc"],
["SEM:GENCHURU", "Le Sappey-en-Chartreuse, Churut"],
["SEM:GENCIMEBOUR", "Vif, La Cime du Bourg"],
["SEM:GENCIMEMONT", "Quaix-en-Chartreuse, La Cime de Mont-Quaix"],
["SEM:GENCIMENTIE", "Claix, Les Cimentiers"],
["SEM:GENCIMESEYP", "Seyssinet-Pariset, Cimetière"],
["SEM:GENCIMETIGA", "Seyssins, Garlettes"],
["SEM:GENCIMETIGS", "La Tronche, Cimetière du Grand Sablon"],
["SEM:GENCITEINTE", "Grenoble, Cité Internationale"],
["SEM:GENCITELABE", "Saint-Martin-d'Hères, Cité Labeye"],
["SEM:GENCITEMACE", "Grenoble, Cité Jean Macé"],
["SEM:GENCITEPMIS", "Grenoble, Cité Paul Mistral"],
["SEM:GENCITESCOL", "Varces-Allières-et-Risset, Collège Jules Verne"],
["SEM:GENCLAIXMAI", "Claix, Claix Mairie"],
["SEM:GENCLEMENCE", "Grenoble, Clémenceau"],
["SEM:GENCLINBELD", "Saint-Martin-d'Hères, Clinique Belledonne"],
["SEM:GENCLINDAU", "Seyssins, Clinique - Portail"],
["SEM:GENCLINMUT", "Grenoble, Groupe Hospitalier Mutualiste"],
["SEM:GENCLOSDOMI", "Le Pont-de-Claix, Clos Dominique"],
["SEM:GENCLOSDOR", "Grenoble, Clos d'Or"],
["SEM:GENCLOSGRUE", "Saint-Martin-le-Vinoux, Clos Gérard Gruel"],
["SEM:GENCLOSSTMA", "Saint-Martin-le-Vinoux, Clos Saint Martin"],
["SEM:GENCOLARZEL", "Château-Bernard, Col de l'Arzelier"],
["SEM:GENCOLAVIER", "Mont-Saint-Martin, Colavière"],
["SEM:GENCOLCHART", "Saint-Martin-le-Vinoux, Collège Chartreuse"],
["SEM:GENCOLCLEME", "Saint-Martin-le-Vinoux, Col de Clémencières"],
["SEM:GENCOLCOMBO", "Claix, Col de Comboire"],
["SEM:GENCOLI", "Saint-Martin-d'Hères, Coli"],
["SEM:GENCOLLSAUL", "Eybens, Collège des Saules"],
["SEM:GENCOLMANHE", "Échirolles, Colonel Manhès"],
["SEM:GENCOLMATTO", "Vizille, Collège Les Mattons"],
["SEM:GENCOLPORTE", "Sarcenas, Col de Porte"],
["SEM:GENCOLVENCE", "Corenc, Col de Vence"],
["SEM:GENCOMBALEY", "Proveysieux, Planfay Combaleyre"],
["SEM:GENCOMBOIRE", "Échirolles, Comboire"],
["SEM:GENCOMMANAL", "La Tronche, Commandant Nal"],
["SEM:GENCOMMANDE", "Échirolles, Commanderie"],
["SEM:GENCOMPLEXE", "Sassenage, Complexe Sportif"],
["SEM:GENCONDIUNI", "Saint-Martin-d'Hères, Condillac - Universités"],
["SEM:GENCONDORCE", "Grenoble, Condorcet"],
["SEM:GENCONRADKI", "Saint-Martin-le-Vinoux, Conrad Kilian"],
["SEM:GENCORENCMA", "Corenc, Corenc Mairie"],
["SEM:GENCORENCVI", "Corenc, Corenc Village"],
["SEM:GENCORNEDOR", "Corenc, La Corne d'Or"],
["SEM:GENCORNIERS", "Vizille, Les Corniers"],
["SEM:GENCOSSEY", "Claix, Cossey"],
["SEM:GENCOTEAU", "Claix, Le Coteau"],
["SEM:GENCOTESASS", "Sassenage, Les Côtes"],
["SEM:GENCOUBERTI", "Domène, Coubertin"],
["SEM:GENCROISEM", "Saint-Martin-d'Uriage, Croisement 6"],
["SEM:GENCROIX", "Saint-Paul-de-Varces, La Croix"],
["SEM:GENCROIXROU", "Saint-Martin-d'Hères, Croix Rouge"],
["SEM:GENCRXROLLA", "Claix, La Croix Rolland"],
["SEM:GENCULFROID", "Venon, Cul Froid"],
["SEM:GENCURIVERC", "Fontaine, Curie - Vercors"],
["SEM:GENCUVILLEU", "Saint-Égrève, Cuvilleux"],
["SEM:GENCXCIBENS", "Meylan, Croix de Cibeins"],
["SEM:GENCXMONTFL", "Corenc, Croix de Montfleury"],
["SEM:GENCXPATRE", "Saint-Martin-d'Hères, Croix du Pâtre"],
["SEM:GENCXRAMEAU", "Meylan, Croix des Rameaux"],
["SEM:GENDEGAULLE", "Eybens, Général de Gaulle"],
["SEM:GENDENPAPIN", "Échirolles, Denis Papin"],
["SEM:GENDEPORTES", "Grenoble, Rue des Déportés"],
["SEM:GENDETOURBE", "Meylan, La Détourbe"],
["SEM:GENDOMENEMA", "Domène, Domène Mairie"],
["SEM:GENDOYENGOS", "La Tronche, Doyen Gosse"],
["SEM:GENDRAC", "Claix, Mémorial"],
["SEM:GENDRAC2", "Échirolles, Drac"],
["SEM:GENDRCALME", "Grenoble, Vallier - Docteur Calmette"],
["SEM:GENDRIANT", "Grenoble, Driant"],
["SEM:GENDRMARTIN", "Grenoble, Docteur Martin"],
["SEM:GENDRMAZET", "Grenoble, Docteur Mazet"],
["SEM:GENDRSCHWEI", "Grenoble, Docteur Schweitzer"],
["SEM:GENDUBEDOUT", "Grenoble, Hubert Dubedout - Maison du Tourisme"],
["SEM:GENECHALIER", "Veurey-Voroize, Les Echalières"],
["SEM:GENECHIGARE", "Échirolles, Echirolles Gare"],
["SEM:GENECOLE", "Quaix-en-Chartreuse, Ecoles"],
["SEM:GENECOLELP", "Champ-sur-Drac, Le Pavillon"],
["SEM:GENECOLEREY", "Vif, Ecole Reymure"],
["SEM:GENECOLHOSP", "Échirolles, Ecoles Hospitalières"],
["SEM:GENECRINS", "Fontaine, Les Écrins"],
["SEM:GENECUREUIL", "Échirolles, Ecureuil"],
["SEM:GENEDELWEIS", "Gières, Edelweiss"],
["SEM:GENEDISON", "Grenoble, Edison"],
["SEM:GENEDMOESMO", "Grenoble, Edmond Esmonin"],
["SEM:GENEDROSTAN", "Saint-Martin-d'Hères, Edmond Rostand"],
["SEM:GENEDVAILLA", "Saint-Martin-d'Hères, Edouard Vaillant"],
["SEM:GENEGLISESE", "Saint-Égrève, Eglise"],
["SEM:GENEGRECOLE", "Proveysieux, Proveysieux Village"],
["SEM:GENEGREGUA", "Proveysieux, Pont du Gua"],
["SEM:GENEGREMOLL", "Proveysieux, Le Mollard"],
["SEM:GENEJCURIE", "Vizille, Ecoles Joliot-Curie"],
["SEM:GENELSATRIO", "Saint-Martin-d'Hères, Elsa Triolet"],
["SEM:GENEMILGUEY", "Grenoble, Emile Gueymard"],
["SEM:GENENGENIER", "Sassenage, Les Engenières"],
["SEM:GENEPICEA", "Gières, Epicéa"],
["SEM:GENESCLANGO", "Grenoble, Esclangon"],
["SEM:GENESPLANAD", "Grenoble, Annie Fratellini-Esplanade"],
["SEM:GENESSARTS", "Échirolles, Essarts - La Butte"],
["SEM:GENETIEGRAP", "Saint-Martin-d'Hères, Etienne Grappe"],
["SEM:GENEUGENESU", "Grenoble, Eugène Sue"],
["SEM:GENEYGALA", "Corenc, Eygala"],
["SEM:GENFACPHARM", "Meylan, Faculté de Pharmacie"],
["SEM:GENFAUCONNI", "Seyssinet-Pariset, Fauconnière"],
["SEM:GENFELIXVIA", "Grenoble, Félix Viallet"],
["SEM:GENFIANCEY", "Saint-Égrève, Chemin Fiancey"],
["SEM:GENFLAUCLOS", "Grenoble, Flaubert - Clos d'Or"],
["SEM:GENFOCHAIRE", "Mont-Saint-Martin, Fochaire"],
["SEM:GENFOCHFERI", "Grenoble, Foch - Ferrié"],
["SEM:GENFONDRATE", "Claix, Fond Ratel"],
["SEM:GENFONTAGNE", "Varces-Allières-et-Risset, Fontagneux"],
["SEM:GENFONTAHDV", "Fontaine, Fontaine Hôtel de Ville - La Source"],
["SEM:GENFONTAINA", "Fontaine, Les Fontainades - Le Vog"],
["SEM:GENFONTANIL", "Fontanil-Cornillon, Palluel"],
["SEM:GENFONTANIM", "Fontanil-Cornillon, Le Fontanil Mairie"],
["SEM:GENFONTCIM", "Fontanil-Cornillon, Le Fontanil Cimetière"],
["SEM:GENFONVIEIL", "Quaix-en-Chartreuse, Fontvieille"],
["SEM:GENFRBLUMET", "Sassenage, François Blumet"],
["SEM:GENFRENAIE", "Venon, La Frênaie"],
["SEM:GENFRQUESNA", "Échirolles, François Quesnay"],
["SEM:GENFURONNIE", "Claix, Furonnières"],
["SEM:GENGABFAURE", "Saint-Martin-d'Hères, Gabriel Fauré"],
["SEM:GENGAGNIERE", "Saint-Martin-le-Vinoux, Louis Gagnière"],
["SEM:GENGALOCHER", "Saint-Martin-d'Hères, Galochère"],
["SEM:GENGARCINS", "Vif, Les Garcins"],
["SEM:GENGARDE", "Saint-Paul-de-Varces, La Garde"],
["SEM:GENGAREJARR", "Jarrie, Jarrie Gare"],
["SEM:GENGARENNE", "Corenc, La Garenne"],
["SEM:GENGARES", "Grenoble, Gares"],
["SEM:GENGARLETTE", "Seyssins, Garlettes"],
["SEM:GENGAVANIER", "Saint-Égrève, Gavanière"],
["SEM:GENGAY", "Saint-Martin-d'Hères, Gay"],
["SEM:GENGAYLUSSA", "Échirolles, Gay Lussac"],
["SEM:GENGDCHATEL", "Saint-Martin-d'Hères, Grand Châtelet"],
["SEM:GENGDTRONCH", "La Tronche, Grande Tronche"],
["SEM:GENGDVERGER", "Champ-sur-Drac, Grand Verger"],
["SEM:GENGERARPHI", "Fontaine, Gérard Philipe"],
["SEM:GENGIERGARE", "Gières, Gières Gare - Universités"],
["SEM:GENGIGNOUX", "Grenoble, Maurice Gignoux"],
["SEM:GENGIRAUDIE", "Varces-Allières-et-Risset, La Giraudière"],
["SEM:GENGLAIEULS", "Saint-Martin-d'Hères, Glaïeuls"],
["SEM:GENGLAIRAUX", "Saint-Égrève, Les Glairaux"],
["SEM:GENGLIERES", "Échirolles, Les Glières"],
["SEM:GENGONNADIE", "Champ-sur-Drac, Marcel Paul"],
["SEM:GENGRANDPRE", "Seyssinet-Pariset, Grand Pré"],
["SEM:GENGRANG", "Saint-Égrève, Grange Haute"],
["SEM:GENGRANGE", "Vif, La Grange"],
["SEM:GENGRANGECH", "Eybens, La Grange du Château"],
["SEM:GENGRANGES", "Échirolles, Les Granges"],
["SEM:GENGRANIER", "Meylan, Granier"],
["SEM:GENGRAPH", "Échirolles, Centre du graphisme"],
["SEM:GENGRDPLACE", "Grenoble, Grand'place"],
["SEM:GENGRDSABLO", "La Tronche, Grand Sablon"],
["SEM:GENGREHOTEL", "Grenoble, Grenoble Hôtel de Ville"],
["SEM:GENGRESIVAU", "Corenc, Grésivaudan"],
["SEM:GENGRIMPI", "Vizille, Le Grimpillon"],
["SEM:GENGROSCHEN", "Varces-Allières-et-Risset, Le Gros Chêne"],
["SEM:GENGRUGLIAS", "Échirolles, Grugliasco"],
["SEM:GENGUEBOUTE", "Meylan, Gué du Boutet"],
["SEM:GENGUERIMAN", "Saint-Martin-le-Vinoux, 16 Août 1944"],
["SEM:GENGUICHARD", "Vaulnaveys-le-Haut, Les Guichards"],
["SEM:GENGUILE", "Sarcenas, Guilletière"],
["SEM:GENGUSTRIVE", "Grenoble, Gustave Rivet"],
["SEM:GENGUYMOCQU", "Échirolles, Guy Mocquet"],
["SEM:GENHBERLUNI", "Saint-Martin-d'Hères, Hector Berlioz - Universités"],
["SEM:GENHDUNANT", "Grenoble, Henri Dunant"],
["SEM:GENHEBOURG", "Herbeys, Herbeys Le Bourg"],
["SEM:GENHENRIREY", "Seyssins, Henri Rey"],
["SEM:GENHENRIWAL", "Saint-Martin-d'Hères, Henri Wallon"],
["SEM:GENHOPITSUD", "Échirolles, Hôpital Sud"],
["SEM:GENHOPMICHA", "La Tronche, Hôpital Michallon"],
["SEM:GENHOPOLICE", "Grenoble, Hôtel de Police"],
["SEM:GENHORLOGE", "Saint-Martin-le-Vinoux, Horloge"],
["SEM:GENHOTELBEL", "Saint-Martin-le-Vinoux, Hôtel Bellevue"],
["SEM:GENHOUILLEB", "Saint-Martin-d'Hères, Houille Blanche"],
["SEM:GENHTMEYLAN", "Meylan, Haut-Meylan"],
["SEM:GENHVENCE", "Corenc, Hameau de Vence"],
["SEM:GENILESCORD", "Veurey-Voroize, Iles Cordées"],
["SEM:GENILESMARS", "Le Pont-de-Claix, Iles de Mars"],
["SEM:GENILEVERTE", "Grenoble, Ile Verte"],
["SEM:GENILIADE", "Eybens, L'Iliade"],
["SEM:GENINRIA", "Montbonnot-Saint-Martin, INRIA"],
["SEM:GENIRENEJOL", "Le Pont-de-Claix, Irène Joliot-Curie"],
["SEM:GENIUTUFRAP", "Gières, Universités - IUT - UFRAPS"],
["SEM:GENJACOBINS", "Vif, Jacobins"],
["SEM:GENJAILLIER", "Meylan, Les Jaillières"],
["SEM:GENJAVAUX", "Eybens, Les Javaux"],
["SEM:GENJBRUANT", "Vaulnaveys-le-Haut, Ecole Jules Bruant"],
["SEM:GENJEANNARC", "Grenoble, Jeanne d'Arc"],
["SEM:GENJEANPREV", "Fontaine, Jean Prévost"],
["SEM:GENJFLANDRI", "Meylan, Jules Flandrin"],
["SEM:GENJRACINE", "Grenoble, Jean Racine"],
["SEM:GENJULESGUE", "Fontaine, Jules Guesde"],
["SEM:GENJULESREY", "La Tronche, Jules Rey"],
["SEM:GENKARBEN", "Saint-Égrève, Karben"],
["SEM:GENKARLMARX", "Fontaine, Karl Marx"],
["SEM:GENLABAUME", "Seyssins, La Baume"],
["SEM:GENLACHAL", "Saint-Martin-le-Vinoux, Lachal"],
["SEM:GENLACHARRI", "Le Gua, La Charrière"],
["SEM:GENLACHENAI", "Venon, La Chênaie"],
["SEM:GENLACOMBE", "Gières, La Combe"],
["SEM:GENLACUCHE", "Veurey-Voroize, La Cuche"],
["SEM:GENLAFAURIE", "Venon, La Faurie"],
["SEM:GENLAFOY", "Meylan, La Foy"],
["SEM:GENLAGAY", "Bresson,  Bresson Lagay"],
["SEM:GENLAGNEAU", "Seyssins, L'Agneau"],
["SEM:GENLAGOMMA", "Saint-Martin-le-Vinoux, Le Gomma"],
["SEM:GENLALUIRE", "Le Pont-de-Claix, Gendarmerie"],
["SEM:GENLALUNE", "Seyssins, Rue de la Lune"],
["SEM:GENLAMELLE", "Champ-sur-Drac, La Melle"],
["SEM:GENLAMONTA", "Saint-Égrève, La Monta"],
["SEM:GENLAMURAIL", "Seyssinet-Pariset, Murailles"],
["SEM:GENLANGEVIN", "Échirolles, Paul Langevin"],
["SEM:GENLAPIERRE", "Le Gua, La Pierre"],
["SEM:GENLAPLAINE", "Seyssinet-Pariset, La Plaine"],
["SEM:GENLAPOYA", "Fontaine, La Poya"],
["SEM:GENLARIVO", "Mont-Saint-Martin, La Rivoire"],
["SEM:GENLARIVOIR", "Saint-Martin-le-Vinoux, La Rivoire"],
["SEM:GENLASERRAL", "Venon, La Serralière"],
["SEM:GENLASURE", "Fontaine, La Sure"],
["SEM:GENLATUILE", "Vaulnaveys-le-Haut, La Tuilerie"],
["SEM:GENLAVALONE", "Vif, La Valonne"],
["SEM:GENLAVILLE", "Venon, La Ville"],
["SEM:GENLEBOURG", "Eybens, Le Bourg"],
["SEM:GENLEBRET", "Meylan, Le Brêt"],
["SEM:GENLECELLIE", "Seyssins, Clinique du Dauphiné"],
["SEM:GENLECHAMAN", "Gières, Le Chamandier"],
["SEM:GENLECHAPON", "Venon, Le Chapon"],
["SEM:GENLECHENIL", "Venon, Le Chenil"],
["SEM:GENLECHERES", "Meylan, Les Léchères"],
["SEM:GENLECOMB", "Seyssinet-Pariset, Les Combes"],
["SEM:GENLECRET", "Eybens, Le Crêt"],
["SEM:GENLECRETS", "Sarcenas, Le Crêt"],
["SEM:GENLEGATINE", "Saint-Martin-le-Vinoux, Gatinet"],
["SEM:GENLEGORGET", "La Tronche, Le Gorget"],
["SEM:GENLEGOUILL", "Le Sappey-en-Chartreuse, Le Gouillat"],
["SEM:GENLEGUA", "Sassenage, Le Gua"],
["SEM:GENLEGUAMAI", "Le Gua, Le Gua Mairie"],
["SEM:GENLEJAPIN", "Gières, Le Japin"],
["SEM:GENLEMARAIS", "Saint-Martin-d'Hères, Le Marais"],
["SEM:GENLEMASGAC", "Saint-Martin-le-Vinoux, Mas Caché"],
["SEM:GENLENCLOS", "Brié-et-Angonnes, L'Enclos"],
["SEM:GENLEONJOUH", "Grenoble, Léon Jouhaux"],
["SEM:GENLEPARL", "Seyssins, Le Parlement"],
["SEM:GENLEPERROU", "Venon, Le Perroud"],
["SEM:GENLEPLATR", "Jarrie, Le Plâtre"],
["SEM:GENLEPLATRE", "Vaulnaveys-le-Bas, Chemin des Cottes"],
["SEM:GENLEPRIOU", "Seyssins, Le Priou"],
["SEM:GENLEREFUGE", "Vif, Le Refuge"],
["SEM:GENLEREYNET", "Venon, Le Reynet"],
["SEM:GENLERIF", "Vif, Le Rif"],
["SEM:GENLERONZA", "La Tronche, Le Rozan"],
["SEM:GENLESALLAS", "Vizille, Les Allas"],
["SEM:GENLESBAINS", "Grenoble, Suzanne Noël - Les Bains"],
["SEM:GENLESCOMBE", "Saint-Martin-le-Vinoux, Les Combes"],
["SEM:GENLESCOTES", "Seyssins, Les Côtes"],
["SEM:GENLESESSAR", "Grenoble, Les Essarts"],
["SEM:GENLESFAURE", "Le Gua, Les Faures"],
["SEM:GENLESFAUVE", "Saint-Martin-le-Vinoux, Les Fauvettes"],
["SEM:GENLESFORGE", "Vizille, Les Forges"],
["SEM:GENLESILES", "Seyssinet-Pariset, Les Iles"],
["SEM:GENLESPIES", "Sassenage, Les Pies"],
["SEM:GENLETOILE", "Le Pont-de-Claix, L'Etoile"],
["SEM:GENLEVERNAY", "Miribel-Lanchâtre, Le Vernay"],
["SEM:GENLEVETIER", "Saint-Martin-le-Vinoux, Levetière"],
["SEM:GENLHERMITA", "Saint-Martin-le-Vinoux, L'Hermitage"],
["SEM:GENLMICHEL", "Grenoble, Louise Michel"],
["SEM:GENLOUISJOU", "Grenoble, Louis Jouvet"],
["SEM:GENLTE", "Vizille, Vizille Lycée"],
["SEM:GENLYCBACHA", "Meylan, Lycée du Grésivaudan - Bachais"],
["SEM:GENLYCGRESI", "Meylan, Lycée du Grésivaudan"],
["SEM:GENLYSROUGE", "Grenoble, Lys Rouge"],
["SEM:GENMADELEIN", "Grenoble, Madeleine"],
["SEM:GENMAICULTU", "Grenoble, MC2: Maison de la Culture"],
["SEM:GENMAINNATI", "Grenoble, Marché d'Intérêt National"],
["SEM:GENMAIRIECO", "Corenc, Mairie-Condamine"],
["SEM:GENMAIRIESM", "Saint-Martin-le-Vinoux, Hôtel de Ville"],
["SEM:GENMAISANCI", "Grenoble, Maison des Anciens"],
["SEM:GENMAISNEUV", "Eybens, Maisons Neuves"],
["SEM:GENMAISON", "Vaulnaveys-le-Bas, Maison Blanche"],
["SEM:GENMAISONCO", "Saint-Martin-d'Hères, Maison Communale"],
["SEM:GENMAISONNA", "Fontaine, Louis Maisonnat"],
["SEM:GENMALACHER", "Meylan, Malacher"],
["SEM:GENMALADIER", "Sassenage, Maladière"],
["SEM:GENMALHERBE", "Grenoble, Malherbe"],
["SEM:GENMALHIVER", "Claix, Malhivert"],
["SEM:GENMALISSOL", "Varces-Allières-et-Risset, Malissolles"],
["SEM:GENMALLIFAU", "Grenoble, Mallifaud"],
["SEM:GENMARAT", "Fontaine, Marat"],
["SEM:GENMARCEAU", "Grenoble, Marceau - Jardin des Vallons"],
["SEM:GENMARCHAND", "Vaulnaveys-le-Haut, Marchandises"],
["SEM:GENMARCSANG", "Seyssins, Marc Sangnier"],
["SEM:GENMARESIST", "Grenoble, Martyrs - Résistance"],
["SEM:GENMARIANNE", "Le Pont-de-Claix, Marianne"],
["SEM:GENMARIECUR", "Échirolles, Marie Curie"],
["SEM:GENMARITELL", "Bresson, La Maritelle"],
["SEM:GENMARRONNI", "Veurey-Voroize, Les Marronniers"],
["SEM:GENMASDESIL", "Seyssins, Mas des Iles"],
["SEM:GENMASGARNI", "Vif, Mas Garni"],
["SEM:GENMASSEGU", "Vif, Le Masségu"],
["SEM:GENMASSENET", "Grenoble, Massenet"],
["SEM:GENMAUPA", "Saint-Martin-d'Uriage, Maupas"],
["SEM:GENMAUPERTJ", "Jarrie, Maupertuis"],
["SEM:GENMAUPERTU", "Meylan, Maupertuis"],
["SEM:GENMAYENCIN", "Gières, Mayencin - Champ Roman"],
["SEM:GENMEINGET", "Saint-Paul-de-Varces, Le Meinget"],
["SEM:GENMETRA", "Brié-et-Angonnes, Les Métraux"],
["SEM:GENMEYLMAIR", "Meylan, Meylan Mairie"],
["SEM:GENMICHALLO", "La Tronche, Hôpital Michallon - Grésivaudan"],
["SEM:GENMIRIBEL", "Miribel-Lanchâtre, Miribel"],
["SEM:GENMOLLARD", "Corenc, Rochasson"],
["SEM:GENMOLLARDP", "Sassenage, Mollard - Pichon"],
["SEM:GENMOLLARSA", "Le Sappey-en-Chartreuse, Les Jonquilles"],
["SEM:GENMONMOUSS", "Échirolles, Monmousseau"],
["SEM:GENMONTCHAV", "Montchaboud, Montchaboud Le Village"],
["SEM:GENMONTFLEU", "Corenc, Montfleury"],
["SEM:GENMONTLIVE", "Meylan, Montlivet"],
["SEM:GENMONTQUAI", "Quaix-en-Chartreuse, Mont-Quaix"],
["SEM:GENMONUMENT", "Corenc, Monument"],
["SEM:GENMORTES", "Domène, Les Mortes"],
["SEM:GENMOUCHERO", "Claix, Moucherotte"],
["SEM:GENMOUNIER", "Grenoble, Mounier"],
["SEM:GENMOUTONNE", "Saint-Égrève, Moutonnées"],
["SEM:GENMURET", "Saint-Égrève, Muret"],
["SEM:GENMURIERS", "Meylan, Les Mûriers"],
["SEM:GENMUSEEDAU", "Grenoble, Musée Dauphinois"],
["SEM:GENMUSGEOCH", "Échirolles, Musée Géo Charles"],
["SEM:GENMUSHEBER", "La Tronche, Musée Hébert"],
["SEM:GENMUTUALIT", "Grenoble, Mutualité"],
["SEM:GENNAMIERE", "Mont-Saint-Martin, Chemin de Namière"],
["SEM:GENNARBONNE", "Saint-Martin-le-Vinoux, Narbonne"],
["SEM:GENNAVIS", "Échirolles, Navis"],
["SEM:GENNERON", "Saint-Martin-le-Vinoux, Néron"],
["SEM:GENNEYRBELL", "Saint-Martin-d'Hères, Neyrpic - Belledonne"],
["SEM:GENNODAMLAC", "Varces-Allières-et-Risset, Notre-Dame de Lachal"],
["SEM:GENNORBSEGA", "Meylan, Norbert Ségard"],
["SEM:GENNOTREDAM", "Grenoble, Notre-Dame - Musée"],
["SEM:GENNOYARBAS", "Noyarey, Bascule"],
["SEM:GENNOYARSTJ", "Noyarey, Saint-Jean"],
["SEM:GENNOYVILLA", "Noyarey, Noyarey Village"],
["SEM:GENODYSSEE", "Eybens, Odyssée"],
["SEM:GENOISEAUX", "Corenc, Les Oiseaux"],
["SEM:GENORATOIRE", "Domène, L'Oratoire"],
["SEM:GENORIEL", "Varces-Allières-et-Risset, L'Oriel"],
["SEM:GENOVALIE", "Sassenage, L'Ovalie"],
["SEM:GENPABLONER", "Saint-Martin-d'Hères, Pablo Neruda"],
["SEM:GENPABLOPIC", "Échirolles, Collège Pablo Picasso"],
["SEM:GENPAJON", "Corenc, Charles Pajon"],
["SEM:GENPALAQUIT", "Sarcenas, Col de Palaquit"],
["SEM:GENPALJUSTI", "Grenoble, Palais de Justice - Gare"],
["SEM:GENPAMPRES", "Claix, Les Pampres"],
["SEM:GENPARCBICH", "Noyarey, Parc des Biches"],
["SEM:GENPARCS", "Sassenage, Les Parcs"],
["SEM:GENPARISE", "Seyssinet-Pariset, Pariset"],
["SEM:GENPASCAL", "La Tronche, Pascal"],
["SEM:GENPAULCOCA", "Grenoble, Paul Cocat"],
["GENPAULELUA", "Saint-Martin-d'Hères, Paul Eluard"],
["SEM:GENPAVILLON", "Varces-Allières-et-Risset, Pavillon"],
["SEM:GENPCLAUDEL", "Grenoble, Paul Claudel"],
["SEM:GENPEAGEDEV", "Vizille, Le Péage"],
["SEM:GENPEIFFEND", "Saint-Martin-d'Uriage, Les Peiffendes"],
["SEM:GENPELISIER", "Varces-Allières-et-Risset, Pélissière"],
["SEM:GENPELLOUTI", "Échirolles, Fernand Pelloutier"],
["SEM:GENPERCEVAL", "Seyssinet-Pariset, Percevalière"],
["SEM:GENPERIBROS", "Saint-Martin-d'Hères, Péri - Brossolette"],
["SEM:GENPERIERES", "Veurey-Voroize, Perrières"],
["SEM:GENPEROUSES", "Claix, Les Pérouses"],
["SEM:GENPERRIERE", "Gières, La Perrière"],
["SEM:GENPETIBRIO", "Vif, Le Petit Brion"],
["SEM:GENPFMITTER", "Seyssins, Parc François Mitterrand"],
["SEM:GENPHEROULT", "Échirolles, Paul Héroult"],
["SEM:GENPIEDGIER", "Gières, Pied de Gières"],
["SEM:GENPIERCOUR", "Saint-Martin-d'Hères, Pierre Courtade"],
["SEM:GENPIERRELO", "Saint-Martin-d'Hères, Pierre Loti"],
["SEM:GENPIERSEMA", "Saint-Martin-d'Hères, Pierre Sémard"],
["SEM:GENPINEA", "Saint-Égrève, La Pinéa - St Robert"],
["SEM:GENPISBUCLO", "Meylan, Piscine des Buclos"],
["SEM:GENPLACA", "Champagnier, Place du Laca"],
["SEM:GENPLACECYM", "Grenoble, Place Cymaise"],
["SEM:GENPLACEQUA", "Quaix-en-Chartreuse, Quaix en Chartreuse Place"],
["SEM:GENPLACESAP", "Le Sappey-en-Chartreuse, Le Sappey en Ch. Place"],
["SEM:GENPLACEVIL", "Seyssins, Seyssins Village"],
["SEM:GENPLACMARC", "Fontaine, Place du Marché Cachin"],
["SEM:GENPLAINE", "Vif, La Plaine"],
["SEM:GENPLAINEDS", "Gières, Plaine des Sports"],
["SEM:GENPLAINEFL", "Meylan, Plaine Fleurie"],
["SEM:GENPLALOUIS", "Meylan, Place de la Louisiane"],
["SEM:GENPLANF", "Proveysieux, Planfay Bas"],
["SEM:GENPLANFAY", "Proveysieux, Planfay Haut"],
["SEM:GENPLATANES", "Varces-Allières-et-Risset, Les Platanes"],
["SEM:GENPLGEANTS", "Grenoble, Les Géants"],
["SEM:GENPLIBERAT", "Sassenage, Place de la Libération"],
["SEM:GENPLREPUBL", "Gières, Place de la République"],
["SEM:GENPOLESUD", "Grenoble, Polesud - Alpexpo"],
["SEM:GENPOLOTTI", "Échirolles, Antoine Polotti"],
["SEM:GENPOMAR", "Proveysieux, Pomarey Bas"],
["SEM:GENPOMAREY", "Proveysieux, Pomarey"],
["SEM:GENPOMMERAI", "Varces-Allières-et-Risset, La Pommeraie"],
["SEM:GENPOMPIDOU", "Claix, Pompidou"],
["SEM:GENPONSARD", "Grenoble, Ponsard"],
["SEM:GENPONTCN", "Champ-sur-Drac, Pont de Champ"],
["SEM:GENPONTDEV", "Gières, Pont de Venon"],
["SEM:GENPONTGENE", "Vif, Le Pont de Genevrey"],
["SEM:GENPONTMAS", "Vizille, Le Pont du Mas"],
["SEM:GENPORTAILR", "Saint-Martin-d'Hères, Portail Rouge"],
["SEM:GENPORTGRES", "Saint-Martin-d'Hères, Porte du Grésivaudan"],
["SEM:GENPOSTE", "Claix, Poste"],
["SEM:GENPOTIE", "Saint-Martin-d'Hères, Potié"],
["SEM:GENPOULAT", "Saint-Paul-de-Varces, Le Poulat"],
["SEM:GENPRAPARIS", "Sassenage, Praparis Usine"],
["SEM:GENPRAPAROS", "Noyarey, Praparis - Les Roses"],
["SEM:GENPREAUCR", "Eybens, Pré au crêt"],
["SEM:GENPRECATLA", "Meylan, Pré Catlan"],
["SEM:GENPREDEAU", "Montbonnot-Saint-Martin, Pré de l'Eau"],
["SEM:GENPREDIEU", "Saint-Égrève, Fiancey - Prédieu"],
["SEM:GENPREFLEUR", "Sassenage, Pré Fleury"],
["SEM:GENPRELENFR", "Le Gua, Prélenfrey Eglise"],
["SEM:GENPREMILL", "Montbonnot-Saint-Martin, Pré Millet"],
["SEM:GENPREMOL", "Poisat, Prémol"],
["SEM:GENPRENOUVE", "Seyssins, Pré Nouvel"],
["SEM:GENPREORME", "Varces-Allières-et-Risset, Pré de l'Orme"],
["SEM:GENPRESQUIL", "Grenoble, Oxford"],
["SEM:GENPRIEURE", "Domène, Le Prieuré"],
["SEM:GENPRISME", "Seyssins, Le Prisme"],
["SEM:GENPROMOSOC", "Saint-Martin-d'Hères, Promotion Sociale"],
["SEM:GENPROVIDEN", "Corenc, Providence"],
["SEM:GENPTCHATEL", "Veurey-Voroize, Petit Châtelard"],
["SEM:GENPTCLXMAI", "Le Pont-de-Claix, Pont-de-Claix Mairie"],
["SEM:GENPTROUGE", "Claix, Pont Rouge"],
["SEM:GENPTTRONCH", "La Tronche, Petite Tronche"],
["SEM:GENPTVENCE", "Saint-Égrève, Pont de Vence"],
["SEM:GENPUIS", "Venon, Les Puis"],
["SEM:GENQUINZAIN", "Échirolles, Quinzaine"],
["SEM:GENRABOT", "Grenoble, Le Rabot"],
["SEM:GENRAFOUR", "Fontanil-Cornillon, Rafour"],
["SEM:GENRAMPE", "Échirolles, La Rampe - Centre-Ville"],
["SEM:GENRAYCHANA", "Grenoble, Raymond Chanas"],
["SEM:GENRENECASS", "Domène, René Cassin"],
["SEM:GENREPLAT", "Brié-et-Angonnes, Le Replat"],
["SEM:GENREPOSOIR", "Saint-Martin-le-Vinoux, Le Reposoir"],
["SEM:GENREVIREE", "Meylan, La Revirée"],
["SEM:GENREVIREES", "Meylan, Revirée - Sayettes"],
["SEM:GENRHINDANU", "Grenoble, Rosa Parks"],
["SEM:GENRIGAU", "Proveysieux, Garcinière"],
["SEM:GENRIPAILLE", "Saint-Martin-le-Vinoux, Ripaillère"],
["SEM:GENRISSET", "Varces-Allières-et-Risset, Risset"],
["SEM:GENRIVETS", "Murianette, Les Rivets"],
["SEM:GENRIVOIRE", "Sassenage, Rivoire de la Dame"],
["SEM:GENROBESPIE", "Poisat, Robespierre"],
["SEM:GENROCHEFOR", "Varces-Allières-et-Risset, Le Rochefort"],
["SEM:GENROCHEPLA", "Saint-Martin-d'Hères, Rocheplane"],
["SEM:GENROCHEPLE", "Saint-Égrève, Rochepleine"],
["SEM:GENROCHERES", "Saint-Égrève, Rocher d'Escalade"],
["SEM:GENROLLANDI", "Sassenage, La Rollandière"],
["SEM:GENROMANCHE", "Champ-sur-Drac, Espace Navarre"],
["SEM:GENRONDEAU", "Grenoble, Marielle Franco - Le Rondeau"],
["SEM:GENRONDEURO", "Varces-Allières-et-Risset, Rond-Point de l'Europe"],
["SEM:GENRONZY", "Claix, La Ronzy"],
["SEM:GENROSERAIE", "Gières, Roseraie"],
["SEM:GENROSES", "Claix, Les Roses"],
["SEM:GENROSSETS", "Le Gua, Les Rossets"],
["SEM:GENROUDIER", "Quaix-en-Chartreuse, Roudier"],
["SEM:GENROUSTEGR", "Quaix-en-Chartreuse, Route de Saint-Egrève"],
["SEM:GENROZATIER", "Varces-Allières-et-Risset, Rozatière"],
["SEM:GENRUEALPES", "Fontaine, Rue des Alpes"],
["SEM:GENRUEPASTE", "Fontaine, Rue Pasteur"],
["SEM:GENRUIRES", "Eybens, Les Ruires-Boétie"],
["SEM:GENRUISSET", "Noyarey, Le Ruisset"],
["SEM:GENSABLONS", "La Tronche, Sablons"],
["SEM:GENSACRISTI", "Vif, Rue de la Sacristie"],
["SEM:GENSAILLANT", "Le Gua, Les Saillants"],
["SEM:GENSAINTEYN", "Le Sappey-en-Chartreuse, Saint-Eynard"],
["SEM:GENSAINTMIC", "Claix, Saint-Michel"],
["SEM:GENSALENGRO", "Grenoble, Salengro"],
["SEM:GENSALLEZOL", "Champ-sur-Drac, Zola - Mairie"],
["SEM:GENSAMMARIN", "Saint-Égrève, San Marino - Barrage"],
["SEM:GENSARCENA", "Sarcenas, Sarcenas Le Village"],
["SEM:GENSARCROZ", "Sarcenas, Pont du Croz"],
["SEM:GENSAULES", "Eybens, Les Saules"],
["SEM:GENSAVOY", "Proveysieux, Savoyardière"],
["SEM:GENSEYHDV", "Seyssinet-Pariset, Seyssinet-Pariset Hôtel de Ville"],
["SEM:GENSEYSROND", "Seyssins, Seyssins Rondeau"],
["SEM:GENSEYSVILL", "Seyssinet-Pariset, Seyssins Village"],
["SEM:GENSEYVILLA", "Seyssins, Seyssins Village"],
["SEM:GENSIMIA", "Jarrie, Les Simianes"],
["SEM:GENSMHVILLA", "Saint-Martin-d'Hères, Saint-Martin-d'Hères Village"],
["SEM:GENSMVINOUX", "Saint-Martin-le-Vinoux, Place du Village"],
["SEM:GENSNETVILA", "Seyssinet-Pariset, Seyssinet Village"],
["SEM:GENSONNANT", "Gières, Le Sonnant"],
["SEM:GENSOUSFRET", "Quaix-en-Chartreuse, Sous La Frette"],
["SEM:GENSOUSPERO", "Venon, Sous-Perroud"],
["SEM:GENSOUVE", "Brié-et-Angonnes, Souveyron"],
["SEM:GENSOUVEVI", "Brié-et-Angonnes, Le Coin"],
["SEM:GENSPAULMAI", "Saint-Paul-de-Varces, Place"],
["SEM:GENSTADE", "Échirolles, Stade"],
["SEM:GENSTADEPER", "Champ-sur-Drac, Léo Lagrange"],
["SEM:GENSTADLESD", "Grenoble, Stade Lesdiguières"],
["SEM:GENSTALALLI", "Grenoble, Stalingrad-Alliés"],
["SEM:GENSTAUGUST", "Grenoble, Saint-Augustin"],
["SEM:GENSTBARTHE", "Le Gua, Saint-Barthélémy"],
["SEM:GENSTBRUNNC", "Grenoble, Saint-Bruno"],
["SEM:GENSTBRUNO", "Grenoble, Saint-Bruno"],
["SEM:GENSTEANGE", "Varces-Allières-et-Risset, Saint-Ange"],
["SEM:GENSTECLAIR", "Grenoble, Sainte-Claire - Les Halles"],
["SEM:GENSTEGVGAR", "Saint-Égrève, Saint Egrève Gare"],
["SEM:GENSTEND", "Varces-Allières-et-Risset, Stendhal"],
["SEM:GENSTEYNARD", "Fontaine, Saint-Eynard"],
["SEM:GENSTGCOMMI", "Saint-Georges-de-Commiers, St-G.-de-Commiers Gare"],
["SEM:GENSTGERMAI", "La Tronche, Saint-Germain"],
["SEM:GENSTJBOSCO", "Meylan, Saint-Jean Bosco"],
["SEM:GENSTLAUREN", "Grenoble, Saint-Laurent"],
["SEM:GENSTMARTIN", "Saint-Martin-d'Uriage, Route de Saint Martin"],
["SEM:GENSTMURY", "Meylan, Saint-Mury"],
["SEM:GENSTROCH", "Grenoble, Saint-Roch"],
["SEM:GENSTVICTOR", "Meylan, Saint-Victor"],
["SEM:GENSUDGALAX", "Échirolles, Sud Galaxie"],
["SEM:GENSURIEUX", "Échirolles, Surieux"],
["SEM:GENTAILLEES", "Saint-Martin-d'Hères, Les Taillées - Universités"],
["SEM:GENTAILLIS", "Claix, Les Taillis"],
["SEM:GENTAVER", "Brié-et-Angonnes, Tavernolles"],
["SEM:GENTEISSEIR", "Grenoble, Teisseire"],
["SEM:GENTELEBAS", "Grenoble, Téléphérique"],
["SEM:GENTERRATS", "Gières, Les Terrats"],
["SEM:GENTERRAY", "Meylan, Lionel Terray"],
["SEM:GENTHEVE", "Jarrie, Les Thévenets"],
["SEM:GENTRAVERS", "Vaulnaveys-le-Bas, Les Travers"],
["SEM:GENTREFFORI", "Sassenage, Trefforine"],
["SEM:GENTREILLE", "Meylan, La Treille"],
["SEM:GENTRONCHOP", "Grenoble, La Tronche Hôpital"],
["SEM:GENTUILERIE", "Seyssins, Tuilerie"],
["SEM:GENURIAGE", "Saint-Martin-d'Uriage, Uriage Gare"],
["SEM:GENURIOL", "Vif, Uriol"],
["SEM:GENUSINENOR", "Vif, L'Usine Nord"],
["SEM:GENVALALLIE", "Claix, Val d'Allières"],
["SEM:GENVALEYBEN", "Eybens, Val d'Eybens"],
["SEM:GENVALLCATA", "Grenoble, Vallier - Catane"],
["SEM:GENVALLIBE", "Grenoble, Vallier - Libération"],
["SEM:GENVALMY", "Grenoble, Flandrin - Valmy"],
["SEM:GENVARCESRE", "Varces-Allières-et-Risset, République"],
["SEM:GENVASSIEUX", "Échirolles, Vassieux"],
["SEM:GENVAULBAS", "Vaulnaveys-le-Bas, Vaulnaveys-Le-Bas Le Village"],
["SEM:GENVAULHAUT", "Vaulnaveys-le-Haut, Vaulnaveys-Le-Haut Le Village"],
["SEM:GENVENARIA", "Vizille, Vénaria"],
["SEM:GENVENCEECO", "Saint-Égrève, Vence EcoParc"],
["SEM:GENVENONMAI", "Venon, Venon Mairie"],
["SEM:GENVERCORS", "La Tronche, Vercors"],
["SEM:GENVERDERET", "Eybens, Le Verderet"],
["SEM:GENVERDUN", "Grenoble, Verdun - Préfecture"],
["SEM:GENVERLAINE", "Grenoble, Verlaine"],
["SEM:GENVERNES", "Domène, Les Vernes"],
["SEM:GENVERNET", "Jarrie, Le Vernet Croix"],
["SEM:GENVERT", "Claix, Vert Sapin"],
["SEM:GENVEUREYEG", "Veurey-Voroize, Eglise"],
["SEM:GENVEUREYMA", "Veurey-Voroize, Mairie"],
["SEM:GENVEUREYRI", "Veurey-Voroize, La Rive"],
["SEM:GENVEYRET", "Grenoble, Veyret"],
["SEM:GENVICTHUGO", "Grenoble, Victor Hugo"],
["SEM:GENVIEUXDON", "Sassenage, Vieux donjon"],
["SEM:GENVIFGARE", "Vif, Vif Gare"],
["SEM:GENVIFGEND", "Vif, Rivalta"],
["SEM:GENVIFMAIRI", "Vif, Vif Mairie"],
["SEM:GENVIGNATE", "Gières, Vignate"],
["SEM:GENVIGNES", "Bresson, Les Vignes"],
["SEM:GENVIGNY", "Grenoble, Vigny"],
["SEM:GENVILLAGE", "Échirolles, Le Village"],
["SEM:GENVILLOLYM", "Grenoble, Village Olympique"],
["SEM:GENVISANCOU", "Saint-Égrève, Visancourt"],
["SEM:GENVOHRIGEN", "Vizille, Parc Vöhringen"],
["SEM:GENXAVJOUVI", "Grenoble, Xavier Jouvin"],
["SEM:GENZASPEYRE", "Vif, Z.A. des Speyres"],
["SEM:GENZELLAMEL", "Saint-Martin-d'Hères, Zella Mehlis"],
["SEM:GENZILES", "Le Pont-de-Claix, ZI des Iles"],

//Ârrets du grésivaudan

["GSV:GEN12420", "Chamrousse, LE RECOIN VFD"],
["GSV:GEN13045", "Revel, REVEL ECOLES"],
["GSV:GEN13050", "Revel, LA FONTAINE"],
["GSV:GEN13052", "Revel, LA SARRAZINE"],
["GSV:GEN13054", "Domène, DOMENE MAIRIE"],
["GSV:GEN13056", "Domène, DOMENE LES ARNAUDS"],
["GSV:GEN13064", "Revel, REVEL LA BOURGEAT"],
["GSV:GEN13074", "Le Versoud, LA CHARRIERE"],
["GSV:GEN13076", "Le Versoud, ETAPES-MALVAISIN"],
["GSV:GEN13078", "Domène, LES VERNES"],
["GSV:GEN13082", "Domène, LE PRIEURE"],
["GSV:GEN13088", "Montbonnot-Saint-Martin, BAUDONNIERE"],
["GSV:GEN13093", "Saint-Jean-le-Vieux, ST JEAN LE VIEUX LA MONTA"],
["GSV:GEN13100", "Domène, RENE CASSIN"],
["GSV:GEN13108", "La Combe-de-Lancey, LE MAS JULIEN"],
["GSV:GEN13113", "Revel, LE GEYMOND"],
["GSV:GEN13116", "Saint-Jean-le-Vieux, LE RIF"],
["GSV:GEN13119", "Saint-Jean-le-Vieux, ST JEAN LE VIEUX LE MOLLARD"],
["GSV:GEN13121", "Revel, LES JACQUETS"],
["GSV:GEN13122", "Revel, CHARRIERES NEUVES"],
["GSV:GEN13125", "Revel, LES FAURES"],
["GSV:GEN13126", "Revel, REVEL LE MONT"],
["GSV:GEN13129", "Revel, LES ROUSSETS"],
["GSV:GEN13131", "Saint-Jean-le-Vieux, ST JEAN LE VIEUX EGLISE"],
["GSV:GEN13133", "Saint-Jean-le-Vieux, LE NAYSORD"],
["GSV:GEN13137", "Saint-Jean-le-Vieux, LE COUVAT"],
["GSV:GEN13140", "Saint-Jean-le-Vieux, L ISLE"],
["GSV:GEN13570", "Montbonnot-Saint-Martin, PRE MILLET"],
["GSV:GEN13586", "Montbonnot-Saint-Martin, INRIA"],
["GSV:GEN13594", "Saint-Ismier, ST ISMIER LA BATIE"],
["GSV:GEN13598", "Saint-Ismier, LES MILLETS"],
["GSV:GEN13604", "Saint-Ismier, LES VARCIAUX"],
["GSV:GEN13606", "Saint-Ismier, BOUFFIERE"],
["GSV:GEN13608", "Saint-Ismier, LE MANIVAL"],
["GSV:GEN13614", "Saint-Ismier, LE MEMORIAL"],
["GSV:GEN13616", "Saint-Ismier, GEYDAN GENISSIEUX"],
["GSV:GEN13618", "Saint-Ismier, CHEMIN DES BOUTS"],
["GSV:GEN13626", "Saint-Ismier, LOT. LABIS"],
["GSV:GEN13628", "Saint-Ismier, LE MOULIN"],
["GSV:GEN13633", "Saint-Ismier, COLLEGE DU GRESIVAUDAN - PARKING"],
["GSV:GEN13634", "Saint-Nazaire-les-Eymes, LES EYMES RD 1090"],
["GSV:GEN13636", "Saint-Nazaire-les-Eymes, LES RATZ"],
["GSV:GEN13638", "Saint-Nazaire-les-Eymes, LE PIAT"],
["GSV:GEN13642", "Le Versoud, COTE BELLE"],
["GSV:GEN13644", "Saint-Ismier, LE FANGEAT"],
["GSV:GEN13650", "Saint-Ismier, LES MARECHAUX"],
["GSV:GEN13652", "Saint-Nazaire-les-Eymes, ST NAZAIRE LES EYMES GARE"],
["GSV:GEN13658", "Saint-Nazaire-les-Eymes, LE LAVORS"],
["GSV:GEN13660", "Saint-Ismier, CHEMIN QUARTALLEES"],
["GSV:GEN13662", "Le Versoud, LA PLACE"],
["GSV:GEN13664", "Le Versoud, BELLE PLAINE"],
["GSV:GEN13668", "Saint-Ismier, ST ISMIER LES PLANTEES"],
["GSV:GEN13674", "Saint-Ismier, LYCEE HORTICOLE"],
["GSV:GEN13678", "Montbonnot-Saint-Martin, PRE DE L EAU"],
["GSV:GEN13682", "La Combe-de-Lancey, LA COMBE DE LANCEY LE VILLARD"],
["GSV:GEN13686", "La Combe-de-Lancey, LE PETIT CHATEAU"],
["GSV:GEN13688", "La Combe-de-Lancey, LE MAS LA RUE"],
["GSV:GEN13690", "La Combe-de-Lancey, LE MAS MONTACOL"],
["GSV:GEN13692", "Laval, LE BONNAT"],
["GSV:GEN13694", "Laval, LAVAL MAIRIE"],
["GSV:GEN13698", "La Combe-de-Lancey, LA COMBE DE LANCEY LE MONT"],
["GSV:GEN13700", "La Combe-de-Lancey, LES ECHARRAS"],
["GSV:GEN13702", "La Combe-de-Lancey, VILLARD D EN BAS"],
["GSV:GEN13704", "La Combe-de-Lancey, LA COMBE LA CHAPELLE"],
["GSV:GEN13706", "La Combe-de-Lancey, LE MAS VANNIER"],
["GSV:GEN13708", "Sainte-Agnès, ECOLE DE STE AGNES"],
["GSV:GEN13710", "Sainte-Agnès, LA VILLE"],
["GSV:GEN13712", "Saint-Mury-Monteymond, LE CHOLET"],
["GSV:GEN13714", "La Combe-de-Lancey, LE MAS LARY"],
["GSV:GEN13718", "Saint-Mury-Monteymond, CARREFOUR PRELONG"],
["GSV:GEN13720", "Saint-Mury-Monteymond, ST MURY CIMETIERE"],
["GSV:GEN13722", "Villard-Bonnot, LA MADONE"],
["GSV:GEN13724", "Villard-Bonnot, VORS"],
["GSV:GEN13726", "Villard-Bonnot, VILLARD BONNOT LA MAIRIE"],
["GSV:GEN13728", "Villard-Bonnot, LA POLOGNE"],
["GSV:GEN13730", "Villard-Bonnot, EGLISE - GENDARMERIE"],
["GSV:GEN13732", "Saint-Mury-Monteymond, L EGLISE"],
["GSV:GEN13734", "Sainte-Agnès, LA FAURE"],
["GSV:GEN13736", "Froges, BRIGNOUD PLACE"],
["GSV:GEN13738", "Villard-Bonnot, LE SABOT"],
["GSV:GEN13740", "Sainte-Agnès, LE MAS N° 2"],
["GSV:GEN13742", "Sainte-Agnès, STE AGNES LE MOLLARD"],
["GSV:GEN13744", "Sainte-Agnès, MAISON D ARGOUD AU RIF"],
["GSV:GEN13746", "Villard-Bonnot, LANCEY"],
["GSV:GEN13748", "Saint-Mury-Monteymond, LA PALLUD MATERNELLE"],
["GSV:GEN13753", "Villard-Bonnot, LYCEE M. REYNOARD - PARKING"],
["GSV:GEN13754", "Villard-Bonnot, CITE DES ROSES"],
["GSV:GEN13756", "Sainte-Agnès, STE AGNES LA BOURGEAT"],
["GSV:GEN13758", "Sainte-Agnès, LE FAY"],
["GSV:GEN13762", "Sainte-Agnès, STE AGNES LA GORGE"],
["GSV:GEN13764", "Le Versoud, CITE NOUVELLE"],
["GSV:GEN13766", "Le Versoud, PONT DE PRUNEY"],
["GSV:GEN13768", "Sainte-Agnès, LES GRANDS CHAMPS"],
["GSV:GEN13770", "Villard-Bonnot, LANCEY GARE"],
["GSV:GEN13772", "Saint-Mury-Monteymond, LE BANC"],
["GSV:GEN13774", "Villard-Bonnot, LYCEE RD.523"],
["GSV:GEN13776", "Saint-Mury-Monteymond, LE MAS VIEUX"],
["GSV:GEN13778", "Saint-Mury-Monteymond, LES COCHARDS"],
["GSV:GEN13780", "Villard-Bonnot, COLLEGE BELLEDONNE"],
["GSV:GEN13782", "Villard-Bonnot, PAPETERIES"],
["GSV:GEN13786", "Laval, LA BOUTIERE"],
["GSV:GEN13788", "Laval, PRABERT"],
["GSV:GEN13790", "Laval, LAVAL LE MOLLARD"],
["GSV:GEN13792", "Laval, LE FUZIER"],
["GSV:GEN13794", "Les Adrets, PRAPOUTEL PATTE D OIE"],
["GSV:GEN13796", "Laval, LE PLANEYSSARD ECOLE"],
["GSV:GEN13798", "Les Adrets, PRAPOUTEL GENDARMERIE"],
["GSV:GEN13800", "Laval, LE CARNIVAL"],
["GSV:GEN13802", "Sainte-Agnès, LE FAY N°2"],
["GSV:GEN13804", "Les Adrets, LES GENIEVRES"],
["GSV:GEN13806", "Laval, VAUGELAS BAS"],
["GSV:GEN13808", "Sainte-Agnès, LA PERRIERE"],
["GSV:GEN13810", "Sainte-Agnès, EPINGLE LA PERRIERE"],
["GSV:GEN14188", "Crolles, LA CROIX DES AYES"],
["GSV:GEN14192", "Saint-Pancrasse, ST PANCRASSE LA MAIRIE"],
["GSV:GEN14194", "Bernin, CROIX DES VARVOUX"],
["GSV:GEN14196", "Bernin, BERNIN P.T.T."],
["GSV:GEN14198", "Bernin, VARVOUX LE BAS"],
["GSV:GEN14204", "Bernin, LES VARVOUX"],
["GSV:GEN14211", "Saint-Hilaire, LES MARGAINS"],
["GSV:GEN14212", "Bernin, LES REVOLEYS"],
["GSV:GEN14218", "Crolles, ST MICROELECTRONICS"],
["GSV:GEN14222", "Froges, ECOLE ELEMENTAIRE GUYNEMER"],
["GSV:GEN14224", "Froges, LE BOCCARD"],
["GSV:GEN14226", "Froges, PRE DU CHENE"],
["GSV:GEN14228", "Le Champ-près-Froges, LOT. LA TOUR"],
["GSV:GEN14234", "Froges, COQUILLARD"],
["GSV:GEN14236", "Le Champ-près-Froges, CHAMP PRES FROGES - LE MOLLARD"],
["GSV:GEN14250", "Crolles, RAFOUR CROIZAT"],
["GSV:GEN14253", "Froges, LANGENET"],
["GSV:GEN14254", "Le Champ-près-Froges, LE BAS"],
["GSV:GEN14256", "Le Champ-près-Froges, CHAMPALUD"],
["GSV:GEN14262", "Crolles, POMPIERS"],
["GSV:GEN14264", "Froges, CITE JARDINS"],
["GSV:GEN14269", "Froges, LES JAURES"],
["GSV:GEN14271", "Froges, LOT BALC. BELLEDONNE"],
["GSV:GEN14273", "Froges, ALLEE DES THUYAS"],
["GSV:GEN14274", "Froges, LE PLANET"],
["GSV:GEN14276", "Froges, LES BOIS"],
["GSV:GEN14279", "Froges, LE MAZARETIER"],
["GSV:GEN14280", "Froges, LES VIGNES DE PICHAT"],
["GSV:GEN14282", "Saint-Hilaire, PRE BENOIT"],
["GSV:GEN14284", "Saint-Hilaire, LES GANDINS"],
["GSV:GEN14295", "Froges, MAS PELIOUD"],
["GSV:GEN14297", "Froges, LES AYETTES"],
["GSV:GEN14300", "Les Adrets, L ENVERS"],
["GSV:GEN14302", "Les Adrets, ECOLE LES ADRETS"],
["GSV:GEN14304", "Les Adrets, ROUTE VIEUX MANEGE"],
["GSV:GEN14306", "Les Adrets, LES ALPETS"],
["GSV:GEN14312", "Les Adrets, VILLARD CHATEAU"],
["GSV:GEN14314", "Les Adrets, POUTAZ BAS"],
["GSV:GEN14316", "Les Adrets, LES AVONS"],
["GSV:GEN14318", "Les Adrets, PRES COMMUNAUX N°1"],
["GSV:GEN14320", "Les Adrets, PRES COMMUNAUX N°2"],
["GSV:GEN14322", "Les Adrets, LES FOURNELLES"],
["GSV:GEN14325", "Les Adrets, LA PITROUSE"],
["GSV:GEN14328", "Hurtières, HURTIERES LE HAUT"],
["GSV:GEN14330", "Hurtières, HURTIERES MAIRIE"],
["GSV:GEN14332", "Les Adrets, VILLARD BERNARD"],
["GSV:GEN14334", "Le Champ-près-Froges, CHAMP LE HAUT MAIRIE"],
["GSV:GEN14338", "Les Adrets, LES COMPTES"],
["GSV:GEN14340", "Froges, ROUARE"],
["GSV:GEN14344", "Hurtières, HURTIERES PLACE"],
["GSV:GEN14346", "Les Adrets, LE LANAT"],
["GSV:GEN14348", "Theys, THEYS ECOLES"],
["GSV:GEN14351", "Theys, LES AYES"],
["GSV:GEN14354", "Tencin, PRE SEC"],
["GSV:GEN14357", "Theys, ROUTE DES GAUTHIERS"],
["GSV:GEN14359", "Theys, LES GLAPIGNEUX"],
["GSV:GEN14360", "Theys, LES COMBES D EN BAS"],
["GSV:GEN14363", "Theys, LE BOURGUIGNON"],
["GSV:GEN14366", "Theys, LES BERTS"],
["GSV:GEN14369", "Theys, LES VALLINS"],
["GSV:GEN14371", "Theys, PIERRE HERSE"],
["GSV:GEN14373", "Theys, LES COMBES D EN HAUT"],
["GSV:GEN14374", "La Pierre, LA PIERRE - CARR. RD 523"],
["GSV:GEN14377", "Theys, LOUTRE"],
["GSV:GEN14379", "Theys, LA TOUR"],
["GSV:GEN14380", "Theys, LA MAISON BLANCHE"],
["GSV:GEN14382", "Les Adrets, LES FOURNACHES"],
["GSV:GEN14385", "Theys, THEYS LA ROCHE"],
["GSV:GEN14386", "Theys, GORGE D OR"],
["GSV:GEN14388", "Theys, LES ESSARTS"],
["GSV:GEN14390", "Les Adrets, LES BLETTIERES"],
["GSV:GEN14395", "Theys, GLAPIGNEUX DESSOUS"],
["GSV:GEN14397", "Les Adrets, LE PRE"],
["GSV:GEN14400", "La Ferrière, LA MARTINETTE"],
["GSV:GEN14402", "La Ferrière, FOND DE FRANCE"],
["GSV:GEN14405", "La Ferrière, LE PLEYNET"],
["GSV:GEN14406", "La Ferrière, CAMOREL"],
["GSV:GEN14408", "La Ferrière, LA FERRIERE LA CHAPELLE"],
["GSV:GEN14410", "La Ferrière, LES MILLETS C.V.O."],
["GSV:GEN14978", "La Terrasse, INSTITUT"],
["GSV:GEN14980", "Saint-Bernard, LES VIROILLES"],
["GSV:GEN14984", "Saint-Bernard, HAMEAU ST MICHEL"],
["GSV:GEN14986", "Saint-Bernard, LE PRAYER"],
["GSV:GEN14988", "Saint-Bernard, LE TERRAIL"],
["GSV:GEN14990", "Saint-Bernard, LE COMBET"],
["GSV:GEN14994", "Saint-Bernard, ST BERNARD DU TOUVET LA BATIE"],
["GSV:GEN14996", "Saint-Bernard, LES PELLOUX"],
["GSV:GEN14998", "Saint-Hilaire, LES CHATAINS"],
["GSV:GEN15000", "Saint-Hilaire, LA CROIX DES EYRAUDS"],
["GSV:GEN15008", "Saint-Bernard, LA DIAT"],
["GSV:GEN15010", "Saint-Hilaire, MAT. LES GANDINS"],
["GSV:GEN15012", "Saint-Hilaire, LES VIALS"],
["GSV:GEN15014", "Saint-Bernard, LES GUILLOTS"],
["GSV:GEN15016", "Saint-Hilaire, ECOLE DES GAUDES"],
["GSV:GEN15018", "Saint-Hilaire, LES MASSARDS"],
["GSV:GEN15022", "Le Touvet, LA FRETTE"],
["GSV:GEN15026", "La Terrasse, LACHAT"],
["GSV:GEN15029", "La Terrasse, LE BURLET"],
["GSV:GEN15031", "Le Touvet, MONTABON"],
["GSV:GEN15032", "Goncelin, GONCELIN GARE"],
["GSV:GEN15035", "Tencin, MONTGALMAND"],
["GSV:GEN15036", "Le Touvet, LA CONCHE"],
["GSV:GEN15038", "Goncelin, VILLARD BOZON"],
["GSV:GEN15042", "Theys, LE CARRET"],
["GSV:GEN15044", "Tencin, GRANDES TERRES"],
["GSV:GEN15046", "Theys, LE GRE"],
["GSV:GEN15050", "Tencin, LE CLOS DU CEDRE"],
["GSV:GEN15053", "Goncelin, COLLEGE ICARE"],
["GSV:GEN15054", "Goncelin, COLLEGE RD.523"],
["GSV:GEN15056", "Theys, LA COCHE"],
["GSV:GEN15058", "Crêts en Belledonne, LA CASSEY"],
["GSV:GEN15060", "Theys, LES VINCENTS"],
["GSV:GEN15064", "Crêts en Belledonne, LE LEVET"],
["GSV:GEN15066", "Crêts en Belledonne, LE VOLEY"],
["GSV:GEN15068", "Crêts en Belledonne, LES AMICONS"],
["GSV:GEN15070", "La Ferrière, LE CURTILLARD"],
["GSV:GEN15072", "La Ferrière, VILLAGE-ECOLES"],
["GSV:GEN15074", "La Ferrière, LE PETIT THIERVOZ"],
["GSV:GEN15076", "La Ferrière, LE GRAND THIERVOZ"],
["GSV:GEN15080", "Pinsot, LA PIAT"],
["GSV:GEN1516", "Allevard, LE DAVID"],
["GSV:GEN1517", "Allevard, LE COLLET D ALLEVARD"],
["GSV:GEN1534", "Le Cheylas, LE MERCIER RD523"],
["GSV:GEN15702", "Sainte-Marie-du-Mont, LA CHAPELLE"],
["GSV:GEN15704", "Saint-Bernard, COL DE MARCIEU"],
["GSV:GEN15706", "Sainte-Marie-du-Mont, LE VILLARD"],
["GSV:GEN15710", "Sainte-Marie-du-Mont, LA VIEILLE EGLISE"],
["GSV:GEN15712", "Saint-Bernard, LOTISSEMENT MARCIEU"],
["GSV:GEN15716", "Le Cheylas, LES MEYANNES"],
["GSV:GEN15718", "Le Cheylas, LE CHEYLAS - LA MAIRIE"],
["GSV:GEN15722", "Le Cheylas, LE CHEYLAS GARE  D.523"],
["GSV:GEN15724", "Le Cheylas, LE CHEYLAS LE MERCIER"],
["GSV:GEN15726", "Le Cheylas, LE ROMPAY"],
["GSV:GEN15728", "La FlachÃ¨re, LA FLACHERE MAIRIE"],
["GSV:GEN15732", "Crêts en Belledonne, BEAUREGARD"],
["GSV:GEN15734", "Sainte-Marie-d'Alloix, STE MARIE D ALLOIX LE VILLAGE"],
["GSV:GEN15736", "La FlachÃ¨re, LA FLACHERE ECOLE"],
["GSV:GEN15741", "Saint-Vincent-de-Mercuze, CAVE COOPERATIVE"],
["GSV:GEN15742", "Le Touvet, LA CIME"],
["GSV:GEN15744", "Le Touvet, LE SAINT JEAN"],
["GSV:GEN15748", "Le Touvet, COLLEGE LA PIERRE  AIGUILLE"],
["GSV:GEN15750", "Le Touvet, LE TOUVET GARE"],
["GSV:GEN15752", "Saint-Vincent-de-Mercuze, ST VINCENT MERCUZE LA PISCINE"],
["GSV:GEN15755", "Crêts en Belledonne, LE TRAIT"],
["GSV:GEN15756", "Crêts en Belledonne, LE CHAPELAT"],
["GSV:GEN15758", "Crêts en Belledonne, MAILLES"],
["GSV:GEN15762", "Saint-Vincent-de-Mercuze, ST VINCENT DE MERCUZE MAIRIE"],
["GSV:GEN15764", "Saint-Vincent-de-Mercuze, LE MONTALIEU"],
["GSV:GEN15766", "Le Cheylas, LES BLEUETS"],
["GSV:GEN15769", "Saint-Vincent-de-Mercuze, LA FUMAS"],
["GSV:GEN15770", "Saint-Vincent-de-Mercuze, ST VINCENT LA BRANCHY"],
["GSV:GEN15774", "Saint-Vincent-de-Mercuze, GS DOUDART DE LAGREE"],
["GSV:GEN15776", "Saint-Vincent-de-Mercuze, LOT. DE LA BARDE"],
["GSV:GEN15778", "Le Cheylas, LE CHEYLAS LE VILLARD"],
["GSV:GEN15780", "Le Touvet, TOUVET MATERNELLE"],
["GSV:GEN15782", "Saint-Vincent-de-Mercuze, RUE HAUSSEPIED"],
["GSV:GEN15784", "Le Cheylas, LE TROUILLET"],
["GSV:GEN15791", "Allevard, LES MORETS"],
["GSV:GEN15794", "Allevard, LE  DAVID"],
["GSV:GEN15804", "Allevard, HAMEAU MONTOUVRARD"],
["GSV:GEN15806", "Crêts en Belledonne, ST PIERRE ECOLES"],
["GSV:GEN15808", "Crêts en Belledonne, LE CATUS"],
["GSV:GEN15812", "Crêts en Belledonne, SAILLES LE BAS"],
["GSV:GEN15814", "Crêts en Belledonne, LE GUILLON"],
["GSV:GEN15816", "Crêts en Belledonne, LE RIGARD"],
["GSV:GEN15820", "Crêts en Belledonne, SAILLES LE HAUT"],
["GSV:GEN15822", "Crêts en Belledonne, MONTGOUTOUX"],
["GSV:GEN15824", "Crêts en Belledonne, LE CHABOUD"],
["GSV:GEN15826", "Crêts en Belledonne, GORGE NOIRE"],
["GSV:GEN15828", "Crêts en Belledonne, CRETS EN BELLEDONNE LE VILLAGE"],
["GSV:GEN15830", "Crêts en Belledonne, LE BEROUD"],
["GSV:GEN15832", "Crêts en Belledonne, LE CARIGNON"],
["GSV:GEN15834", "Crêts en Belledonne, LE FEYJOUX"],
["GSV:GEN15836", "Crêts en Belledonne, LES GRANGES"],
["GSV:GEN15842", "Crêts en Belledonne, LES COTTERIAUX"],
["GSV:GEN15844", "Le Cheylas, L ABBAYE"],
["GSV:GEN15846", "Pinsot, PINSOT LE VILLAGE"],
["GSV:GEN15850", "Pinsot, CHINFERT"],
["GSV:GEN15852", "Pinsot, HOT PIC BELLE ETOILE"],
["GSV:GEN16340", "Sainte-Marie-du-Mont, LES PRES  MAIRIE"],
["GSV:GEN16345", "Barraux, CIMETIERE"],
["GSV:GEN16347", "Barraux, HAMEAU LA CUILLER"],
["GSV:GEN16348", "Barraux, LA CORVA"],
["GSV:GEN16350", "Barraux, LE RESERVOIR"],
["GSV:GEN16352", "La Buissière, LA BERARDE"],
["GSV:GEN16354", "Barraux, LE BOISSIEU PONT"],
["GSV:GEN16357", "La Buissière, LA BUISSIERE LES GRANGES"],
["GSV:GEN16358", "La Buissière, LA BUISSIERE ECOLE"],
["GSV:GEN16360", "Barraux, BARRAUX MATERNELLE"],
["GSV:GEN16361", "Pontcharra, LYCEE P. DU TERRAIL - BREDA"],
["GSV:GEN16362", "La FlachÃ¨re, LE BOISSIEU LOT"],
["GSV:GEN16364", "Sainte-Marie-du-Mont, HAMEAU DE ST GEORGES"],
["GSV:GEN16367", "Barraux, BARRAUX EC.PRIMAIRE"],
["GSV:GEN16368", "Barraux, LE PUITS"],
["GSV:GEN16372", "Barraux, LE FAYET"],
["GSV:GEN16374", "Barraux, BARRAUX LOT. BEAUREG"],
["GSV:GEN16377", "Pontcharra, JAVEYDAN"],
["GSV:GEN16378", "Pontcharra, MALBOURGET"],
["GSV:GEN16380", "Chapareillan, ST MARCEL D EN HAUT"],
["GSV:GEN16382", "Pontcharra, COLLEGE MARCEL CHENE"],
["GSV:GEN16384", "Pontcharra, VILLARD DIDIER"],
["GSV:GEN16386", "Pontcharra, LYCEE P. DU TERRAIL"],
["GSV:GEN16388", "Barraux, BARRAUX LE VILLAGE"],
["GSV:GEN16390", "Pontcharra, PONTCHARRA GARE"],
["GSV:GEN16396", "Pontcharra, VILLARD NOIR"],
["GSV:GEN16398", "La FlachÃ¨re, LA FLACHERE GARE"],
["GSV:GEN16404", "La Buissière, LA MALADIERE"],
["GSV:GEN16410", "Allevard, PANORAMIC"],
["GSV:GEN16412", "Allevard, LE CLOSY"],
["GSV:GEN16414", "Pontcharra, PONTCHARRA LA MAIRIE"],
["GSV:GEN16419", "Pontcharra, CHALLEYS"],
["GSV:GEN16421", "Pontcharra, PAPILLARD"],
["GSV:GEN16423", "Pontcharra, LE MARAIS"],
["GSV:GEN16425", "Pontcharra, MONTAUCHER"],
["GSV:GEN16426", "Pontcharra, VILLARD NOIR LES PLANTEES"],
["GSV:GEN16428", "Pontcharra, AVENUE DU GRANIER"],
["GSV:GEN16431", "Pontcharra, LE PAPET"],
["GSV:GEN16436", "Saint-Maximin, ST MAXIMIN LA MAIRIE"],
["GSV:GEN16444", "La Chapelle-du-Bard, BEAUVOIR"],
["GSV:GEN16446", "Allevard, LA RATZ"],
["GSV:GEN16448", "Allevard, LE COLOMBIER"],
["GSV:GEN16450", "La Chapelle-du-Bard, LA CHAPELLE LA GORGE"],
["GSV:GEN16454", "La Chapelle-du-Bard, LA CHAPELLE ECOLE"],
["GSV:GEN16456", "La Chapelle-du-Bard, MONTGAREN"],
["GSV:GEN16458", "Le Moutaret, LE MOUTARET LE VILLAGE"],
["GSV:GEN16460", "Le Moutaret, FREYDON"],
["GSV:GEN16462", "Le Moutaret, LES MASURES"],
["GSV:GEN16464", "La Chapelle-du-Bard, LE BUISSON"],
["GSV:GEN16994", "Chapareillan, EC PRIVEE BELLECOUR"],
["GSV:GEN16998", "Chapareillan, CHAPAREILLAN GARE"],
["GSV:GEN17000", "Chapareillan, LES ATRUS"],
["GSV:GEN17003", "Chapareillan, COTAGNIERS"],
["GSV:GEN17004", "Chapareillan, LES GIROUDS"],
["GSV:GEN17006", "Chapareillan, LA PALUD"],
["GSV:GEN17008", "Chapareillan, L ETRAZ"],
["GSV:GEN17010", "Chapareillan, CHAPAREILLAN MAIRIE"],
["GSV:GEN17012", "Chapareillan, ST MARCEL D EN BAS"],
["GSV:GEN17014", "Chapareillan, BELLECOMBETTE"],
["GSV:GEN17017", "Chapareillan, LA MEUNIERE"],
["GSV:GEN17019", "Chapareillan, CHAPAREILLAN ECOLE"],
["GSV:GEN17020", "Chapareillan, BELLECOMBE"],
["GSV:GEN17023", "Chapareillan, LES GAILLONS"],
["GSV:GEN20030", "Saint-Bernard, ST BERNARD EGLISE"],
["GSV:GEN20055", "Saint-Ismier, LE RIVET"],
["GSV:GEN20088", "Meylan, NORBERT SEGARD"],
["GSV:GEN20090", "Meylan, BUSSEROLLES"],
["GSV:GEN20194", "La Chapelle-du-Bard, PLAN POUCET"],
["GSV:GEN20211", "Pontcharra, RESIDENCES BAYARD"],
["GSV:GEN20215", "Pontcharra, LYCEE AV DE LA GARE"],
["GSV:GEN20217", "La Buissière, CHATEAU"],
["GSV:GEN20223", "Allevard, COLLEGE FLAVIUS VAUSSENAT"],
["GSV:GEN20230", "Saint-Nazaire-les-Eymes, ST NAZAIRE LES EYMES MAIRIE"],
["GSV:GEN20231", "Saint-Nazaire-les-Eymes, TRANSFORMATEUR"],
["GSV:GEN20257", "Le Cheylas, LES CHABERTS"],
["GSV:GEN20261", "Laval, LA TAILLAT"],
["GSV:GEN20264", "Laval, LE CARNIVAL LANCELOT"],
["GSV:GEN20287", "La Chapelle-du-Bard, REVIT"],
["GSV:GEN20289", "La Chapelle-du-Bard, PONT DU BENS"],
["GSV:GEN20290", "Le Touvet, LE TOUVET GENDARMERIE"],
["GSV:GEN20294", "Les Adrets, LES AVONS 2"],
["GSV:GEN20295", "Crêts en Belledonne, PLANCHAMPS"],
["GSV:GEN20298", "Allevard, LE GLAPIGNEUX"],
["GSV:GEN20300", "Allevard, ALLEVARD LE MOLLARD"],
["GSV:GEN20302", "Allevard, LA TOUR DU TREUIL"],
["GSV:GEN20316", "La Buissière, PATTE D OIE"],
["GSV:GEN20319", "Pontcharra, ECOLE CESAR TERRIER"],
["GSV:GEN20322", "Le Cheylas, LES VIGNASSES"],
["GSV:GEN20338", "Pontcharra, LA TREILLE"],
["GSV:GEN20358", "Saint-Ismier, LE CLOS DU MARS"],
["GSV:GEN30007", "Chamrousse, LE RECOIN OT"],
["GSV:GEN30027", "Pontcharra, MEDIATHEQUE"],
["GSV:GEN30028", "Pontcharra, VILLAGE D ENTREPRISES"],
["GSV:GEN30029", "Pontcharra, PONTCHARRA PISCINE"],
["GSV:GEN30033", "Crolles, TEISSEIRE"],
["GSV:GEN30041", "Le Cheylas, LE CHEYLAS USINES"],
["GSV:GEN30044", "Le Cheylas, LE CHEYLAS ECOLES"],
["GSV:GEN30045", "Saint-Martin-d'Uriage, CHENEVARIE"],
["GSV:GEN30046", "Saint-Martin-d'Uriage, LA PEREREE"],
["GSV:GEN30047", "Saint-Martin-d'Uriage, CORPS D URIAGE"],
["GSV:GEN30049", "Saint-Martin-d'Uriage, IZARDS PATTE D'OIE"],
["GSV:GEN30051", "Saint-Martin-d'Uriage, LE PINET D URIAGE"],
["GSV:GEN30052", "Saint-Martin-d'Uriage, CARREFOUR DU REPLAT"],
["GSV:GEN30055", "Saint-Martin-d'Uriage, HAUTES VUES"],
["GSV:GEN30056", "Saint-Martin-d'Uriage, ST NIZIER D URIAGE"],
["GSV:GEN30057", "Gières, GIERES GARE"],
["GSV:GEN30067", "Montbonnot-Saint-Martin, MONTBONNOT LA PISCINE"],
["GSV:GEN30069", "Allevard, BESSEY"],
["GSV:GEN30071", "Allevard, GUILLET"],
["GSV:GEN30073", "Villard-Bonnot, GRANDE ILE"],
["GSV:GEN30076", "Montbonnot-Saint-Martin, CH DE LA CROIX VERTE"],
["GSV:GEN30077", "Montbonnot-Saint-Martin, ECOLE DES CHAVANNES"],
["GSV:GEN30086", "Allevard, MUSEE JADIS"],
["GSV:GEN30089", "Allevard, LES PANISSIERES"],
["GSV:GEN30102", "Saint-Maximin, ST MAXIMIN LA COMBE"],
["GSV:GEN30105", "Saint-Maximin, AVALLON"],
["GSV:GEN30108", "Saint-Maximin, LES BRUNS"],
["GSV:GEN30111", "Saint-Maximin, RIPPELETS"],
["GSV:GEN30114", "Saint-Maximin, BRETONNIERES"],
["GSV:GEN30117", "Allevard, LES AMOUREUX"],
["GSV:GEN30120", "Allevard, AVENUE DE SAVOIE"],
["GSV:GEN30421", "La Combe-de-Lancey, LA SCIERIE"],
["GSV:GEN4001", "Chapareillan, RUE DES NOYERS"],
["GSV:GEN40053", "Lumbin, ESAT"],
["GSV:GEN5000", "Chapareillan, ALLIBERT TREKKING"],
["GSV:GEN5013", "La Chapelle-du-Bard, LE ROZAT"],

["ST00543","Apprieu, LE RIVIER ECOLE"],
["ST00022","Bilieu, BARDONNET"],
["ST00023","Bilieu, CHANTARET"],
["ST00019","Bilieu, LES MAURES"],
["ST00021","Bilieu, PETIT BILIEU"],
["ST00020","Bilieu, ROUTE DE CHARAVINES"],
["ST00018","Bilieu, VILLAGE"],
["ST00031","Charancieu, CENTRE"],
["ST00573","Charancieu, ZA CHARANCIEU"],
["ST00577","Charavines, BERNARDIERE"],
["ST00038","Charavines, FORGES"],
["ST00042","Charavines, GARE"],
["ST00037","Charavines, GUILLERMET"],
["ST00034","Charavines, JACQUIN"],
["ST00044","Charavines, OFFICE DE TOURISME"],
["ST00043","Charavines, PAPETERIE"],
["ST00039","Charavines, PLACE DU MARCHE"],
["ST00040","Charavines, VIRAGE JANIN"],
["ST00047","Charnècles, 6 CHEMINS"],
["ST00054","Charnècles, FERME BOURDIS"],
["ST00053","Charnècles, LES RIVOIRES"],
["ST00055","Charnècles, LEZARDIERES PT"],
["ST00050","Charnècles, MAIRIE"],
["ST00049","Charnècles, PLACE"],
["ST00048","Charnècles, PONT DE BOIS VERT"],
["ST00060","Chirens, CLERMONT"],
["ST00579","Chirens, COLLEGE"],
["ST00062","Chirens, GARANGERE"],
["ST00063","Chirens, GUILLETIERE"],
["ST00059","Chirens, L'ARSENAL"],
["ST00057","Chirens, LE FAGOT"],
["ST00058","Chirens, LE GAYET"],
["ST00061","Chirens, TOUR CLERMONT"],
["ST00056","Chirens, VILLAGE"],
["ST00082","Coublevie, BARRIOZ"],
["ST00068","Coublevie, BARTHELON"],
["ST00097","Coublevie, BEAUREGARD"],
["ST00585","Coublevie, BOUVIER DIVAT"],
["ST00086","Coublevie, CHEMAIN DE LA GRANDE SURE"],
["ST00071","Coublevie, COLLEGE PLAN MENU"],
["ST00065","Coublevie, CROIX BAYARD"],
["ST00077","Coublevie, ECOLE DU BERARD"],
["ST00080","Coublevie, HOPITAL"],
["ST00100","Coublevie, LAFAILLE"],
["ST00094","Coublevie, LAVOIR DU NEYROUD"],
["ST00067","Coublevie, LE BRET"],
["ST00578","Coublevie, LES NOYERS"],
["ST00079","Coublevie, MAIRIE"],
["ST00093","Coublevie, MAISON DE RETRAITE"],
["ST00081","Coublevie, MFR DALMASSIERE"],
["ST00069","Coublevie, MOLLARD"],
["ST00095","Coublevie, NEYROUD"],
["ST00092","Coublevie, ORGEOISE"],
["ST00101","Coublevie, PARKING PLAN MENU"],
["ST00070","Coublevie, PILET"],
["ST00066","Coublevie, PLACE DU 19 MARS 1962"],
["ST00064","Coublevie, PLACE E. BROCHIER"],
["ST00085","Coublevie, ROUTE DE LA BUISSE"],
["ST00078","Coublevie, ROUTE DE ST JEAN"],
["ST00076","Coublevie, ROUTE DES GORGES"],
["ST00073","Coublevie, RUE DU 11 NOV 1918"],
["ST00074","Coublevie, TIVOLIERE"],
["ST00072","Coublevie, ZA DU ROULET"],
["ST00544","Fontanil-Cornillon, CROIX DE ROCHETTE"],
["ST00545","Fontanil-Cornillon, LEP F. DOLTO"],
["ST00589","Fontanil-Cornillon, PALLUEL"],
["ST00001","La Bâtie-Divisin, MAIRIE"],
["ST00571","La Buisse, AFIPH"],
["ST00025","La Buisse, CHEMIN DU GAY"],
["ST00026","La Buisse, ECOLES"],
["ST00027","La Buisse, GRAND CHAMP"],
["ST00030","La Buisse, LE GAY"],
["ST00029","La Buisse, LE GAY GIRATOIRE"],
["ST00028","La Buisse, LE PANSU"],
["ST00024","La Buisse, PLACE"],
["ST00580","La Buisse, RESSOURCERIE"],
["ST00565","La Buisse, CENTR'ALP : ROSSIGNOL"],
["ST00187","La Murette, LA COURATIERE"],
["ST00186","La Murette, LE PAYSAN"],
["ST00185","La Murette, VILLAGE"],
["ST00197","Le Pin, BREZIN BOURG"],
["ST00200","Le Pin, CARREFOUR BREZIN"],
["ST00199","Le Pin, CENTRE EQUESTRE"],
["ST00198","Le Pin, LA CUAZ"],
["ST00201","Le Pin, LES ALLEX"],
["ST00195","Le Pin, PLACE SAINT CHRISTOPHE"],
["ST00196","Le Pin, VERS ARS"],
["ST00104","Massieu, COTE D'AINAN"],
["ST00103","Massieu, LA SARRA"],
["ST00102","Massieu, VILLAGE"],
["ST00109","Merlas, BOUTIERE"],
["ST00108","Merlas, CHAPELLE DE MERLAS"],
["ST00114","Merlas, FAGOTIERE"],
["ST00075","Merlas, LAYAT BAS"],
["ST00113","Merlas, LE BURLET"],
["ST00588","Merlas, LES ECHELLES"],
["ST00117","Merlas, LES GORGES"],
["ST00116","Merlas, MERLIETTE"],
["ST00106","Merlas, NOUVELIERE"],
["ST00107","Merlas, PICOUDIERE"],
["ST00112","Merlas, PIVOTIERE"],
["ST00110","Merlas, REYSSABOT"],
["ST00111","Merlas, ST SIXTE"],
["ST00105","Merlas, VILLAGE"],
["ST00550","Miribel-les-Échelles, EGLISE"],
["ST00547","Miribel-les-Échelles, LES EMPTAZ"],
["ST00546","Miribel-les-Échelles, ST ROCH"],
["ST00548","Miribel-les-Échelles, LE VERNEY"],
["ST00139","Moirans, BOIS DU FOUR"],
["ST00157","Moirans, BOULODROME"],
["ST00122","Moirans, CAMPALOUD"],
["ST00120","Moirans, CHALET"],
["ST00137","Moirans, CHAMPFEUILLET"],
["ST00158","Moirans, COLLEGE VERGERON"],
["ST00133","Moirans, COSTE GAZ"],
["ST00136","Moirans, COTE DES FILLES"],
["ST00134","Moirans, DELLORENZI"],
["ST00534","Moirans, ECHEVINS"],
["ST00131","Moirans, ESPACE JAIL"],
["ST00167","Moirans, GARE SNCF"],
["ST00135","Moirans, LE PAVILLET"],
["ST00162","Moirans, LES BALMES"],
["ST00127","Moirans, LES VIOLETTES"],
["ST00140","Moirans, LESARDIERE"],
["ST00126","Moirans, LOUIS MOYROUD"],
["ST00161","Moirans, LYCEE BEGHIN"],
["ST00141","Moirans, LYCEE PIERRE BEGHIN"],
["ST00125","Moirans, MAISONNEUVE"],
["ST00123","Moirans, MANGUELY"],
["ST00535","Moirans, MEDIATHEQUE"],
["ST00584","Moirans, MONTMARTEL"],
["ST00165","Moirans, NOVESPACE POMMARIN"],
["ST00128","Moirans, OUVRIERS PAPETIERS"],
["ST00159","Moirans, PARC DE LA GRILLE"],
["ST00124","Moirans, PETIT CHAMP FREY"],
["ST00138","Moirans, PETIT CRIEL"],
["ST00121","Moirans, POMPIERS"],
["ST00160","Moirans, RI D'OLON"],
["ST00132","Moirans, RUE DE LA COSTE"],
["ST00153","Moirans, RUE DU 8 MAI 1945"],
["ST00118","Moirans, SAINT JACQUES"],
["ST00163","Moirans, SCHNEIDER"],
["ST00166","Moirans, THALES LCD"],
["ST00493","Moirans, CROIX ROUSSE"],
["ST00533","Moirans, MONNAIR"],
["ST00181","Montferrat, 4 CHEMINS"],
["ST00177","Montferrat, JALAMION"],
["ST00176","Montferrat, LA GARENNE"],
["ST00178","Montferrat, LAC BLEU"],
["ST00173","Montferrat, LE VERNEY"],
["ST00175","Montferrat, LES ETEPPES"],
["ST00179","Montferrat, MUSEE"],
["ST00172","Montferrat, VERONNIERE"],
["ST00171","Montferrat, VILLAGE EGLISE"],
["ST00194","Paladru, CALATRIN"],
["ST00192","Paladru, GARAGE RENAULT"],
["ST00193","Paladru, LA TRUITIERE"],
["ST00190","Paladru, LES TROIX CHENES"],
["ST00189","Paladru, SAINT PIERRE DE PALADRU"],
["ST00191","Paladru, STADE"],
["ST00188","Paladru, VILLAGE"],
["ST00205","Pommiers-la-Placette, COL DE LA PLACETTE"],
["ST00207","Pommiers-la-Placette, LES BARNIERS"],
["ST00575","Pommiers-la-Placette, PALLACHERE"],
["ST00206","Pommiers-la-Placette, QUATRE BRAS"],
["ST00204","Pommiers-la-Placette, RD520 VILLAGE"],
["ST00574","Pommiers-la-Placette, TENNIS"],
["ST00209","Réaumont, BOURG ECOLE"],
["ST00216","Réaumont, CHEMIN DU MOULIN"],
["ST00210","Réaumont, LE BAYARD"],
["ST00217","Réaumont, LE BESSEY"],
["ST00213","Réaumont, LE CARRET"],
["ST00215","Réaumont, LE CARRET TRANSFO"],
["ST00214","Réaumont, LE MOURET"],
["ST00208","Réaumont, VILLAGE"],
["ST00621","Renage, CHATEAU"],
["ST00557","Renage, EGLISE"],
["ST00554","Renage, LA CROZE"],
["ST00555","Renage, LES PRAIRIES"],
["ST00556","Renage, PLACE CARDINALE"],
["ST00558","Renage, ZA LE PLAN"],
["ST00222","Rives, ABATTOIRS"],
["ST00221","Rives, ALLIMAND"],
["ST00239","Rives, BAS RIVES"],
["ST00225","Rives, BERLIOZ"],
["ST00234","Rives, CHARTREUSE"],
["ST00553","Rives, CLOS JUVIN"],
["ST00223","Rives, COLLEGE R. DESNOS"],
["ST00242","Rives, COURBATIERE"],
["ST00243","Rives, GARE SNCF"],
["ST00224","Rives, JEAN JAURES"],
["ST00232","Rives, LEVATEL"],
["ST00220","Rives, LIBERATION"],
["ST00231","Rives, MAISON DE RETRAITE"],
["ST00238","Rives, MALADIERE"],
["ST00233","Rives, PASTIERES"],
["ST00240","Rives, PLACE X BROCHIER"],
["ST00226","Rives, SADI CARNOT"],
["ST00252","Saint-Aupre, BARREAU"],
["ST00246","Saint-Aupre, BEC FIN"],
["ST00254","Saint-Aupre, CHAMPTORAZ"],
["ST00256","Saint-Aupre, CHEVALLIER"],
["ST00249","Saint-Aupre, CHEVILLARD"],
["ST00253","Saint-Aupre, COLOMBIER"],
["ST00251","Saint-Aupre, DELPHIN"],
["ST00248","Saint-Aupre, GRAND VIVIER"],
["ST00255","Saint-Aupre, LE GRAND CHEMIN"],
["ST00250","Saint-Aupre, MARGARON"],
["ST00247","Saint-Aupre, ROSSETIERE"],
["ST00245","Saint-Aupre, TURE"],
["ST00244","Saint-Aupre, VILLAGE"],
["ST00542","Saint-Blaise-du-Buis, BONPERTUIS"],
["ST00211","Saint-Blaise-du-Buis, LE GUICHARD"],
["ST00572","Saint-Blaise-du-Buis, CHATELARD"],
["ST00260","Saint-Blaise-du-Buis, CIMETIERE"],
["ST00265","Saint-Blaise-du-Buis, DEVEZ"],
["ST00262","Saint-Blaise-du-Buis, GRAND VOYE"],
["ST00257","Saint-Blaise-du-Buis, MAIRIE"],
["ST00261","Saint-Blaise-du-Buis, PETIT VOYE"],
["ST00258","Saint-Blaise-du-Buis, RAVIGNHOUSE"],
["ST00269","Saint-Blaise-du-Buis, ROUTE DU RIVIER"],
["ST00263","Saint-Blaise-du-Buis, RTE DE LA MURETTE"],
["ST00259","Saint-Blaise-du-Buis, ZA LE TALAMUD"],
["ST00272","Saint-Bueil, LA ROCHE"],
["ST00275","Saint-Bueil, LE SATRE"],
["ST00270","Saint-Bueil, RD82"],
["ST00218","Saint-Cassien, HALTE FERROVIAIRE"],
["ST00278","Saint-Cassien, EGLISE"],
["ST00280","Saint-Cassien, LE ROYER"],
["ST00279","Saint-Cassien, LE SAPIN"],
["ST00277","Saint-Cassien, MALOZA"],
["ST00284","Saint-Étienne-de-Crossey,  CARREF GD VIVIER"],
["ST00298","Saint-Étienne-de-Crossey,  CHARRAT"],
["ST00294","Saint-Étienne-de-Crossey,  COUCHONNIERE"],
["ST00282","Saint-Étienne-de-Crossey,  ETANG DAUPHIN"],
["ST00287","Saint-Étienne-de-Crossey,  GATELIERE"],
["ST00290","Saint-Étienne-de-Crossey,  LE PARIS"],
["ST00288","Saint-Étienne-de-Crossey,  LE PERRIN"],
["ST00285","Saint-Étienne-de-Crossey,  LE PICARD"],
["ST00297","Saint-Étienne-de-Crossey,  LE VIVIER"],
["ST00295","Saint-Étienne-de-Crossey,  LES GROS"],
["ST00289","Saint-Étienne-de-Crossey,  LES REYNAUDS"],
["ST00293","Saint-Étienne-de-Crossey,  LES ROUX"],
["ST00286","Saint-Étienne-de-Crossey,  POMPIERS"],
["ST00292","Saint-Étienne-de-Crossey,  TOLVON"],
["ST00283","Saint-Étienne-de-Crossey,  VACHONNES"],
["ST00281","Saint-Étienne-de-Crossey,  VILLAGE"],
["ST00322","Saint-Geoire-en-Valdaine,  BOULONGEAT"],
["ST00330","Saint-Geoire-en-Valdaine,  CHAFFARDIERE"],
["ST00304","Saint-Geoire-en-Valdaine,  CHAMPET"],
["ST00326","Saint-Geoire-en-Valdaine,  CHOCHE LE PARIS"],
["ST00324","Saint-Geoire-en-Valdaine,  CONSUOZ"],
["ST00331","Saint-Geoire-en-Valdaine,  CONSUOZ ABRIBUS"],
["ST00582","Saint-Geoire-en-Valdaine,  COTAGON"],
["ST00329","Saint-Geoire-en-Valdaine,  GENDARMERIE"],
["ST00310","Saint-Geoire-en-Valdaine,  HOPITAL"],
["ST00309","Saint-Geoire-en-Valdaine,  L'ORCIERE"],
["ST00536","Saint-Geoire-en-Valdaine,  LA COMBE"],
["ST00311","Saint-Geoire-en-Valdaine,  LA GLACIERE"],
["ST00305","Saint-Geoire-en-Valdaine,  LA PALE"],
["ST00328","Saint-Geoire-en-Valdaine,  LAMBERTIERE"],
["ST00320","Saint-Geoire-en-Valdaine,  LAREMBERT"],
["ST00319","Saint-Geoire-en-Valdaine,  LE FALQUE"],
["ST00318","Saint-Geoire-en-Valdaine,  LE GROSSET"],
["ST00325","Saint-Geoire-en-Valdaine,  LE MOLLARD"],
["ST00312","Saint-Geoire-en-Valdaine,  LE PLATON"],
["ST00323","Saint-Geoire-en-Valdaine,  LES BROSSES"],
["ST00327","Saint-Geoire-en-Valdaine,  LES HOPITAUX"],
["ST00317","Saint-Geoire-en-Valdaine,  LES PERRINS"],
["ST00313","Saint-Geoire-en-Valdaine,  PLAMPALAIS"],
["ST00142","Saint-Jean-de-Moirans, CHARTREUX"],
["ST00342","Saint-Jean-de-Moirans, COLOMB AUTOROUTE"],
["ST00341","Saint-Jean-de-Moirans, COLOMBINIERE"],
["ST00345","Saint-Jean-de-Moirans, GYMNASE"],
["ST00336","Saint-Jean-de-Moirans, L'ARCHAT"],
["ST00335","Saint-Jean-de-Moirans, LA MANCHE"],
["ST00333","Saint-Jean-de-Moirans, LE SCAIX"],
["ST00344","Saint-Jean-de-Moirans, LES TISSEUSES"],
["ST00538","Saint-Jean-de-Moirans, MAISON POUR TOUS"],
["ST00334","Saint-Jean-de-Moirans, MARCHE AUX CERISES"],
["ST00340","Saint-Jean-de-Moirans, PARABOOT"],
["ST00332","Saint-Jean-de-Moirans, PATINIERE"],
["ST00339","Saint-Jean-de-Moirans, PLACE"],
["ST00337","Saint-Jean-de-Moirans, RD1075"],
["ST00537","Saint-Jean-de-Moirans, TRINCON"],
["ST00354","Saint-Julien-de-Raz, CENTRE PNEUMOLOGIE"],
["ST00349","Saint-Julien-de-Raz, LAC"],
["ST00350","Saint-Julien-de-Raz, LE GARREL"],
["ST00355","Saint-Julien-de-Raz, LE PLAN"],
["ST00352","Saint-Julien-de-Raz, LE PUITS"],
["ST00348","Saint-Julien-de-Raz, VILLAGE"],
["ST00356","Saint-Nicolas-de-Macherin, CHATELONNIERE"],
["ST00360","Saint-Nicolas-de-Macherin, HAUTEFORT"],
["ST00362","Saint-Nicolas-de-Macherin, L'USINE"],
["ST00358","Saint-Nicolas-de-Macherin, LE PILON"],
["ST00361","Saint-Nicolas-de-Macherin, LES PRAIRIES"],
["ST00357","Saint-Nicolas-de-Macherin, MACHERIN"],
["ST00363","Saint-Nicolas-de-Macherin, MELISSARD"],
["ST00359","Saint-Nicolas-de-Macherin, PLACE"],
["ST00365","Saint-Sulpice-des-Rivoires, BOURG"],
["ST00364","Saint-Sulpice-des-Rivoires, CHATEAU D'EAU"],
["ST00367","Saint-Sulpice-des-Rivoires, FERME MOLLARD"],
["ST00366","Saint-Sulpice-des-Rivoires, LA PLATIERE"],
["ST00368","Saint-Sulpice-des-Rivoires, RIVOIRES"],
["ST00375","Tullins, COLLEGE CONDORCET"],
["ST00583","Tullins, CRUZILLE"],
["ST00389","Tullins, ECOLE DESMOULINS"],
["ST00369","Tullins, FURES"],
["ST00397","Tullins, GARE SNCF"],
["ST00379","Tullins, GOUY"],
["ST00377","Tullins, JARDIN DES ARTS"],
["ST00381","Tullins, L'ESLINARD"],
["ST00383","Tullins, LE MANGUELY"],
["ST00395","Tullins, LE PARADIS"],
["ST00374","Tullins, LE PAVE"],
["ST00370","Tullins, LE PORT"],
["ST00384","Tullins, LE VERT"],
["ST00382","Tullins, LES MASSONS"],
["ST00372","Tullins, MICHEL PERRET"],
["ST00380","Tullins, ORCEL"],
["ST00390","Tullins, PETIT TIZIN"],
["ST00373","Tullins, ROUTE DE GRENOBLE"],
["ST00391","Tullins, ST JEAN DE CHEPY"],
["ST00623","Tullins, STADE JEAN VALOIS"],
["ST00622","Tullins, VERDEMONT"],
["ST00624","Tullins, ZONE COMMERCIALE"],
["ST00398","Velanne, CENTRE"],
["ST00399","Velanne, LA SAUGE"],
["ST00581","Voiron, ACACIAS"],
["ST00402","Voiron, AVENUE DE PAVIOT"],
["ST00423","Voiron, BALTISS"],
["ST00456","Voiron, BD DU GUILLON"],
["ST00415","Voiron, BELVEDERE I"],
["ST00414","Voiron, BELVEDERE II"],
["ST00442","Voiron, BERIDOT"],
["ST00409","Voiron, BLANCHISSERIES"],
["ST00446","Voiron, BRAMERET"],
["ST00411","Voiron, BRUNERIE"],
["ST00448","Voiron, BRUNETIERE"],
["ST00418","Voiron, CENTRE SOCIAL"],
["ST00457","Voiron, CES LA GARENNE"],
["ST00444","Voiron, CHAMPFEUILLET"],
["ST00443","Voiron, CHAMPFEUILLET ZA"],
["ST00431","Voiron, CIMETIERE"],
["ST00447","Voiron, CLOS BERARD"],
["ST00417","Voiron, COLLEGE ST JOSEPH"],
["ST00445","Voiron, CROIX MORIN"],
["ST00472","Voiron, DENFERT ROCHEREAU"],
["ST00465","Voiron, DOCTEUR VALOIS"],
["ST00452","Voiron, ECOLE STE MARIE"],
["ST00485","Voiron, EDGAR KOFLER"],
["ST00460","Voiron, EDOUARD HERRIOT"],
["ST00416","Voiron, EGLISE ST PIERRE"],
["ST00425","Voiron, FATON"],
["ST00412","Voiron, FBG SERMORENS"],
["ST00494","Voiron, FERRONNIERE"],
["ST00464","Voiron, FRERES TARDY"],
["ST00600","Voiron, GARE NORD QUAI 01"],
["ST00601","Voiron, GARE NORD QUAI 02"],
["ST00603","Voiron, GARE NORD QUAI 04"],
["ST00604","Voiron, GARE NORD QUAI 05"],
["ST00562","Voiron, GARE NORD QUAI 03"],
["ST00607","Voiron, GARE SUD QUAI 08"],
["ST00608","Voiron, GARE SUD QUAI 09"],
["ST00611","Voiron, GARE SUD QUAI 12"],
["ST00612","Voiron, GARE SUD QUAI 13"],
["ST00613","Voiron, GARE SUD QUAI 14"],
["ST00614","Voiron, GARE SUD QUAI 15"],
["ST00615","Voiron, GARE SUD QUAI 16"],
["ST00487","Voiron, GENDARMERIE"],
["ST00419","Voiron, GENERAL LECLERC"],
["ST00450","Voiron, GEORGE SAND"],
["ST00420","Voiron, GEORGES FRIER"],
["ST00433","Voiron, GRAND ANGLE"],
["ST00413","Voiron, GYMNASE LA GARENNE"],
["ST00449","Voiron, HORTENSIAS"],
["ST00451","Voiron, IMPOTS"],
["ST00405","Voiron, L AGNELAS"],
["ST00436","Voiron, LAVOIR DE CRIEL"],
["ST00489","Voiron, LE PARVIS"],
["ST00488","Voiron, LE ROUSSET"],
["ST00625","Voiron, LE ROUSSET 2"],
["ST00407","Voiron, LE VERDIN"],
["TPV:1000740","Voiron, LEPRINCE RINGUET"],
["ST00492","Voiron, LES ECUREUILS"],
["ST00486","Voiron, LES TUILIERES"],
["ST00410","Voiron, LOUIS NEEL"],
["ST00459","Voiron, LYCEE MARTELLIERE"],
["ST00421","Voiron, MAIRIE"],
["ST00404","Voiron, MAISON BLANCHE"],
["ST00432","Voiron, MAISON ROSE"],
["ST00462","Voiron, MATERNITE CHIRURGIE"],
["ST00461","Voiron, MEDECINE"],
["ST00458","Voiron, MEDIATHEQUE"],
["ST00430","Voiron, MJC"],
["ST00428","Voiron, PAUL BERT"],
["ST00424","Voiron, PAVIOT"],
["ST00403","Voiron, PAVIOT ECOLE"],
["ST00406","Voiron, POLE DE VOUISE"],
["ST00437","Voiron, RUE DE CRIEL"],
["ST00439","Voiron, RUE DES CASTORS"],
["ST00426","Voiron, RUE DES GENTIANES"],
["ST00438","Voiron, RUE DES MARMOTTES"],
["ST00463","Voiron, RUE DU COLOMBIER"],
["ST00427","Voiron, RUE DU FATON"],
["ST00455","Voiron, RUE GUIMET"],
["ST00454","Voiron, SNCF"],
["ST00434","Voiron, STENDHAL"],
["ST00422","Voiron, VERDUN"],
["ST00429","Voiron, VICTOR HUGO"],
["ST00498","Voissant, EGLISE"],
["ST00499","Voissant, SOUS LE MONT"],
["ST00500","Voissant, VERCHERE"],
["ST00164","Voreppe, THALES TRIXELL"],
["ST00525","Voreppe, ALUMINIUM"],
["ST00514","Voreppe, AVENEUE DU 11 NOVEMBRE"],
["ST00509","Voreppe, BANNETTES"],
["ST00513","Voreppe, BASCULE"],
["ST00517","Voreppe, CAFE ADRAIT"],
["ST00521","Voreppe, CHARMINELLES"],
["ST00519","Voreppe, CHASSOLIERE"],
["ST00505","Voreppe, CHEVALON"],
["ST00503","Voreppe, DOCTEUR THEVENET"],
["ST00524","Voreppe, ELS GROUP"],
["ST00530","Voreppe, GARE SNCF"],
["ST00522","Voreppe, L'ARCADE"],
["ST00512","Voreppe, LOGIS NEUF"],
["ST00527","Voreppe, LOUIS ARMAND"],
["ST00515","Voreppe, MAIRIE"],
["ST00506","Voreppe, MALOSSANE"],
["ST00510","Voreppe, MONUMENT AUX MORTS"],
["ST00526","Voreppe, POMA"],
["ST00529","Voreppe, RADIALL"],
["ST00528","Voreppe, SAMLLOC"],
["ST00504","Voreppe, SEMINAIRE"],
["ST00520","Voreppe, VOLOUISE"],
["ST00620","Vourey, LAVOIR"],
["ST00532","Vourey, PRESSOIR"],
];

